### PR TITLE
PitchTo function

### PR DESCRIPTION
**Pull request by MekBoss**
Function which return pitch from one actor to another.
Not sure that I should use trigonometric function, but it work.

I remember I see someone who ask about it on forum.

### CODE REVIEW

**Comment by raa-eruanna** [comment]
It seems like this was created using GitHub directly, rather than using a standard Git client. The issue here is, that it created 3 commits. These should be squashed.

**Comment by coelckers** [comment]
This also subtracts the positions directly without using the portal aware helper functions. Sorry, not usable this way.

**Comment by MekBoss** [comment]
>portal aware helper functions
Which means...?
I suspect that I should not have to use "raw" position.

>this was created using GitHub directly
Im still new to github and dont have an expirience with using this. Sorry about this.

**Comment by MekBoss** [comment]
Understood.
And last one

>It seems like this was created using GitHub directly, rather than using a standard Git client. The issue here is, that it created 3 commits. These should be squashed.

What is "standard Git client"?

**Comment by raa-eruanna** [comment]
https://git-scm.com/downloads

Git will replicate this repository onto your own system and allow you to modify the files directly, test them, commit and upload them, so that you can create a new pull request here.

If you're using Windows, you can also use TortoiseGit. https://tortoisegit.org/

**Comment by PROPHESSOR** [comment]
@MekBoss You can use [GitKraken](https://www.gitkraken.com/). It's a crossplatform graphical GIT client easy to use.

**Comment by MekBoss** [comment]
I fear, my skill of RTFM fails every time I use it. Because I still dont understand how to do so.
And GUI only make it worse.

**Comment by MekBoss** [comment]
I think I understand how to use git. What should I do now, close this pull request and open new?

**Comment by MekBoss** [comment]
Dont mind me, I working on it.

**Comment by coelckers** [comment]
Please redo this. Something has gone wrong here and the PR is no longer usable.

**Pull request closed without merging**
