### PR TITLE
Export AllClasses

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
Should be self-explanatory

### CODE REVIEW

**Comment by coelckers** [comment]
What for`?

**Comment by ZippeyKeys12** [comment]
There’s a bunch of data management and classes are by prefix, so it’s easier to load it that way.
There was a bigger reason but I can’t remember it right now, I’ll add it if I do.

**Comment by MajorCooke** [comment]
Graf is busy with RL projects. Just be patient.

**Comment by ZippeyKeys12** [comment]
I was hoping for mental or Rachel to say if they thought it was going to get no'd. Yeah, I mean no one has said anything on GetStatSize yet.

**Comment by ZippeyKeys12** [comment]
There’s a registry of all items, which requires that items are loaded before the player is spawned. Right now, I have to add each one, but I want it to be automated using class name. If the class name starts with ZMA_, it can be added to the marine upgrades registry. The main reason to do so other than a function to register them is because a lot of the rest of my systems run on class prefixes, so it makes sense to keep it consistent. Also for NPCs they need to be loaded too, and their data isn't contained in an actor because I need to do off-map simulation, so I want to do the same as the item registry and monitor NPCs.

**Pull request merged**
