### PR TITLE
Remove FindSDL2 find-module, use sdl2-config.cmake instead

### PR DESCRIPTION
**Pull request by vilhelmgray**
This requires SDL >= 2.0.4.

Since <https://bugzilla.libsdl.org/show_bug.cgi?id=2464> was fixed in
SDL 2.0.4, SDL behaves as a CMake "config-file package", even if it was
not itself built using CMake: it installs a sdl2-config.cmake file to
${libdir}/cmake/SDL2, which tells CMake where to find SDL's headers and
library, analogous to a pkg-config .pc file.

As a result, we no longer need to copy/paste a "find-module package"
to be able to find a system copy of SDL >= 2.0.4 with find_package(SDL2).
Find-module packages are now discouraged by the CMake developers, in
favour of having upstream projects behave as config-file packages.

This results in a small API change: FindSDL2 used to set SDL2_INCLUDE_DIR
and SDL2_LIBRARY, but the standard behaviour for config-file packages is
to set <name>_INCLUDE_DIRS and <name>_LIBRARIES. Use the CONFIG keyword
to make sure we search in config-file package mode, and will not find a
FindSDL2.cmake in some other directory that implements the old interface.

In addition to deleting redundant code, this avoids some assumptions in
FindSDL2 about the layout of a SDL installation. The current libsdl2-dev
package in Debian breaks those assumptions; this is considered a bug
and will hopefully be fixed soon, but it illustrates how fragile these
assumptions can be. We can be more robust against different installation
layouts by relying on SDL's own CMake integration.

When linking to a copy of CMake in a non-standard location, users can
now set the SDL2_DIR or CMAKE_PREFIX_PATH environment variable to point
to it; previously, these users would have used the SDL2DIR environment
variable. This continues to be unnecessary if using matching system-wide
installations of CMake and SDL2, for example both from Debian.

This is based on the patch written by Simon McVittie for OpenJK:
https://github.com/JACoders/OpenJK/commit/52030235f052772008d99e6ccb16de48e7ddb688

### CODE REVIEW

**Comment by madame-rachelle** [comment]
The reasoning shown here sounds solid; but what I worry about most is whether or not it actually works on the distros that we are targeting. Debian, incidentally enough, being among the primary ones.

If the changes here cause no issue with the currently supported Debian variants, including Ubuntu and Mint (so long as they are still within their LTS support status), then I see no reason not to merge these changes.

**Comment by madame-rachelle** [comment]
That is precisely what I was worried about, I didn't even know Travis was missing from the stats there.

@vilhelmgray while I appreciate the initiative to actually do something, and not just armchair-dev like a lot of people do, a lot of your pull requests seem to have a tendency to muscle us into an arbitrary standard of the "proper" way to do things - and in this case, it comes at the expense of even compiling at all on the distros that by far the greater majority of our Linux users use.

Clearly, there's two standards here: what you insist is the "right way" to do things, and what, practically and empirically, actually works. In the future, I beg you please, actually care about the latter. Standards truly mean precisely fuck all when things break - and you aren't going to change Debian overnight to be more standards-conformant with a humble and tiny project like GZDoom.

**Comment by alexey-lysiuk** [comment]
Actually, the change is OK. Sorry, at the moment I don't have possibility to check myself why it failed.

**Comment by madame-rachelle** [comment]
Huh, I take back what I said then, at least about this pull request. Whatever is relevant in this one, that was relevant in that big debacle in one of the previous ones still applies, though.

I got it to build successfully on my system.

I wonder if the Travis VM's/jails are having connection issues, maybe that's why it didn't compile.

**Comment by alexey-lysiuk** [comment]
```
CMake Error at src/CMakeLists.txt:1164 (add_executable):
  Target "zdoom" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
  has leading or trailing whitespace.  This is now an error according to
  policy CMP0004.
```

**Comment by vilhelmgray** [comment]
> ```
> CMake Error at src/CMakeLists.txt:1164 (add_executable):
>   Target "zdoom" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
>   has leading or trailing whitespace.  This is now an error according to
>   policy CMP0004.
> ```

It took me a while to figure out what was happening here -- perhaps I have upset some ancient Martian gods since my gzdoom PRs always seem to collide with some esoteric corner cases.

Anyway, this is an [upstream bug that was fixed back in 2016](https://hg.libsdl.org/SDL/rev/e723c663ba58).

This is [bug 822210](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822210) in the upstream Debian bug tracker.

Travis is installing an [old version of SDL2 (*2.0.4+dfsg1-2ubuntu2.16.04.2*)](https://travis-ci.org/github/coelckers/gzdoom/jobs/668543276#L530) that has the bug so that's why it's failing.

Debian patched this bug with their [*2.0.4+dfsg2-1* version release](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822210#52). But Ubuntu Xenial is on an [old version (*2.0.4+dfsg1-2ubuntu2.16.04.2*) still](https://packages.ubuntu.com/xenial/libsdl2-dev); this is likely an oversight on Ubuntu.

I can open a bug on Ubuntu requesting the developers to update the package to fix this bug because it's not specific to GZDoom and affects all SDL2 installations.

**Comment by alexey-lysiuk** [comment]
Ubuntu 16.04 is still maintained, and we support it as well. If it doesn’t build out of the box, then it’s a bit premature merge this change.

**Comment by vilhelmgray** [comment]
For now I have opened up a bug report for the Ubuntu package here: https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1869757

Ideally Ubuntu will pick up the Debian patch and resolve this issue. If not, then I'll update this patch by adding a **STRIP** command to make sure the `SDL2_LIBRARIES` string is clean before we link. For now, we can wait and see how the Ubuntu team responds.

**Comment by vilhelmgray** [comment]
**Ubuntu Xenial 16.04 LTS** is currently in ["Extended Security Maintenance (ESM)"](https://ubuntu.com/esm), meaning only security-critical fixes are applied to this version until its [end-of-life date (April 2021)](https://help.ubuntu.com/community/EOL#Ubuntu_16.04_Xenial_Xerus). This means the bug report I filed for the **libsdl2** package in Xenial will likely not be addressed because it's not a security bug.

Because the EOL for Xenial will be here soon, it'll be better to simply wait until April 2021 to merge this PR instead of implementing a **STRIP** solution just to revert it some months later once it's no longer relevant. So for now let's postpone this PR, and I'll recomment again when the EOL has passed for Xenial.

**Comment by Cacodemon345** [comment]
This should be merged in anticipation of Ubuntu  16.04 going out of support very, very soon.

**Pull request merged**
