### PR TITLE
EventHandlers: NewGame and OnUnregister order fixes

### PR DESCRIPTION
**Pull request by Player701**
Currently, all EventHandlers (including StaticEventHandlers) fire their NewGame event after their WorldLoaded event. This setup seriously limits the usefulness of the NewGame event, as it cannot be used to affect the logic implemented in other events normally fired when starting a new level (like CheckReplacement). This PR rectifies this by introducing the following changes:

1. StaticEventHandlers will fire their NewGame event before a level is loaded. This ensures that global new-game initialization takes place before any per-map handlers enter the scene.

2. Normal EventHandlers will fire their NewGame event after they have been registered and before anything else. This ensures that local new-game initialization takes place before per-map handlers actually start doing something.

There is also a problem with StaticEventHandlers being unregistered before normal EventHandlers when leaving the game. The following changes are introduced to take care of this:

3. StaticEventHandlers will be unregistered _after_ unloading the current level, instead of before (current behavior). This eliminates the need to check if a StaticEventHandler still exists in case a per-map EventHandler needs to talk to it in its OnUnregister event.

4. All event handlers will be unregistered in reverse order, compared to their registration order. This ensures that at any given time, for every event handler which is currently executing, any event handlers registered before it are guaranteed to exist. 

To see what kinds of things are not possible with the current order of events, see [here](https://forum.zdoom.org/viewtopic.php?f=2&t=62398). The example outlined there depicts a settings system where some settings can only be changed for a new game. If any of these settings is supposed to affect the behavior of events defined in per-map handlers (for example, we want to make an option which replaces a weapon with another weapon, so we need to get the value of the setting in CheckReplacement), then the values of these settings are absolutely required to be initialized _before_ any other events fire, but _after_ we determine whether a new game has started. Currently, there is no suitable entry point for this.

Regarding the PR code-wise, it's probably important to note that a new argument had to be introduced in G_DoLoadLevel and P_SetupLevel to check for a new game and decide whether to fire the NewGame event. I'm not fond of global variables, so I had to add an argument instead, just to be on the safe side (I'm saying this because I see that global variables seem to be used quite extensively thoughout the code).

In case there are any mods which depend on the current behavior... well, considering that the NewGame event itself is a relatively recent development, there probably aren't too many projects that use it, and I highly doubt these changes may break anything irreparably. If this somehow turns out to be the case, then we could introduce a new event to fire on a new game but before a level is loaded, without re-purposing NewGame for that. 

There is also an issue where the WorldUnloaded event is only fired on level transitions (i.e. by exiting normally or using the "changemap" command), but not when exiting the game completely, starting a new game or loading a new level via the "map" command. Interestingly enough, per-map handlers are affected by this but static handlers are not. I'm not sure if this is a deliberate design choice or a limitation of the current setup in the engine, so I guess I'd better not touch this for now.

### CODE REVIEW

**Comment by remyabel** [comment]
Passing around a variable with global state is effectively the same as a global variable, so if your concern is avoiding global variables, you might as well use one. My primary concern is that boolean arguments are hard to reason about. For example in `G_DoLoadLevel` you have `if (newGame) { E_NewGame(false); }` but in `P_SetupLevel` you have `if (newGame) { E_NewGame(true); }` This is already vexing to the reader, but if you made a typo anywhere along the call chain, it becomes difficult to debug.

Have you considered using something more explicit like an `enum` to show state?

**Comment by Player701** [comment]
All right, if you say there's nothing wrong with it, I guess I could change it a bit later then (I'm currently at work) - though I think `EventState` is probably not a very good name for such a enum. I will try to come up with a better name.

**Comment by Player701** [comment]
Changed the bool argument in `E_NewGame` to an enum argument. I've named the enum `EventHandlerType` and made it an `enum class` instead of a plain `enum` to avoid potential naming conflicts. Existing functions have been left untouched.

**Comment by ZippeyKeys12** [comment]
It was intentional that it fired after world loading, but I didn't realize it fired after `CheckReplacement`. Also a `bool` was fine, it just had an unclear name.

**Comment by Player701** [comment]
Well, this is just awesome. Thanks a lot!

And if someone needs to check for a new game after the world has loaded, it is always possible to store this information in a vairable and make use of it in the WorldLoaded event.

**Pull request merged**
