### PR TITLE
Compatibility for Hellbound MAP29

### PR DESCRIPTION
**Pull request by MajorCooke**
Some of the ceilings in the monster closets weren't high enough to allow the cyberdemons to pass, making 100% kills impossible. This is caused by the floors not going down far enough and stopping at a certain height above the next closest floor.

### CODE REVIEW

**Comment by drfrag666** [comment]
I've investigated it (with ZETH-win32!) and this is okay to merge.

**Comment by coelckers** [comment]
I repeat what I said on the forum: This change massively alters how the level plays, better remove the Cybers entirely instead.

**Comment by drfrag666** [comment]
Understood. But i still think it's a map bug and the intention of the author was to allow them to teleport. He didn't put them there to be blocked and "only" two appear on easy.

**Comment by madame-rachelle** [comment]
Intention and effect are two different things and it's very difficult to judge the best way to handle this based on that.

Nevertheless, however, I will echo what Graf said - the level has existed this long in its broken state, changing it now will drastically alter how the map is played, and GZDoom was not made for that.

This is one example of a change that I consider to be a bit arbitrary - now, if it were a couple imps that got stuck, sure, have at it - sure, we can release a couple more imps into the fray - but it's cyberdemons, and cybies have the potential to cause the player massive issues.  - Which as you pointed out, they were actually intended to - but, like I said, the level has existed in this state for this long where they haven't.

This is a prime example of the overreach that GZDoom has over others' levels using the compatibility system. As Peter Parker's Uncle Ben once said - "with great power comes great responsibility." If the author wants the cyberdemons to wreak havoc on the player at the end of the level, it's up to him to come back and fix that.

**Comment by madame-rachelle** [comment]
I will say this though: It appears that the level set was meant to be compatible with prBoom. If the cyberdemons work properly in prBoom, then this change would make a lot more sense. If they are still stuck in prBoom though, then removing them would be better.

**Comment by MajorCooke** [comment]
I tested with PrBoom+. The cyberdemons do indeed remain stuck there. Not sure if this will make a difference in PrBoom itself but I don't think it will. 

@coelckers what function is there to remove the specific actors again?

**Comment by drfrag666** [comment]
@madame-rachelle: That makes sense.
@MajorCooke: as expected, else it would be a major problem in the engine.
 But removing them what for? That wouldn't change anything.
 Don't you think you're looking too much into it?

**Comment by MajorCooke** [comment]
Currently it prevents earning 100% kills. So the cyberdemons will need to be removed.

**Comment by drfrag666** [comment]
Sure, i forgot about that.

**Comment by madame-rachelle** [comment]
> coelckers what function is there to remove the specific actors again?

There isn't any, as far as I know, but you don't need it. Instead, just set its spawn flags to 0 and it should prevent it from appearing at all. An example is in level_compatibility.zs at line 184:

```			case '2C4A3356C5EB3526D2C72A4AA4B18A36': // TNT: Evilution map29
			{
				// remove mancubus who always gets stuck in teleport tunnel, preventing
				// 100% kills on HMP
				SetThingFlags(405, 0);
				break;
			}
```
So please do it this way. :)

**Comment by coelckers** [comment]
You cannot delete anything from the array of things to be spawned. Some parts of the engine need the index, e.g. FraggleScript.
Setting the spawn flags to 0 is the defined method to handle this case.

**Comment by MajorCooke** [comment]
Done.

**Pull request merged**
