### PR TITLE
Update settings in favor of libADLMIDI and libOPNMIDI updates

### PR DESCRIPTION
**Pull request by Wohlstand**
This is a changeset made in favor of libADLMIDI and libOPNMIDI update, made at ZMusic side in this PR: https://github.com/coelckers/ZMusic/pull/12
This changeset is depends on the ZMusic side changes.

P.P.S. A question: which good CSV editor you use for this? Importing and Exporting with LibreCalk does making of much more changes in the file than I wanted (mainly spacing removals, etc.). I wanted to fill some Russian and other translations I can make, however, a raw CSV seems hard to maintain without of special tools :suspect:

**Reply by Graf:** 
None. The original sheet is hosted on Google.  Here's the relevant info: https://forum.zdoom.org/viewtopic.php?f=49&t=63737

Please add the texts there. I cannot merge this PR with changes to the CSV, the contents would get lost at the next text update.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Okay, I did all changes at the Google Document. However, just now I found another bug: at libOPNMIDI, the external bank won't load... :suspect:

**Comment by Wohlstand** [comment]
AHA!!! I see why that bug happens: inside of the ZMusic, instead of an absolute path, you passing a basename only! :eyes: 
изображение

**Comment by Wohlstand** [comment]
Okay, the source of the string is GZDoom, gonna fix the bug at it...

**Comment by Wohlstand** [comment]
Okay, I fixed that bug at the ZMusic side, seems it works now as intended! I also added SysEx calls which were supported by both ADLMIDI and OPNMIDI, and so, let's use them!

**Comment by madame-rachelle** [comment]
> 
> 
> > > P.P.S. A question: which good CSV editor you use for this? Importing and Exporting with LibreCalk does making of much more changes in the file than I wanted (mainly spacing removals, etc.). I wanted to fill some Russian and other translations I can make, however, a raw CSV seems hard to maintain without of special tools :suspect:
> 
> None. The original sheet is hosted on Google. Here's the relevant info: https://forum.zdoom.org/viewtopic.php?f=49&t=63737
> 
> Please add the texts there. I cannot merge this PR with changes to the CSV, the contents would get lost at the next text update.

I just would like to point out that it seems this accidentally got edited instead of quoted as a reply.

**Comment by Wohlstand** [comment]
> I just would like to point out that it seems this accidentally got edited instead of quoted as a reply.

Okay, I had to re-write back my initial message, and I was added a missing ZMusic side PR link as a note.

**Comment by coelckers** [comment]
I merged this manually to completely prune the changes to the .CSV file.

**Pull request closed without merging**
