### PR TITLE
Various xBRZ improvements

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
https://forum.zdoom.org/viewtopic.php?t=61499

### CODE REVIEW

**Comment by coelckers** [comment]
What's the point of the old version? I cannot see any real differences between it and the new one.

**Comment by alexey-lysiuk** [comment]
They are different especially in how alpha channel is scaled. For example, compare numbers in althud. Also, take a closer look at sprite edges, player’s weapon is the best example.
Personally I really dislike the new version and use only the old one. It’s a matter of taste though.

**Comment by raa-eruanna** [comment]
@alexey-lysiuk If I create a version that combines this with #587 would you prefer I squash your commits together or do you want to keep them separate?

**Comment by alexey-lysiuk** [comment]
Keep them because these changes can be reverted separately if something will go wrong.

**Comment by raa-eruanna** [comment]
Okay, done in #593

**Pull request closed without merging**
