### PR TITLE
Update portal.cpp copyright attribution

### PR DESCRIPTION
**Pull request by Altazimuth**
It's just a copyright notice; no more, no less.

### CODE REVIEW

**Comment by Altazimuth** [comment]
@coelckers In light of the GZDoom release (congrats by the way!) I was hoping you might have some time to look at this? Given it's a measly 3 lines changed I figure it'll be less than a minute to read properly.

**Comment by dpjudas** [comment]
@Xane123 The license file in the root project folder is enough. It covers every file unless it explicitly has a different license attached to it. Spamming every source file is a tradition used by many, but there's no need to follow it.

@Altazimuth Replacing one muddy "copyright statement" with another is pointless. Either this file is copyrighted by SoM or it is not. If he feels that the file is infringing he should step forward himself and point out exactly what he think is his work. Then Graf can either negotiate a license with him or remove whatever implementation is supposed to be problematic here. I'm closing this PR as it doesn't really fix anything if there's a copyright dispute.

**Comment by Altazimuth** [comment]
> Replacing one muddy "copyright statement" with another is pointless.
It's also harmless and corrects the current one. What do you have to lose from accepting it?

**Comment by Altazimuth** [comment]
> Replacing one muddy "copyright statement" with another is pointless.

@dpjudas It's also harmless and corrects the current one. What do you have to lose from accepting it?

**Comment by MatthewTheGlutton** [comment]
They say the opposite things.

Current: we did NOT take code from Eternity but we acknowledge that some things got reinvented in roughly the same shape.

Proposed: we DID take code from Eternity.

Whichever one is the case, that should prevail.

**Comment by somtwo** [comment]
I mean, the code is blatantly ripped from code I wrote in EE, Quasar showed that years ago. Why anyone is even questioning that is beyond me. As far as I'm concerned this commit is the only close-to-ethical thing to do at this point, and is more than I expected years after this code was stolen. Like, seriously, I worked my ass off to make this work.

**Comment by alexey-lysiuk** [comment]
Could you please post a link to this investigation? Thanks.

**Comment by dpjudas** [comment]
@somtwo I have no idea if something is stolen or not (I did not write this code). But I do think that this kind of accusation is quite serious. Like legally serious. Because of that we are just asking for evidence of what is stolen so we can judge the accusation.

I closed the PR because it essentially acknowledges the accusation. I'm not Graf, so if you have good proof he will have to decide what he wants to do. Personally, I would make a clear copyright at the top of the file including your name if parts or whole indeed was written by you. Just keep in mind that ideas in itself is not copyrightable - that's what patents are for.

**Comment by dpjudas** [comment]
Okay after checking the EE license, I can see both are GPL. So I guess legally this really boils down to a (possibly) removed copyright line at the top of a source file. In any case, I think if the line should be fixed it should be done with a properly copyright statement and not what Altazimuth suggested.

Consider me out of this thread because I frankly can't be bothered with these Doom community disputes when its down to a name written in a source file or not.

**Comment by jmtd** [comment]
@dpjudas I bet you'd feel differently if it was your name/work and not someone else's.

**Comment by caligari87** [comment]
It also looks like the question was debated and resolved in that thread, so why is it being brought up again?

**Comment by dpjudas** [comment]
@jmtd No, I would not. First, imitation is the sincerest form of flattery, and secondly take a look at all the vulkan source files in GZD and notice how I did not even bother adding the copyright boiler and my name to it.

I can understand if someone else cares more, but at the same time I find it very silly to contribute to open source, GPL of all things, and then afterwards gets offended when other people looked at it and used some of the ideas. Even IF the accusation of copyright is correct we talking about copying from one GPL project to another, in a small community where everyone knows which source port added portals first (that would be EE, even I know this and I showed up years later)..

**Comment by coelckers** [comment]
Some people here really have no f*cking clue what they are doing with their reckless actions and in what kind of legal bind they are placing other people with this.

@SoM:
You should never *ever* publicly accuse others of wrongdoing without having irrefutable proof about the matter - which you simply cannot have because the core part of the disputed code is totally different from Eternity's equivalent.

To make it clear: The proposed change of the attribution presented a major problem for me because it plain and simply misrepresents the facts and would have indirectly forced me to having violated the license in a way I did not do.

So here's how this will be solved - and please note that I took the pointers directly from how Eternity handles attribution:
I changed the license of the disputed file to be explicitly GPLv3. I added no explicit attribution to this file, what I instead chose to do is give Eternity Engine a general attribution in the file listing copyright attribution. This is fair because there has been the occasional bit of code taken from Eternity, e.g. some small bits in the polyobject code or a blockmap validation routine and maybe some other small bit that got missed and forgotten. But that's the extent I am willing to go here.

If you think that isn't enough - please have a check of all the copyright headers in Eternity - they were all edited to remove the people previously working on - all those were offloaded to an external AUTHORS file - so in my opinion it's just appropriate to do the same here.

**Pull request closed without merging**
