### PR TITLE
Fix bouncing missiles not dealing damage when hitting top/bottom

### PR DESCRIPTION
**Pull request by Cacodemon345**
Also exports the new function P_DoMissileDamage to ZScript.

### CODE REVIEW

**Comment by drfrag666** [comment]
@alexey-lysiuk So is it okay now? Looks good. It's been merged into QZDoom but devbuilds are failing (transition to ZMusic as dll, same happened in GZDoom) I'm going to merge this in a while and upload a devbuild for testing. I'll contact @Blzut3 to tell him to delete the cache.

**Comment by alexey-lysiuk** [comment]
Kinda. I'm still not sure that [this](https://github.com/coelckers/gzdoom/pull/1068/files#diff-04640343fab52042b04b0df49f61a64bR3976) is the right place to call the damage function.

**Comment by drfrag666** [comment]
Thanks, i've merged it and uploaded a test build.

**Comment by OrdinaryMagician** [comment]
If there's one small gripe I have with this, it's that you made that DoMissileDamage function static. I don't see there being a reason for that.

**Comment by drfrag666** [comment]
Is there something still missing here? I already merged the new commit (non static) and for me it looks good (i could be missing something tough).

**Comment by coelckers** [comment]
No, the only thing is that none of the other devs here seems to be willing to act on their own.

**Comment by madame-rachelle** [comment]
I typically do not act on pull requests when the reviews are still active. When they are dismissed (without merging the pull request) that sends a signal to me that the concerns listed in the review have been addressed and the request can be tested and merged.

**Comment by MajorCooke** [comment]
@madame-rachelle He dismissed the review, is now a good time? =D

**Comment by MajorCooke** [comment]
@alexey-lysiuk Would you say it's good now?

**Pull request merged**
