### PR TITLE
Export INI parser to ZScript

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
[Sample PK3](https://www.dropbox.com/s/6qlp2q2nc5e9q5i/appetizers.pk3?dl=0)
Put `event readtext` into console to test.

Add INIParser with `Read`, `Get`, `Set` and `Clear`.

### CODE REVIEW

**Comment by ZippeyKeys12** [comment]
1. I had to add the clear argument internally for multiple ini's. This is so one can have variables overwritten by submods. Because it was needed internally, I figured I might as well export it. I'll fix the duplicates.
2. The functionality is in FConfigFile, so I exported it. It wasn't like the write functions where it didn't make any sense.
3. Sure
4. My bad

**Comment by ZippeyKeys12** [comment]
I’ve done all the fixes, but I feel that `Set` to provide user freedom, it’s up to the user to use it responsibly. The main use-case I envisioned was allowing for users to implement inheritance as well as user changes. If you really want me to remove it I can.

**Comment by coelckers** [comment]
Sorry for being late, but I have to agree with alexey-lysiuk here. If the Set function is not safe, i.e. it does not do what anyone would expect, it should be omitted. And if it does not overwrite an existing key of the same name, it is not really safe, especially when the data cannot be written back.

Regarding class vs. struct, it is a bit more tricky. Normally any object being created at script execution needs to be a class object - a struct is just a plain set of data.
But keep in mind that the INI cannot be retained because it's not serializable and also has no means to be read back from its source lump.
I think this is far more important than anything else, if you want to use this as a user-provided dictionary of key/value pairs it will normally have to stick around - but then there need to be means to restore it when loading a savegame.
And now the Set method will become the big issue. Without it, restoring it will mean to merely reload the source data, but with Set in this will require full serializer support!

**Comment by alexey-lysiuk** [comment]
The main issue of Set is that mere fact that it doesn’t belong to a parser. INI parser should produce an _immutable_ dictionary, i.e. key/value pairs grouped by sections. This object cannot be altered.
This PR combines loader with a _mutable_ string-to-string map. In its current form it allows to use INIParser as a generic dictionary. And I’m pretty sure that someone will do exactly this.

In my opinion there should be two entities: a dictionary (it can be mutable and serializable) and a parser that creates such dictionary as a result of its operation.

**Comment by ZippeyKeys12** [comment]
I’m going to comment out the `Set` function. Once I figure out serialization, this conversation will be more relevant.
Just to be clear, the `Set` function works properly. It’s just useless without serialization as Graf has pointed out.

**Comment by coelckers** [comment]
> In my opinion there should be two entities: a dictionary (it can be mutable and serializable) and a parser that creates such dictionary as a result of its operation.

What? You want a second class for just the one reader function? That doesn't sound very efficient. For that a static method that returns an initialized dictionary would suffice.

In any case, even for an immutable dictionary, it at least needs to remember the lump name so that it can be restored from that later, so you cannot fully separate the data from its source.

**Comment by ZippeyKeys12** [comment]
Honestly this should be able to be serialized before it's even added, so it's gonna be a while

**Comment by alexey-lysiuk** [comment]
> Just to be clear, the `Set` function works properly. It’s just useless without serialization as Graf has pointed out.

It’s not only useless but dangerous. It allows to use this parser as a dictionary without actually parsing anything.
Lack of generic dictionary type in ZScript will certainly provoke such abuse.

> What? You want a second class for just the one reader function? That doesn't sound very efficient. For that a static method that returns an initialized dictionary would suffice.

I meant that parser functionality should not be combined with dictionary in _one instance_ of a class. Implementation details are secondary here.

**Comment by ZippeyKeys12** [comment]
Actually redoing this where it'll be much better for serialization

**Pull request closed without merging**
