### PR TITLE
Implement FVector in ZScript for member variables

### PR DESCRIPTION
**Pull request by MrRaveYard**
Adds FVector2 and FVector3 into ZScript for the purpose of supporting member variables.

The values are stored as floats in memory, however load and store ops do conversion to/from double, so the math operations and etc. are that of a regular Vector2 or Vector3. Same goes for local variables, function parameters and return values.

### CODE REVIEW

**Comment by coelckers** [comment]
Cool!

This will allow us to shrink the size of AActor quite a bit as many of its variables that are rarely used do not need double precision.

Since you marked this "work in progress", what's left to do here?

**Comment by MrRaveYard** [comment]
Mostly because I don't feel confident in some of the changes. Also I've mostly tested FVector2 so far. I'll do further testing of FVector3 later today.

**Comment by MrRaveYard** [comment]
I tested both FVector2 and FVector3 and there's nothing else that I wanted to change, so now I'm waiting for feedback.

**Comment by coelckers** [comment]
Looking good on first sight.

**Comment by nashmuhandes** [comment]
@MrRaveYard now that this has been implemented, perhaps it's a better time now to revisit interpolated actor scale? https://github.com/coelckers/gzdoom/pull/1043

**Pull request merged**
