### PR TITLE
ChexQuest 3 BIGFONT in lump format

### PR DESCRIPTION
**Pull request by Nemrtvi**
No extra characters—just the original set of fonts from chex3.wad in a lump format.

### CODE REVIEW

**Comment by coelckers** [comment]
Any reason why this was prematurely merged? I said in the forum that this needs a bit of added work before becoming usable.

**Comment by Nemrtvi** [comment]
> 
> 
> Any reason why this was prematurely merged? I said in the forum that this needs a bit of added work before becoming usable.

I suppose it’s better to specify that on the commit next time. :D

**Comment by madame-rachelle** [comment]
Sorry about that. Yeah, put it on the commit, please.

**Comment by madame-rachelle** [comment]
@coelckers do you want me to push a revert commit? This will require that Undead rebases his work locally in order to override the revert when this gets submitted again. Or I can leave it as-is and he can just fix it on his own later on.

**Comment by coelckers** [comment]
No. By now I made the needed changes, but this commit on its own would have broken a bit of stuff because the IWAD font was still there and order of application of this filter and the competing game_doomchex was undefined.

**Pull request merged**
