### PR TITLE
Dealing with C++ classes and C memory functions handling fixes.

### PR DESCRIPTION
**Pull request by devnexen**
One overflow copy fix.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Looks like GME is here a whole thing is very outdated here...
The newer version is here at me: https://github.com/WohlSoft/AudioCodecs/tree/master/libgme

**Comment by Wohlstand** [comment]
Did a quick review of the whole stuff (except of GME side), so, it's only an adding of `(void)*` cast to all `memset` and `memcpy` calls in the code, must be fine!

**Comment by coelckers** [comment]
What alexey-lysiuk said. 
Some catch-all "warning-fix" commits genrally pose a huge problem, if something in there doesn't work out as expected. 
If there's issues, there first should be some attempt to actually fix the problem instead of using some generic cast that will forever hide the problem to the compiler.

In general this looks like typical GCC. Verbose warnings for perfectly legitimate code.

**Comment by Wohlstand** [comment]
In some cases there are even would be an error when you giving the pointer into "void*" target without of the cast. I had some of myself, but didn't remembering where, that was many places, and, one I remembering the case of feeding of `const xxx*` into `void*`, but something non-const also would lead to warning or even the error...

**Pull request closed without merging**
