### PR TITLE
Fixed: NetServerInfo was not being saved after the exit cleanup

### PR DESCRIPTION
**Pull request by drfrag666**

### CODE REVIEW

**Comment by coelckers** [comment]
What's the point of this? If you remove code I need a bit more of an explanation.

**Comment by drfrag666** [comment]
I forgot to link the thread, i've confirmed the bug.
https://forum.zdoom.org/viewtopic.php?f=2&t=70120#p1168037

**Comment by Cacodemon345** [comment]
Seems like a change just for the sake of it.

**Comment by drfrag666** [comment]
G_NewInit () now is also called from D_Cleanup() so netgame was always false in FGameConfigFile::ArchiveGameData.

**Comment by coelckers** [comment]
In that case you need to fix it differently. This will only cause problems. G_NewInit is supposed to reset the local engine state and that includes clearing the netgame flag.

**Comment by drfrag666** [comment]
I've tracked the code and i don't think this would cause problems, and i haven't found any in my quick test. netgame is initialized to false. I also thought about using an auxiliary variable to store the netgame status and restore it but then i checked the code and this was cleaner. G_NewInit is called at exit/restart/error and from G_DoNewGame. Better safe than sorry tough.

**Comment by drfrag666** [comment]
How about this in D_ErrorCleanup?
```
	aux = netgame;
	G_NewInit ();
	netgame = aux;
```

**Comment by drfrag666** [comment]
But actually it's "called" from G_DeferedInitNew and that happens in the menu, idclev, hxvisit, nextmap, nextsecret, map and recordmap, none of them work in MP.

**Pull request closed without merging**
