### PR TITLE
Fixed "Messages ON" not being printed

### PR DESCRIPTION
**Pull request by drfrag666**

### CODE REVIEW

**Review by madame-rachelle — CHANGES_REQUESTED** [review]
Please use an enum constant, do not use static numbers like this.

https://github.com/coelckers/gzdoom/blob/49b289d54e332c3f0118e8fb21d84f56114a153b/src/common/engine/printf.h#L51-L65

**Comment by drfrag666** [comment]
I've just restored the old code, that special value was never defined.

**Comment by madame-rachelle** [comment]
Okay, I did not know that. However, I will not accept this PR as-is. If you add in a new enum constant that would be fine by me and I'll accept it.

**Comment by drfrag666** [comment]
Which name would you suggest?

**Comment by madame-rachelle** [comment]
`PRINT_EVENWHENOFF` could work, I suppose, but I guess it's up to you, really, as long as it bears some meaning to what's happening.

Since you're using a power of two, should probably do a flag check as well, instead of checking for the static value - `(printlevel & PRINT_EVENWHENOFF)` as example

**Comment by coelckers** [comment]
I do not want this hack job back. Looks I forgot to move the show_messages = true line before the Printf.

**Comment by drfrag666** [comment]
I thought you wanted to fix this yourself but in the end i've opened https://github.com/coelckers/gzdoom/pull/1289

**Pull request closed without merging**
