### PR TITLE
 New savegame list order

### PR DESCRIPTION
**Pull request by drfrag666**
Sort savegames by reverse slot number (filename) but keeping autosaves at the top. Again some ancient code there. Discussed here:
https://forum.zdoom.org/viewtopic.php?f=18&t=58827#p1032460

### CODE REVIEW

**Comment by coelckers** [comment]
Slot number is a relatively meaningless metric here. It'd be better sorted by save date instead.

**Comment by drfrag666** [comment]
I beg to disagree. Actually in original Doom saves where sorted by slot number and once you've created a few slots you can save where you want and move saves around. Sure in ZDoom there are unlimited slots. At least IMHO it's better than the current implementation, i don't see many people giving their saves silly names to force a suitable alphabetical order, and works well.
 Sorting by date would need some carcinogenic code to convert between date formats.

**Comment by raa-eruanna** [comment]
I have to agree with Graf. Date is a much more sensible sorting method, it's more intuitive, and it makes it easier to recall "I was playing X or Y mod yesterday, so the saves from that mod should be pretty close to the top."

I don't think the slot number sorting is going to work for me, it's an unnecessary and arbitrary change.

And besides - I am one of those people who use alphabetical save names in order to force sorting. Of course I also wipe my saves every 2 months anyway because it gets too cluttered.

**Comment by drfrag666** [comment]
Okay may be the concept of dynamic virtual slots it's not intuitive, but new saves go at the top and when you delete some in the middle the new ones take its place and that's easy to get.
 I took autosaves into account and they always go to the top but not custom filenames. The system could be extended to sort custom names separately, it's in the legacy devbuild for now if you want to try it.
 I'll have to revert it for the release then.

**Comment by drfrag666** [comment]
I've uploaded a fix for the custom filenames thing (even emulating Randi coding style :D) but that doesn't mean i expect it to be accepted. It won't catch custom names in the 'mycoolsave' style tough.

**Pull request closed without merging**
