### PR TITLE
Add WorldOffset field

### PR DESCRIPTION
**Pull request by TehRealSalt**
Adjusts the thing's 3D position on render side. This allows for adjusting a thing's visual position without impacting their hitbox.

I wanted to use this as a hitstun effect for my TC, but I ended up rolling with a different effect because I couldn't do this. However I still think this can be a incredibly useful feature.

This is an example script that gives the Doom imp fireball a crazy spinning effect, ala Shotzo's bullets from Kirby: https://mega.nz/file/K2IVASBZ#58jjARYMOA_BEvfGHwKfFkW6U6U8xPB3NI4YXHyYTUw

### CODE REVIEW

**Comment by MajorCooke** [comment]
Does this cover interpolation as well?

**Comment by MekBoss** [comment]
Just leave it here
https://github.com/coelckers/gzdoom/pull/1043#pullrequestreview-365486668

**Comment by MajorCooke** [comment]
...What?

**Comment by alexey-lysiuk** [comment]
I guess, he meant my concern about increase of Actor class size.

**Pull request merged**
