### PR TITLE
Dedicated Russian SMALLFONT for Chex

### PR DESCRIPTION
**Pull request by Nemrtvi**
Preview

### CODE REVIEW

**Comment by Wohlstand** [comment]
**Off topic:** Idk who wrote this translation, but looks like main hero / player is a ... girl :girl: :fox_face: Or... because main hero is the "хлопина" and because of female grammatical gender of "хлопина" word, therefore main hero has a female grammatical gender :wink:, even the character who plays it is a man.

Very interesting and good idea to let appeals are addressed to player to be adapted for specified gender in languages are having grammatical gender :fox_face: :+1:

Yeah, in Russian (and in many other languages too) is the grammatical gender which affects verbs and genitives in dependence on a grammatical gender of related thing / person / creature.

**Comment by Nemrtvi** [comment]
That’s just a test. The text changes depending on the player’s chosen gender in the Player Setup menu.

**Comment by Wohlstand** [comment]
> That’s just a test. The text changes depending on the player’s chosen gender in the Player Setup menu.

Okay, didn't knew it's already exists, thanks for the note! :fox_face:

**Comment by Gaerzi** [comment]
If "Chex" stays in Latin script, won't it be read as "Snekh"?

**Comment by Nemrtvi** [comment]
The alternative would be to transliterate it as “Чекс,” which I don’t think is worthwhile.

**Pull request merged**
