### PR TITLE
Allow dynamic link FluidSynth 2 builds

### PR DESCRIPTION
**Pull request by vilhelmgray**

### CODE REVIEW

**Comment by vilhelmgray** [comment]
Ah, you're probably right -- I assumed it would work since FLUIDSYNTH2 was already defined for the Windows builds.

**Comment by vilhelmgray** [comment]
If FluidSynth version 2 is not yet supported, perhaps the [FluidSynth cmake](https://github.com/coelckers/gzdoom/blob/master/cmake/FindFluidSynth.cmake) should be updated to check for version 1 and fail if only version 2 is available.

**Comment by alexey-lysiuk** [comment]
If you have ability to test such changes properly, do it and make a PR then.

**Comment by vilhelmgray** [comment]
The OpenSUSE GZDoom package has a patch claiming to make the build work with fluidsynth 2.x: https://build.opensuse.org/package/view_file/games/gzdoom/fl2.patch?expand=1

Would that patch resolve this issue? The patch seems suspiciously small, so I'm not sure how it's working for them:

```
--- gzdoom-3.6.0.orig/src/sound/mididevices/music_fluidsynth_mididevice.cpp
+++ gzdoom-3.6.0/src/sound/mididevices/music_fluidsynth_mididevice.cpp
@@ -78,10 +78,13 @@ extern "C" unsigned __stdcall GetSystemD
 #define FLUID_CHORUS_DEFAULT_LEVEL 2.0f
 #define FLUID_CHORUS_DEFAULT_SPEED 0.3f
 #define FLUID_CHORUS_DEFAULT_DEPTH 8.0f
-#define FLUID_CHORUS_DEFAULT_TYPE FLUID_CHORUS_MOD_SINE
 
 #endif
 
+#ifndef FLUID_CHORUS_DEFAULT_TYPE
+#define FLUID_CHORUS_DEFAULT_TYPE FLUID_CHORUS_MOD_SINE
+#endif
```

**Comment by alexey-lysiuk** [comment]
I guess it resolves compilation errors. Have no idea about the rest. All GZDoom releases are shipped with FluidSynth 1.

**Comment by vilhelmgray** [comment]
It looks like OpenSUSE has been using this patch since 2018-10-17, so I'm impressed if they really are running FluidSynth 2 without issues. I'll contact the package maintainer and see what's going on -- perhaps they have some other additional patches in play -- and if they can assist in getting FluidSynth 2 support merged in here.

**Comment by vilhelmgray** [comment]
> I guess it resolves compilation errors. Have no idea about the rest. All GZDoom releases are shipped with FluidSynth 1.

I spoke with the openSUSE maintainer about the patch: it turns out there are no API changes between FluidSynth 1 and FluidSynth 2 that affects GZDoom code; the only difference is that we need to define `FLUID_CHORUS_DEFAULT_TYPE` if we're using FluidSynth 2.

I've force-pushed the patch to this pull request. It should resolve this issue, and since it's been tested for 8 months on openSUSE, it should be pretty stable now.

**Comment by alexey-lysiuk** [comment]
> I spoke with the openSUSE maintainer about the patch: it turns out there are no API changes between FluidSynth 1 and FluidSynth 2 that affects GZDoom code; the only difference is that we need to define `FLUID_CHORUS_DEFAULT_TYPE` if we're using FluidSynth 2.

This looks a bit fragile to me, and IIRC, similar change was proposed some time ago.
Anyway, I would to leave the final decision to Graf.

**Comment by vilhelmgray** [comment]
SDL2 has support for Fluidsynth. Would changing this code to use SDL2 in Fluidsynth mode be an acceptable solution?

**Comment by Wohlstand** [comment]
@vilhelmgray , SDL2 itself doesn't. SDL Mixer 2 does support of FluidSynth 1 only yet. SDL Mixer X (my fork of Mixer) does support FluidSynth if both versions and it can detect every FS version and link to it.

**Comment by vilhelmgray** [comment]
> @vilhelmgray , SDL2 itself doesn't. SDL Mixer 2 does support of FluidSynth 1 only yet. SDL Mixer X (my fork of Mixer) does support FluidSynth of both versions and it can detect every FS version and link to it.

I'm not very familiar with your fork. Is there a reason your fork is not merged back into SDL2 Mixer?

**Comment by Wohlstand** [comment]
@vilhelmgray , my fork (https://github.com/WohlSoft/SDL-Mixer-X) has new functionality which majorely changes some internal part. I have tried to ask to merging my features into original Mixer, however, my post has left with no reply many years.

**Comment by Gaerzi** [comment]
Fluidsynth will mostly be interesting when it reaches the next non-maintenance release (so, 2.1 or perhaps 3.0, not 2.0.x) as it'll be when it'll be able to load gm.dls as the default soundfont on Windows, though at the cost of an extra dependency on [libinstpatch](https://github.com/swami/libinstpatch).
https://github.com/FluidSynth/fluidsynth/commit/e49b5ed201ae42148f95e402c2623913e282efd3

**Comment by coelckers** [comment]
I'll leave the decision here to someone with a system where this is relevant. On Windows we have our own precompiled DLLs so this is of no consequence there.

**Pull request merged**
