### PR TITLE
Expose Print Levels to ZScript

### PR DESCRIPTION
**Pull request by AFADoomer**
Exposes print level functionality to ZScript.
- Split print flags into separate enumerator from print levels
- Updated PrintString function, notification buffer AddString function, and console buffer AddText function to take and handle print level and print flags as two separate variables
- Added new overload Printf and VPrintf functions that take print level and print flags as separate parameters
- Added Console.PrintString ZScript function that takes print level and flags as the first two parameters, then standard printf-style input after that
- Updated all instances in the code where a print flag was used to use the new syntax and flag enumerations.
- Updated a hard-coded flag value (PRINT_BOLD instead of 200 in console buffer)

Use:
`Console.PrintString(PRINT_HIGH, PRINTF_NOLOG, "Printing to screen and console without adding to log file");`

Basic demo file of the new ZScript call: [printlevel.zip](https://github.com/coelckers/gzdoom/files/6602034/printlevel.zip)

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
Maybe I’m missing something obvious, but why was print flags variable split on two?

**Comment by AFADoomer** [comment]
Because the first 5 values aren't actually flags, they are basically color selectors.  This is similar to the mixing of channels and flags that used to be present in the sound functions.

**Comment by alexey-lysiuk** [comment]
Honestly, 40 modified files are way too much for such mere feature. I would ignore unwanted values in new ZScript function.

**Comment by AFADoomer** [comment]
I assumed that the flags issue was the reason that this was not implemented already...  It would be really trivial to implement if no one cares about flags and message types being mixed together.

**Comment by marrub--** [comment]
I don't really see any issue with modifying so many files, save for if CI is lazy-compiling it, and even then. This refactoring would probably be done sooner or later anyhow, since GZDoom has been moving away from flags-inside-description (see: StartSound) for quite a bit.

**Comment by MajorCooke** [comment]
Is Printlevel akin to HUDMessage's ID parameter? If so, I very much would love this.

I'm going to merge this into QZDoom when I get the chance so people can test it.

**Comment by AFADoomer** [comment]
What do I need to do to make this a viable pull request?

**Comment by coelckers** [comment]
Old a it my be, this slipped under my radar for some reason. 
For what this provides it is far too noisy and changes things I do not want to see changed.
If you can resubmit this without changing half the code it will be accepted

**Pull request closed without merging**
