### PR TITLE
Destructible geometry - fixes, 3D floor support, ZScript support

### PR DESCRIPTION
**Pull request by jewalky**
This time tested :P

- Moved out remaining parts of logic to p_destructible (projectile hit functions)
- Fixed handling of radius damage to lines (as opposed to sectors)
- Added 3D floor support (uses health3d, health3dgroup in control sector)

Accompanying ACC PR https://github.com/rheit/acc/pull/75

### CODE REVIEW

**Comment by jewalky** [comment]
Please don't merge for now. Just found out that bouncing projectiles are handled incorrectly, would like to fix within this one. Sorry for that.

**Comment by jewalky** [comment]
Should be done on my side.

**Comment by jewalky** [comment]
Wasn't going to add ZScript yet, but I got reported a bug that FastProjectiles don't work correctly and looked into it... so it works now :p

Pretty much everything that I planned should work now.

About ZScript geometry damage event:
Aside from informational usage, this is also basically a way to limit damage to the map geometry if you know that certain parts are invulnerable to hitscan (for example).
The user receives all parameters from P_DamageSector/P_DamageLinedef and can write new damage to e.NewDamage, like following: https://pastebin.com/QvNN3Rky

This can also be used if you have some actor that does radius damage but you know that it isn't supposed to affect walls, and other stuff like that.

**Comment by coelckers** [comment]
Although I merged it I'd like to ask you to put a proper license header into the new p_destructible file.

**Comment by jewalky** [comment]
@coelckers can you just add the same header as here so that I don't need to create micro-PRs? https://github.com/coelckers/gzdoom/blob/master/src/events.cpp

**Pull request merged**
