### PR TITLE
Use the internal version of _stat() unconditionally since it's broken on Windows

### PR DESCRIPTION
**Pull request by drfrag666**

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
I doesn't make any sense to me. It was OK to workaround broken `_stat()` implementation for Windows XP compatible toolchain. Please note that Microsoft version didn't work at all, not in some very specific corner cases.
However, if you need to alter MSVC `_stat()` unconditionally, just make a new function. It would call `stat()` on POSIX, and the given code on Windows.

**Comment by drfrag666** [comment]
So i take that the given code is good? I know what it was for (before it was only broken on XP now it's always), but it's already in and to me it makes no difference changing that function or adding another one. Well, this way i make less changes.

**Comment by coelckers** [comment]
Let's repeat this: Can you prove that this fixes the INI overwrites?
If not, this won't get added. It looks to me like you are poking around in the dark, finding some random inconsistencies and then apply a "fix" in the vain hope that this is what causes the INI bug.

**Comment by alexey-lysiuk** [comment]
> me it makes no difference changing that function or adding another one.

The code is written to be read by humans, not machines. When I'm seeing a library function, I assume that code provided by corresponding system SDK will be used.
Overriding internal function is not what we want from generic `stat()` implementation. MS may change its name in the future, and the fix will fail silently.
It wasn't the best solution for Windows XP toolchain either, kinda quick and dirty fix for mostly deprecated platform.

> It looks to me like you are poking around in the dark, finding some random inconsistencies and then apply a "fix" in the vain hope that this is what causes the INI bug.

Exactly, nobody known what's going on there for sure. Similar approach would be to try to read config several times with some delay. It may or may not eliminate the problem in the exactly same way as other guessing fixes.

**Comment by drfrag666** [comment]
I thought i already had proved it, anyway this is the known problem of assuming a file doesn't exist just becouse you can't open it, the reason why you can't open it it's not important. There's an alternative as i said and that's printing a warning and not saving it on exit.
> Overriding internal function is not what we want from generic stat() implementation. MS may change its name in the future
Wouldn't we get an unused function warning then? But yes that makes sense, i could change it.

**Comment by Blzut3** [comment]
The XP toolchain fix didn't override any symbols.  _wstat64i32 was defined to something in CMake so essentially the windows header was "modified" to point to a custom symbol which was in one of our translation units.  I guess I could have just wrote the real function name in the cpp file and avoided this confusion.

If that function is needed as a more permanent thing then you should definitely call it directly with a new, clear name as @alexey-lysiuk suggested.  The method I used was entirely because I didn't want to change the code to work around a compiler bug that Microsoft claimed they were fixing for the XP toolchain (which ultimately never got released).

**Comment by alexey-lysiuk** [comment]
`_wstat64i32` is the name of MSVC library function. Our implementation was linked instead of non-functional theirs. IIRC, it had faulty wide characters conversion.

**Comment by Blzut3** [comment]
Ahh right [you changed it](https://github.com/coelckers/gzdoom/commit/0546c86716a3f603cbcfeccd67b9d541b098c263).  Honestly I still prefer the CMake macro method since overriding functions like that is wholly undefined vs just being highly ill advised.  But that's neither here nor there.

**Comment by alexey-lysiuk** [comment]
In general, the approach is quite bad indeed. Although, we don't care about it anymore as XP support was dropped few releases ago.

**Comment by drfrag666** [comment]
Thanks. I've changed the name of the function, it's not meant to be a permanent thing since they could fix it at a later point. Doing another custom function to work around another compiler bug would be overkill IMO and the function could be removed later.

**Comment by coelckers** [comment]
We do not need this as this was not addressing the issue it was supposed to fix.

**Pull request closed without merging**
