### PR TITLE
vid_setsize support for SDL backend

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
Fully tested, works as expected.

While I was at it, I also fixed a small issue with how window positions were being saved on dragging.

### CODE REVIEW

**Comment by coelckers** [comment]
I see you copied over all the hacks I had to add to the Windows backend to allow switching away from borderless fullscreen and properly restore the window size (which cannot be done in the same frame - a lot of the code is only there to trigger a second resize event.) Please check if they are really needed and remove them if not.

**Comment by raa-eruanna** [comment]
> I see you copied over all the hacks I had to add to the Windows backend to allow switching away from borderless fullscreen and properly restore the window size

I will take responsibility for this. She did so at my suggestion. So this is my failing, sorry.

**Comment by OrdinaryMagician** [comment]
OK here's a cleaner attempt at it.

**Comment by OrdinaryMagician** [comment]
Well, that's going to be a problem...

**Comment by raa-eruanna** [comment]
I'm sorry, but I am going to have to disagree with Alexey on this - so it's probably something we should go ahead and discuss.

There is a point where it makes sense to support older versions of the libraries, such as SDL2. But when it starts missing crucial features, and in my opinion this counts as one of them, you have to consider dropping support for older libraries. How old is the feature in question? If it's more than a year old - that's more than enough time for even some of the laggier distros to pick up on this. If not, I don't think it's unreasonable to expect people to drop in a newer version of SDL2 if their distro is too old.

This reminds me of the issues we had with LLVM back when we used it in QZDoom.

**Comment by alexey-lysiuk** [comment]
As you wish but please provide a workaround for Travis which still uses Ubuntu 14.04 😒

**Comment by raa-eruanna** [comment]
I'm not trying to say "let's do this" or "it must be this way" - I am only trying to provide something that I think should be discussed or considered. We could move this to the forum if that's more appropriate.

**Comment by alexey-lysiuk** [comment]
Actually I'm fine with any solution that won't break continuous integration.
By the way Ubuntu 16.04 uses SDL 2.0.4 and I wouldn't call it laggy distro.

**Comment by OrdinaryMagician** [comment]
I'd say it is considering the latest LTS release is 18.04.

**Comment by raa-eruanna** [comment]
Well in that case we definitely should consider customising our SDL2 installation, in my opinion, until the bigger distros start picking up on it. What we did with 3DGE was we simply grabbed the repo and added it to CMake. If it works, it works, and I'd prefer to make it as easy as possible, both for the CI and for future contributors. Once the bigger distros pick up on it, we simply remove our local copy and use the distro dependency again.

**Comment by coelckers** [comment]
What a mess! The main argument of Linux users to dynamically link everything possible is that "it can be updated at will at any time". And what do we get here? Quite the opposite in fact with the lowest common denominator dictating what can be used. I think it renders the entire concept ad absurdum.

**Comment by raa-eruanna** [comment]
I've tried both the default GCC compiler, and Clang 3.9, on Ubuntu 14.04, only to fail compile with both compilers.

Why are we supporting a distro so old?

I actually would like to request that we upgrade the distro requirement. Just because Ubuntu supports it, doesn't mean we have to. We can drop in a newer SDL2 for 16.04, if at least it compiles on that. It is codenamed "Xenial" - can we update Travis to use that, instead?

**Comment by alexey-lysiuk** [comment]
> It is codenamed "Xenial" - can we update Travis to use that, instead?

[No.](https://github.com/travis-ci/travis-ci/issues/5821)

**Comment by raa-eruanna** [comment]
In that case then, we'll probably have to `wget` and `dpkg -i` the correct SDL2 version - the latest from 16.04. I'm upgrading my VM now, I'm going to test a compile, later if/when I get it working I'll have to take advantage of the CI's on this repo to test it.

**Comment by alexey-lysiuk** [comment]
[16.04 still uses SDL 2.0.4](https://packages.ubuntu.com/xenial/libs/libsdl2-2.0-0)

**Comment by raa-eruanna** [comment]
Indeed, you are correct. I still really see no reason why we should hold back a feature just because of this, though. Maybe the function can be reimplemented?

**Comment by alexey-lysiuk** [comment]
Because there were no steps made to increase required version of SDL properly.

There should be a check for version in CMake script. We need a way to run GZDoom on distros with lower versions, both for stable releases and self-compiled builds. This will be used for Travis builds too.

**Comment by OrdinaryMagician** [comment]
I recall SDL 2.0.4 having some input bugs that were fixed in 2.0.5. I don't understand why they didn't update it.

**Comment by alexey-lysiuk** [comment]
The best solution for `SDL_GetWindowBordersSize()` will be to check its presence in SDL2 shared library and to use it if it's available. Various sound related libraries are loaded in this way.

**Comment by OrdinaryMagician** [comment]
I've never done this with SDL so I'll have to check the docs.

**Comment by OrdinaryMagician** [comment]
As suggested I've written something into OrdinaryMagician/gzdoom@f287e99f. It's ugly but it works.

If it looks fine to you I'll merge it for this PR.

**Comment by alexey-lysiuk** [comment]
I added a few comment to the commit with `SDL_GetWindowBordersSize()` loaded dynamically.

**Comment by OrdinaryMagician** [comment]
I honestly just want all this hell to end. I'm not exactly having a good day today between this and all the chaos at home. If all the changes look ok I'll rebase and force push into a single commit.

**Comment by alexey-lysiuk** [comment]
Looks good, do it.

**Comment by Blzut3** [comment]
FYI GZDoom has i_module.h for making library procedures optional.  Right now it'd arguably be more work to use it, but it does clean up boilerplate if there were to ever be more procs that should be optional.  The stuff in optwin32.h would provide an equivalent example of what is being done here.

**Comment by coelckers** [comment]
Line 424:

static_cast<SystemGLFrameBuffer *>(screen)->GetWindowBordersSize(top,left);

That entire casting voodoo is redundant. This is already inside the framebuffer class and should call the function without any explicit object. Lucky you that screen is a singleton, otherwise this may behave erratically. ;)

**Comment by alexey-lysiuk** [comment]
`screen` has `DFrameBuffer*` type but `GetWindowBordersSize()` requires `SystemGLFrameBuffer` and its called from free function `ProcessSDLWindowEvent()`.

**Pull request merged**
