### PR TITLE
Added +PUFFHITANGLE flag: puffs with this flag set will automatically…

### PR DESCRIPTION
**Pull request by nashmuhandes**
… face the angle of the thing or wall that it hits.

### CODE REVIEW

**Comment by nashmuhandes** [comment]
Use case: I want the puffs to shoot out smoke and debris in the exact angle of the wall, instead of them always shooting towards the player.

**Comment by nashmuhandes** [comment]
Additionally, I need some feedback:

Currently for floors and ceilings, the behavior is left unchanged. But I was thinking of making it so that when the puff hits the floor or ceiling with this flag set, the puff's angle, pitch and roll will be calculated off the normal of the plane it hit; in this case, the flag name needs to be changed.

Does anyone think this is a good idea? If it is, I will have to at least change the name of the flag to prevent future clashes, even if I don't actually code the floor/ceiling plane functionality yet.

**Comment by coelckers** [comment]
The idea is ok, but the implementation is not. This should be part of P_SpawnPuff, not the calling functions. There's 10 places where P_SpawnPuff gets called from C++ code and several more from script code, not counting any mods that may use the function.

**Comment by nashmuhandes** [comment]
Oh okay, sorry about that. Will clean it up ASAP.

**Comment by nashmuhandes** [comment]
Closing this for now as I don't have time for the next few days. Will re-open and request your review when I have code ready.

**Comment by nashmuhandes** [comment]
I have decided that doing this in the engine is too invasive...

You posted in the forum "Trace should be exported but its implementation requires some C-isms to fully support its features"... in that case, I will wait for scriptification of TraceResults so that modders can do this on their own.

**Pull request closed without merging**
