### PR TITLE
HUD model tweaks

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
What this does:
 - Look up HUD models by referencing the psprite's caller, rather than player's ReadyWeapon (this allows other owned inventory to use models without having to define their frames in every single weapon's MODELDEF).
 - Additionally allow Strife hands psprite to be a model (IsHUDModelForPlayerAvailable will check the PSP_STRIFEHANDS psprite first if it exists).

The only shortcoming from this at least is that if there's neither a PSP_STRIFEHANDS or PSP_WEAPON psprite active, models still won't be used. I'd have to look into that later, but I decided to submit this as-is because I couldn't get an example wad done in time and the branch is starting to grow stale.

### CODE REVIEW

**Comment by Chernoskill** [comment]
A very welcome addition/change to the HUD model functionality. I hope you can find a way to overcome the one issue you listed.

**Comment by coelckers** [comment]
Note: By mixing something useful and something unfinished in the same PR you virtually ensure it won't get merged. Please separate the two features. The burning hands thing does not look like it should be merged.

**Comment by OrdinaryMagician** [comment]
Oops, wait, I can fix this without having to make a new branch.

**Comment by OrdinaryMagician** [comment]
It may be a naive solution, but honestly, so is the way hud models and sprites are mutually exclusive. But fixing that is beyond the scope of this.

**Pull request merged**
