### PR TITLE
Add actor sprite shadows

### PR DESCRIPTION
**Pull request by nashmuhandes**

### CODE REVIEW

**Comment by coelckers** [comment]
That last commit makes this entire thing totally pointless. Please remove it again. It should be a user option that can be enabled in stock maps as well.

**Comment by nashmuhandes** [comment]
> That last commit makes this entire thing totally pointless. Please remove it again. It should be a user option that can be enabled in stock maps as well.

@coelckers Very well. And what about the CVar's default state being true? It means when a user starts up the engine, the engine will have sprite shadows drawn by default. I was motivated by your justification to ship GZDoom with certain settings (like texture filtering and transparency) - you say that you do this to make GZDoom visually stand out compared to other "classic" Doom engines. So I am applying the same logic here.

**Comment by coelckers** [comment]
Default state should be off and it should only add shadows to monsters, just like the Build games do.

**Comment by nashmuhandes** [comment]
@coelckers done

**Comment by Doom2fan** [comment]
The new changes make this practically useless for modders IMO. I think it'd be much, much better if it were reverted to the opt-in flag version, and there were a second CVar (or a third value for the existing CVar) that lets you choose whether it's enabled for monsters by default or not.

**Comment by MajorCooke** [comment]
I agree. In some games like Magic Carpet 2: The Netherworlds, projectiles casted shadows too. I'd like them enabled there as well.

**Comment by nashmuhandes** [comment]
> The new changes make this practically useless for modders IMO. I think it'd be much, much better if it were reverted to the opt-in flag version, and there were a second CVar (or a third value for the existing CVar) that lets you choose whether it's enabled for monsters by default or not.

Edit: Also, a related thought: as it currently is, this adds two new flags. The more flags we have, the more potential branch misses. Why not leave this as something the user can add themselves with a simple event handler? Automatically adding the flag to spawned monsters with one is completely trivial, and is easily done without causing desyncs or anything.
This would both be better for performance and maintenance purposes, and would be the most useful for modders.

Yes, that was exactly the motivation. Graf, the main attraction of the mod version was that mod authorss could simply embed the mod into their mods/TCs and have the shadows shown by default, without user intervention. It was also what prompted me to make that [commit](https://github.com/coelckers/gzdoom/pull/1197/commits/0069f4dbd50521aaaf5baf49898ac6ad7f61f049).

It is very effortless (and in fact I already made it; it's attached to the forum thread) to make an Event Handler-based mod that injects +CASTSPRITESHADOW to all the monsters and players.

This way, GZDoom by default will look vanilla (no shadows), but BOTH players and also modders have control of their preference.

I hope this can be reconsidered. I can do a force push to my branch to clean up the commit list.

**Comment by coelckers** [comment]
I suggested the monster limit for a simple reason. With all other objects that do not move, these shadows stand out as a fake hack. Judging from the Build games, this really only works if the shadow casting actor is moving.

**Comment by nashmuhandes** [comment]
Ok, understood.

Temporarily closing this PR until I figure out a solution where everyone can be happy.

(No hard feelings! I need more time to refine this feature anyway)

Thanks for your consideration. I'll be back. :)

**Pull request closed without merging**
