### PR TITLE
Add pixelation post-processing filter

### PR DESCRIPTION
**Pull request by bkoropoff**
This allows creating the blocky retro feel of the original 320x200 resolution despite resolutions this low no longer being supported.  Works well combined with nearest neighbor texture filtering, software lighting, palette tonemap, etc.

The shader does a depth buffer lookup to avoid resampling the player weapon sprite since it would produce ugly aliasing artifacts.

### CODE REVIEW

**Comment by coelckers** [comment]
I think the processing code needs to be moved out of the render backends. The PostProcessScene functions in both are virtually identical.

**Comment by madame-rachelle** [comment]
I really would like to say "No" to this. This ultimately is not needed, there are already mods that do this, and instead of wasting rendering time with pixels you never see, a scaling solution would be much more ideal; that has been planned for a while now.

**Comment by madame-rachelle** [comment]
To make matters worse, this is not flexible at all. It's only an on-off switch; you cannot customize it.

**Comment by dpjudas** [comment]
I don't understand why this shader needs access to the depth buffer. The player weapon sprite hasn't been drawn at the time this shader runs.

I'm also not sure the 2D drawer writes any depth values at all, making it impossible to detect this way. Even if it does, I'm not sure its a good idea to add such an expectation as it could change in the future.

**Comment by coelckers** [comment]
I concur with everything Rachael has said.

**Comment by madame-rachelle** [comment]
@ OP: It's nice that you're willing to contribute to the engine, and we do ultimately need a solution to the loss of 320x200. But this is the wrong solution to that problem. What you presented here already exists as a user mod, and there it should stay.

The biggest issue here is that this is a hacky work-around and ultimately will get in the way, in the long run, of further engine improvements. If you wish to implement Viewport scaling (which works independently of AND in tendem with the resolution scaler we already have), I am definitely open to that.

Ultimately - this problem needs a proper solution, not a 10-minute hack.

**Pull request closed without merging**
