### PR TITLE
- fixed: Change compiled exe version strings to match git repo number…

### PR DESCRIPTION
**Pull request by raa-eruanna**
…s. This is viewable in Windows by right-clicking on the executable and selecting "Properties".

### CODE REVIEW

**Comment by edward-san** [comment]
But including ```gitinfo.h``` inside ```version.h``` nullifies the attempt to avoid recompiling everything each time git commit is updated.

**Comment by coelckers** [comment]
How good then that this is only included by 30 source files (40, to be precise, but 11 are Posix only and 9 are Windows only.)

**Comment by alexey-lysiuk** [comment]
How about making this change Windows only? Or even better, make it configurable via preprocessor macro. Because from developer's perspective this is needed for Windows devbuilds only.
To be honest it's easier to check version in console than in file's properties.

**Comment by raa-eruanna** [comment]
Whatever works - but just so you know, external programs can query the .exe - example: https://github.com/raa-eruanna/GetProductVersion

This is still a work in progress - I was going to convert it from a console app to a window app, basically just searching for g/qzdoom.exe and popping up an input box with the complete git hash key pre-selected that can be put in bug reports later - as explained here - https://forum.zdoom.org/viewtopic.php?f=49&t=55309

I haven't gotten very far with it yet - but preserving this little change with the exe's Windows resource is important. There really should not be that many areas in the code that depend on the version.h - can the code fragments be isolated into their own file, possibly simply calling a function or pointer instead?

**Comment by coelckers** [comment]
The most frequently accessed item is the GAMENAME #define, this can easily be moved into a function.

**Pull request merged**
