### PR TITLE
PSPF_MIRROR Overlay Flag

### PR DESCRIPTION
**Pull request by MajorCooke**
- Flips the sprite's drawing and position over entirely on the X axis. Automatically implies PSPF_FLIP.

### CODE REVIEW

**Comment by coelckers** [comment]
What aboiut software rendering support?

**Comment by MajorCooke** [comment]
Rachael took care of it, unless you mean ZDoom's?

**Comment by MajorCooke** [comment]
https://forum.zdoom.org/viewtopic.php?f=59&t=56602#p1000669

**Comment by MajorCooke** [comment]
All done.

**Comment by MajorCooke** [comment]
Okay, really done for sure now. Includes polysoft rendering support too!

**Comment by MajorCooke** [comment]
It's ready. [Here's a test example.](https://forum.zdoom.org/viewtopic.php?f=59&t=56602#p1000169)

**Comment by raa-eruanna** [comment]
This has already been merged, but for some reason Github didn't pick up on it. (Probably because I did a rebase merge in the original tree so it doesn't recognize the commit hashes)

**Pull request closed without merging**
