### PR TITLE
Actor.LineTrace should be clearscope

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
This is most definitely an oversight from my part.

### CODE REVIEW

**Comment by coelckers** [comment]
This cannot be made 'clearscope' unless we know how a true C/S implementation can deal with it. Giving it that flag now and later finding out that it cannot be done would be a major disaster.

**Comment by OrdinaryMagician** [comment]
LineTracer.Trace can be used from ui scope fine, but Actor.LineTrace function can't?

**Comment by coelckers** [comment]
Can it? I see we may be getting in a bad situation once C/S becomes real. Let's hear from the people doing the C/S work first.

**Comment by OrdinaryMagician** [comment]
I mean, considering both of them just run a Trace without modifying anything in the world, it shouldn't be problematic, right?

**Pull request closed without merging**
