### PR TITLE
Add actor scale interpolation flag

### PR DESCRIPTION
**Pull request by MrRaveYard**
Implements interpolation for actor's scale. Forum posts: [mine](https://forum.zdoom.org/viewtopic.php?f=15&t=67609) and [old one](https://forum.zdoom.org/viewtopic.php?f=15&t=62894&hilit=interpolate+scale).

### CODE REVIEW

**Comment by MrRaveYard** [comment]
I see your point, but maybe some performance testing should be in order?

Personally on my PC, I'm able to tell the difference in Chillax's MAP39 after expanding `AActor` by more than 1024 bytes.
But my builds always run slower than the downloadable devbuilds.

Are there any plans regarding the bloating?

**Comment by coelckers** [comment]
I think in this case the increase in size can be countered by making both
the original scale and the PrevScale members FVectors instead of DVectors.
Here the added precision is not really needed, unlike for the position.

**Comment by MrRaveYard** [comment]
Great idea!
Should all related stuff in the renderers be changed to FVector too? Or is it okay for GetSpriteScale to keep returning DVector?

**Comment by coelckers** [comment]
The general rule of thumb should be that anything only used by the renderer can use single precision floats and the function may return such a thing. If it causes problems in some places, add a second access function. For the scale an FVector may even be faster because the renderer does not need to convert it from double to float.

**Comment by MrRaveYard** [comment]
I think I've hit a little problem. How does one export FVector2 to ZScript?

**Comment by MajorCooke** [comment]
Does it give an error if you convert all of them to float vectors?

**Comment by alexey-lysiuk** [comment]
Vectors of floats are not supported by VM. This requires either new instructions, or rework of existing vector support.

**Comment by MajorCooke** [comment]
Where can they be added at, curiously? I might try adding support for them.

**Comment by alexey-lysiuk** [comment]
https://github.com/coelckers/gzdoom/blob/10628e60cb3995fd693c4f9881e3cc6aa6ae027a/src/common/scripting/core/types.cpp#L326

**Comment by madame-rachelle** [comment]
This, unfortunately, needs to be updated to the latest master to resolve merge conflicts.

**Comment by MajorCooke** [comment]
You might not want to merge it at any rate if Graf has an issue with it.

> The general rule of thumb should be that anything only used by the renderer can use single precision floats and the function may return such a thing. If it causes problems in some places, add a second access function. For the scale an FVector may even be faster because the renderer does not need to convert it from double to float.

**Comment by madame-rachelle** [comment]
Okay. Well this is going to get closed to inactivity soon if the issue is not fixed and the rebase doesn't happen.

**Comment by MajorCooke** [comment]
So, I don't know if you've seen how ViewPos was implemented but since it's in, might give you an idea on what to do here. Could be wrong but worth a shot if you're still interested in this, Rave.

**Comment by coelckers** [comment]
> Okay. Well this is going to get closed to inactivity soon if the issue is not fixed and the rebase doesn't happen.

Yup, it took a while, but now it happens.

**Pull request closed without merging**
