### PR TITLE
Adds line specials

### PR DESCRIPTION
**Pull request by raa-eruanna**
Rockstar Raccoon's commit, cleaned up

### CODE REVIEW

**Comment by coelckers** [comment]
So far, so good. But this still needs a corresponding change for the ACC headers.

**Comment by RockstarRaccoon** [comment]
Thanks Rachael

**Comment by RockstarRaccoon** [comment]
Would the ACC change be required for this to be accepted?

**Comment by Cacodemon345** [comment]
`Would the ACC change be required for this to be accepted?`
Yes, maybe.

**Comment by RockstarRaccoon** [comment]
This makes me a sad raccoon.

**Comment by RockstarRaccoon** [comment]
I'm tempted to ask if this could be implemented in the meantime, just because it does give a mapper access to a line special, as will take a little while before most mappers have use of it.

**Comment by RockstarRaccoon** [comment]
https://github.com/rheit/acc/pull/73

**Comment by RockstarRaccoon** [comment]
This is the WAD file I've been using to test things.
https://drive.google.com/open?id=1AYGU8jC0gmQKn3auywae9Inrr14Bjsoz

**Pull request merged**
