### PR TITLE
Allow gamepad input in the background

### PR DESCRIPTION
**Pull request by drfrag666**
DInput and SDL. For fake slitscreen. It's harmless.
https://forum.zdoom.org/viewtopic.php?f=4&t=63710&start=15#p1110019

### CODE REVIEW

**Comment by drfrag666** [comment]
Really? I can't think of any. Why would anyone play another game with GZDoom open, active in background and unpaused?

**Comment by madame-rachelle** [comment]
> Really? I can't think of any. Why would anyone play another game with GZDoom open, active in background and unpaused?

Eh, just trust me here - it's really better to be safe than sorry. Don't pose the Doom community with an "impossible" challenge - someone will rise to the occasion and prove you wrong. :) I can see where you are going with this - but it is often dangerous to make such assumptions and you really should not start getting into the habit of doing so now. I've been burned a couple times with this, myself.

**Comment by coelckers** [comment]
This must be an option. I won't merge it if it forces background use.

**Comment by dpjudas** [comment]
Can only say I agree with Graf on this one. Standard input logic says it follows the active and focused window only. Joysticks shouldn't be an exception to this. Any exception to this should not be default as it is pretty nonstandard.

**Comment by drfrag666** [comment]
I've been looking into it and the keyboard also has DISCL_BACKGROUND but it doesn't work. Why?
 What about 'joy_background' for the CVAR?

**Comment by madame-rachelle** [comment]
`joy_background` works perfect for the CVAR. Also please don't enable background input for the keyboard for GZDoom - we have several people plenty paranoid enough already about the stats info.

**Comment by madame-rachelle** [comment]
Also, before I forget - please put the option in the menu, too, when you create the CVAR. The CVAR also needs to default to 'off'.

**Comment by drfrag666** [comment]
But shouldn't it be DISCL_FOREGROUND for the keyboard then?

**Comment by coelckers** [comment]
Since the keyboard device is unacquired when being moved to the background
it makes little to no difference.

**Comment by drfrag666** [comment]
Done but 'vid_activeinbackground' is not in the menu, 'i_soundinbackground' is.
Without that it won't work.

**Comment by Orangestar12** [comment]
Is there a reason this never got accepted?

**Pull request closed without merging**
