### PR TITLE
Service Expansion

### PR DESCRIPTION
**Pull request by MajorCooke**
Added GetString/Int/Double/Object(UI) functions to Service.

The purpose of these is to:
- Reduce string translations, which may slow the game if Service is used often enough
- Pass in pointers for storing or removing

In addition, this allows creation of custom functions via Service classes without needing them to be specifically defined.

### CODE REVIEW

**Comment by mmaulwurff** [comment]
Indeed, with these new functions Service will be more useful.

**Comment by drfrag666** [comment]
You could have force pushed to the old remote branch.

**Comment by MajorCooke** [comment]
This is cleaner and the old examples no longer apply.

**Review by alexey-lysiuk — COMMENTED** [review]
It look much better now.

The exact deprecation version is a bit unclear as it depends on the first release which will contain the change. I think, we can merge this PR as is, and adjust the version later.

**Comment by MajorCooke** [comment]
Can you do the honors of mergin?

**Comment by MajorCooke** [comment]
Thank you!

**Pull request merged**
