### PR TITLE
Optional override for SetSlot and ClearPlayerClasses

### PR DESCRIPTION
**Pull request by edthebat**
With this, a decade-long struggle can now be ended.

Corresponding edit to translation spreadsheet will be sent via PM

### CODE REVIEW

**Comment by MajorCooke** [comment]
@edthebat Can you fix the merge conflict? Then I'll be able to merge it into QZDoom.

**Comment by edthebat** [comment]
That wasn't there when I created this... I'll have to figure it out; that'll be my first time.

**Comment by coltongit** [comment]
@MajorCooke The PR's now been rebased. You can go ahead and merge into QZDoom

**Comment by edthebat** [comment]
Based on what GitHub told me, I resolved the conflict by undoing all the differences...

**Pull request closed without merging**
