### PR TITLE
Exported MD5 to ZScript

### PR DESCRIPTION
**Pull request by 3saster**
Exported the MD5 hashing algorithm to ZScript, so that mods don't need [to](https://github.com/3saster/fullscrn_huds/blob/af9374f337081c86d91b7ae200a56f37814c1eea/zscript/compat/compat_functions.zs#L61) [reimplement](https://github.com/Doom2fan/Se7evidas/blob/662df772dde522643176ff63343eeba9a5744e7a/PK3%20Source/S7ZScript/MD5.ZS) a hashing algorithm. It returns the MD5 of a string, since I imagine the main use case of this would be for hashing [data-lumps](https://github.com/3saster/fullscrn_huds/blob/af9374f337081c86d91b7ae200a56f37814c1eea/filter/game-doomchex/zscript/statusbars/main.zs#L100-L109), but if there is a better place/way this should be done, I can edit as necessary.

### CODE REVIEW

**Comment by Doom2fan** [comment]
IMO it'd be better to have a "MD5" class that allows you to add more stuff without having to construct a long string, with methods to add strings, ints, floats, etc.
e.g.:
```CSharp
    let hasher = MD5.CreateHasher ();
    hasher.AddString ("foo");
    hasher.AddString ("bar");
    hasher.AddFloat (13.37);
    hasher.AddInt (0xDEADBEEF);
    hasher.Finish ();
    string hash = hasher.GetHashString ();
```

**Comment by alexey-lysiuk** [comment]
> IMO it'd be better to have a "MD5" class that allows you to add more stuff without having to construct a long string, with methods to add strings, ints, floats, etc.

I'm not sure about floats. We should use own conversion routines, but this needs to be checked carefully.

**Comment by 3saster** [comment]
Huh, strange, I swear I couldn't get the characters to cast to uint8_t when I tried this when I wrote it a few weeks ago, I must have been doing something weird. Thanks for the AppendFormat tip btw, wasn't aware of that one.

> IMO it'd be better to have a "MD5" class that allows you to add more stuff without having to construct a long string, with methods to add strings, ints, floats, etc.

The MD5 algorithm operates on bytes, what exactly would it mean to add an integer/float then? Would the number be broken down into each byte and passed that way?

**Comment by alexey-lysiuk** [comment]
The interface is still an open question. Even with a single method, I don't really understand why it's static. Do you want to get a hash of a literal string?
I would like to hear other opinions on this.
Also, such functions are usually added to `vmthunks.cpp`, but that's not quite important for now.

**Comment by 3saster** [comment]
The method is static because I made it a member of the string class. In retrospect, perhaps that should be moved, either to another data type or to create a MD5 class. We'll see what Graf says on the interface.

> Do you want to get a hash of a literal string?

Technically yes, but it was done for a different reason. The static method [ReadLump](https://github.com/coelckers/gzdoom/blob/3b8ddb6b9bd9b0bb13c083108e9ae8c9ddd2949e/wadsrc/static/zscript/base.zs#L877) returns a "string", where each element is a byte of that lump (plus 0x00 appended at the end for some reason). This was the primary reason for adding this feature, although as I say that, perhaps it might make more sense in the form `GetLumpChecksum(int lump)` as a member of the `Wads` struct, but again, the interface is an open question atm. The result of using this function on the output of `ReadLump` is, after deleting the additional 0x00 character, what one would get if they calculated the MD5 of that lump itself.

**Comment by coelckers** [comment]
In this form it's really not useful. To actually make it useful it probably needs a bit of native support.

**Pull request closed without merging**
