### PR TITLE
Force STATIC for internal GZDoom libraries

### PR DESCRIPTION
**Pull request by vilhelmgray**
This makes sure the internal versions of these libraries bundled with
the GZDoom source code is used. This prevents the system from building
GZDoom for dynamic linking with incompatible external libraries (see
<https://forum.zdoom.org/viewtopic.php?f=2&t=64633>).

### CODE REVIEW

**Comment by coelckers** [comment]
Since I am building GZDoom with an external JPEG-turbo version built with vcpkg this somewhat gets into the way. I cannot bundle that library due to its complex compiler setup.

**Comment by alexey-lysiuk** [comment]
If you are building with external library, files from `jpeg` directory should not be processed at all.
There will be no corresponding project in the solution, and executable will be compiled with provided headers and linked with that external library directly.
Are you sure that addition of these STATICs has an influence on your setup?

**Comment by vilhelmgray** [comment]
> Since I am building GZDoom with an external JPEG-turbo version built with vcpkg this somewhat gets into the way. I cannot bundle that library due to its complex compiler setup.

I'm not familiar with vcpkg, but if this is an external JPEG library installed on the system then this patch should not affect it: external JPEG libraries will take preference over the internal jpeg directory.

This patch is only for the case where no external JPEG libraries are found on the system (i.e. `not JPEG_FOUND` or `FORCE_INTERNAL_JPEG`). In this case, we dive into the jpeg directory and start building the internal library.

> If you are building with external library, files from `jpeg` directory should not be processed at all.
> There will be no corresponding project in the solution, and executable will be compiled with provided headers and linked with that external library directly.

This is true. This patch does not affect external libraries; jpeg will still be dynamically linked to the system library in this case, as it should be.

> Are you sure that addition of these STATICs has an influence on your setup?

Ideally, if no external libraries are present on the system, then the internal libraries bundled with GZDoom will be used. However, in practice this may not end up happening as we desire.

The linkage method chosen by the `add_library` CMake command is ambiguous. On systems which select dynamic linking as the preferred method, these internal libraries will be built but not statically linked to the GZDoom executable. This results in the [error described in the bug report](https://forum.zdoom.org/viewtopic.php?f=2&t=64633):

    gzdoom: error while loading shared libraries: libSPIRV.so: cannot open shared object file: No such file or directory

This doesn't affect just SPIRV, but all internal libraries with `add_library` left ambiguous. Adding the `STATIC` specifier makes it explicit that these internal libraries should be linked to the executable if they are built, regardless of the preferences selected by the system.

**Comment by alexey-lysiuk** [comment]
@coelckers, could you please check this PR with your setup? Because the changes look reasonable to me. They should not affect any external libraries no matter static or dynamic they are.

**Comment by vilhelmgray** [comment]
I apologize for the commit description message -- I realize in retrospect that it was misleading in describing what this patch is actually doing. I can force-push a different description message that clarifies this patch does not affect current GZDoom external library support.

**Comment by alexey-lysiuk** [comment]
The comment is OK. I reopened it, so Graf can check these changes.

**Pull request merged**
