### PR TITLE
Restore pre-ZScript behaviour of A_BrainExplode and A_BrainScream.

### PR DESCRIPTION
**Pull request by Cacodemon345**
This should allow mods to replace BossBrain in DECORATE without having to mess with ZScript functions.

### CODE REVIEW

**Comment by coelckers** [comment]
Please do not make such invasive changes if you don't know what the stuff is supposed to do.

**Comment by Cacodemon345** [comment]
I wouldn't say it's invasive.

**Comment by coelckers** [comment]
It is, because you replaced the rocket with a BossBrain - which possesses entirely different properties.

**Comment by coelckers** [comment]
And that's precisely what your PR did NOT do!

**Comment by Cacodemon345** [comment]
This PR was also to fix a bug where anything that replaced BossBrain wouldn't spawn custom explosions.

**Pull request closed without merging**
