### PR TITLE
Don't interpolate zooming and panning in the automap

### PR DESCRIPTION
**Pull request by Calinou**
Follow-up to #1122.

Some people have found regressions with automap zooming which I can't reproduce (both on Windows and Linux).

This errs on the safe side by disabling interpolation for zooming and panning in the automap. Its logic will run on a per-tick basis again.

### CODE REVIEW

**Comment by coelckers** [comment]
How about fixing the problem? If you want to do real time input checks you have to scale your input by real time intervals between calls that actually match the 35 fps tic rate.

**Comment by Calinou** [comment]
@coelckers This is what was in place before. I added a delta time calculation and it worked as expected on my PC (both on a native Linux installation and a Windows VM). But for other people, it broke and I don't know why :slightly_frowning_face:

**Comment by drfrag666** [comment]
Panning is very smooth here, only zooming is very sharp and that's affected by the delta.

**Comment by drfrag666** [comment]
The delta is also used for panning, here zooming is not interpolated at all.
I've done this to at least prevent the wild zooming, no idea if it makes much sense.
```
diff --git a/src/am_map.cpp b/src/am_map.cpp
index 2227ac189..396978a3d 100644
--- a/src/am_map.cpp
+++ b/src/am_map.cpp
@@ -85,8 +85,8 @@ enum
 
 // C++ cannot do static const floats in a class, so these need to be global...
 static const double PLAYERRADIUS = 16.;	// player radius for automap checking
-static const double M_ZOOMIN = 2; // how much zoom-in per second
-static const double M_ZOOMOUT = 0.25; // how much zoom-out per second
+static const double M_ZOOMIN = (1.02);	// how much zoom-in per tic - goes to 2x in 1 second
+static const double M_ZOOMOUT = (1 / 1.02);	// how much zoom-out per tic - pulls out to 0.5x in 1 second
 
 static FTextureID marknums[AM_NUMMARKPOINTS]; // numbers used for marking by the automap
 bool automapactive = false;
@@ -1472,11 +1472,11 @@ void DAutomap::changeWindowScale (double delta)
 	}
 	else if (buttonMap.ButtonDown(Button_AM_ZoomIn))
 	{
-		mtof_zoommul = (1 + (M_ZOOMIN - 1) * delta);
+		mtof_zoommul = M_ZOOMIN * delta * TICRATE;
 	}
 	else if (buttonMap.ButtonDown(Button_AM_ZoomOut))
 	{
-		mtof_zoommul = (1 + (M_ZOOMOUT - 1) * delta);
+		mtof_zoommul = M_ZOOMOUT * delta * TICRATE;
 	}
 	else
 	{

```

**Comment by drfrag666** [comment]
Now i know what's going on. It works well when you use the keypad for zooming but zooming in is faster than zooming out. But with those defaults you can't use the mouse wheel, i always use the mouse wheel and that's never smooth. It's how it works.

**Comment by drfrag666** [comment]
To fix am_zoom you could use M_OLDZOOMIN and M_OLDZOOMOUT but now am_zoomin is faster than before. Before both zoom in and out speeds where the same.
The old code was:
```
static const double M_ZOOMIN = (1.02);	// how much zoom-in per tic - goes to 2x in 1 second
static const double M_ZOOMOUT = (1 / 1.02);	// how much zoom-out per tic - pulls out to 0.5x in 1 second
```
It went to 2x in one second. The new code says:
```
static const double M_ZOOMIN = 2; // how much zoom-in per second
static const double M_ZOOMOUT = 0.25; // how much zoom-out per second
```
But zoom in faster than before and much faster than zoom out even setting M_ZOOMOUT to 0.5. So clearly the speeds are wrong.

**Comment by drfrag666** [comment]
Setting M_ZOOMOUT to 0.2 zoom in and out speeds are pretty much the same here but now 2 doesn't mean 2x per second right? It doesn't mean anything i guess. Curiously a guy in the forum complained about zooming out being faster, for me changing am_emptyspacemargin has no effect.

**Comment by drfrag666** [comment]
For reference this is what i've done:
https://github.com/drfrag666/gzdoom/commit/3547320a0f3a38e15a85faeb18ff1e94f493ee0d
Wouldn't it be better to bind the mouse wheel to +am_zoomout and +am_zoomin instead?

**Comment by madame-rachelle** [comment]
Closed due to #1131

**Pull request closed without merging**
