### PR TITLE
Fixed FastProjectile not calling sector damage callback in XY movement

### PR DESCRIPTION
**Pull request by jewalky**
This weird actor is broken again... special thanks to Lewisk3 for having all his projectiles as fast :p
Also moved BlockingCeiling/BlockingFloor to P_CheckPosition so that it's more reliable on ZScript side.

### CODE REVIEW

**Comment by coelckers** [comment]
I cannot accept this. Please move the code back from P_CheckPosition to P_XYMovement., This absolutely must not be done in P_CheckPosition.

**Comment by jewalky** [comment]
Actually my motivation here was that BlockingMobj and BlockingLine are set from CheckPosition at some point, so I moved my code so that it's more like the existing one and so that modders don't need to write this if(z ...) expression in order to check if thing was blocked by any planes. 

If I make a native method in Actor like `CheckBlockingPlanes` and put it where it originally was, will it be ok?

**Comment by coelckers** [comment]
With this code it is very hard to say what is ok and what not. The main problem is that P_CheckPosition should not invoke any more actions than it already does. Calling any action special from there is highly problematic, and that's what the sector action checks essentially did. As long as the function merely checks a condition and stores the result in its FCheckPosition structure or in new variables of the checked actor, things should be fine.

**Comment by coelckers** [comment]
I'll have a closer look. This needs a better diff viewer to check...

**Comment by coelckers** [comment]
No, We've been busy with the JIT compiler recently so other stuff got shoved to the wayside,

**Pull request closed without merging**
