### PR TITLE
RandomSpawner Expansion

### PR DESCRIPTION
**Pull request by MajorCooke**
- If given the BOSS(DEATH) flags, RandomSpawners will remain as if the spawned had those flags.
- Now records the selected name from ChooseSpawn to Chosen variable, and the newly created actor to Spawned.
- Original actor and Chosen name can be retrieved with GetSpawn().
- Both are protected to help identify difference between the main spawned and the tracer in the event the latter is changed.
- BOSS flag will transfer to future RandomSpawners, but BOSSDEATH won't.

### CODE REVIEW

**Comment by coelckers** [comment]
This code transfers the spawner's BOSSDEATH flag to the spawned actor's BOSS flag. That is not correct.

**Comment by MajorCooke** [comment]
`boss`, not `bBoss`.

**Comment by MajorCooke** [comment]
To clarify, [here's the temporary value](https://github.com/coelckers/gzdoom/pull/1159/files#diff-fa010028474d0c8c4298a82e8aa58bb2R174) to get the actor to stick around.

The only transferring of flags it does is to future randomspawners, and that's [only the boss flag](https://github.com/coelckers/gzdoom/pull/1159/files#diff-fa010028474d0c8c4298a82e8aa58bb2R242).

**Comment by MajorCooke** [comment]
I see now, you meant A_BossDeath's call. Fixed.

**Comment by coelckers** [comment]
How can I review this? Essentially all I can do is see if it compiles and hope for the best. But that's not a good approach

**Comment by MajorCooke** [comment]
[Here's a test package.](https://drive.google.com/file/d/1ufiPEnyrpgzpVKamHbwMspYpc0a366Sa/view?usp=sharing)

Simply put, the idea behind this is to be able to track the actor spawned. Many mods rely upon RandomSpawner, so this will allow for maximum compatibility. What I'm trying to do is create a timer for items that are spawned and make it so they disappear after two minutes, but with random spawners being responsible for spawning these, this will prove to be a blocker. 

The mod I'm working on is designed for maximum compatibility with all other mods, and the monsters added drop default health/armor/ammo that's replaced often.

**Comment by MajorCooke** [comment]
I've been testing this thoroughly in QZDoom and everything's been working just fine.

**Comment by MajorCooke** [comment]
Another reason I've discovered this is important for me is because I'm trying to make a minimizer setting for items drops. Instead of allowing monsters to drop multiples of the same item, I want to combine them together but I cannot because the randomspawner disappears too quickly. But because the checking for the boss(death) flags occurs during PostBeginplay, it will allow me to inject a temporary flag so I can catch the spawn chain, check the item spawned, and then destroy the randomspawners.

**Comment by MajorCooke** [comment]
Can I get someone to review this?

**Pull request closed without merging**
