### PR TITLE
Allow selecting different timidity config files

### PR DESCRIPTION
**Pull request by kcat**

### CODE REVIEW

**Comment by kcat** [comment]
Rebased to apply with the menudef changes made some time ago. Any issues with this?

**Comment by alexey-lysiuk** [comment]
I think it's worth merging this PR before release and I gave it a try.

Unfortunately it doesn't work for me on macOS: `timidity` executable cannot locate configuration file while the path is correct and pretty short and doesn't contain spaces or any other special characters.
It maybe related to recent changes in `music_timiditypp_mididevice.cpp` file: command line parser for POSIX platforms was heavily modified. It might be just a coincidence though.

**Comment by rautamiekka** [comment]
^ If `timidity` ain't finding it's expected to, it should print far more debug lines, like what locations and files it's trying to use that actually don't exist, among anything else.

**Comment by kcat** [comment]
Hmm, I just updated GZDoom and this is also failing for me now too. It seems the quotations placed around the config file name are confusing it as they're now being passed to timidity as-is, and it's interpreting the quotations as part of the filename. Unfortunately it looks like the manual parsing it does now, rather than the ```wordexp``` call it used before, does not handle quotations and won't work anymore with config paths/filenames that contain spaces.

**Comment by rautamiekka** [comment]
^
>won't work anymore with config paths/filenames that contain spaces.

Does it work by using the backslash escape like `\ ` for space ? That wouldn't work on Window$ of course.

**Comment by kcat** [comment]
No, it only checks for spaces to separate parameters and doesn't have any handling for quote marks or escapes:
https://github.com/coelckers/gzdoom/blob/master/src/sound/mididevices/music_timiditypp_mididevice.cpp#L547

**Comment by kcat** [comment]
Seems it broke with commit 64e96c5f46f12745f5883fbafe580cdd34810e55. Does OpenBSD not support ```wordexp```? Both it and the ```glob``` call it was replaced with (later replaced with manual separation handling) are POSIX.1-2001 and did the job fine.

**Pull request closed without merging**
