### PR TITLE
Fix building with Vulkan enabled when system glslang is installed

### PR DESCRIPTION
**Pull request by Cacodemon345**
Fixes https://github.com/coelckers/gzdoom/issues/1382.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
I think, you are misunderstanding the problem.

If compiler (preprocessor) could not find header file, compilation fails with error.
So, all needed paths are added to the list of compiler’s search paths.
The real issue is with an order of these paths in the list.

Even if the given change fixes this particular issue, it just hides the actual problem.

**Comment by Cacodemon345** [comment]
The alternative would require patching the third-party files which I don't think would be OK. And the system include directories are implicitly added to the search list *after* any include directories specified on the command line on Linux compilers to my understanding.

**Comment by alexey-lysiuk** [comment]
Please read carefully what I said in the first comment. It’s not about patching anything, it’s about changing order of header search paths set for the main executable target.

**Comment by Cacodemon345** [comment]
Is this fine?

**Comment by alexey-lysiuk** [comment]
No, it seems like you do not understand the actual problem.

Once again, if include path is missing, compilation fails. Ask yourself, why does it work without your change?
Answer is obvious, it works because all header search paths are already in place.

There are two unrelated things that lead to an error described in #1382.
The first one is changed public interface of glslang. The second one is order of header search paths.
The problem is not specific to glslang. It just becomes noticeable due to incompatible APIs between the version we use and more recent version from Vulkan SDK.

Does this change address the mentioned issue? No, it doesn’t.
Accidentally, it may fix compilation failure in this particular case, but that’s all. The real cause of it is still there.

**Comment by Cacodemon345** [comment]
On second thought, this looks like updating glslang is the only solution.

**Pull request closed without merging**
