### PR TITLE
Event system - stage 1 (+2)

### PR DESCRIPTION
**Pull request by jewalky**
What's in:
- general framework (StaticEventHandler -> EventHandler, serialization, loading/unloading from mapinfo).
- RenderEventHandler. This was modified so that it only has before full render frame hook.
- WorldEventHandler. This has WorldLoaded, WorldUnloaded and WorldThingSpawned hooks.
I decided to not do WorldThingDestroyed/WorldThingDied hooks because it's trivial to attach an actor to spawned thing that will check it's state and act accordingly.
- Console.Printf (for logging outside of Actor, note that you don't have to add \n there)
- Fixes for vararg type resolving.

Static and dynamic handlers:
- Map and GameInfo handlers are required to inherit Static handlers.
- Map handlers are serialized to the savegame. WorldLoaded/Unloaded for non-static and map handlers are executed only once (like OPEN/UNLOADING acs scripts).
- WorldLoaded/Unloaded for GameInfo static handlers are executed anytime the level is loaded/unloaded. To tell apart level change from savegame loading, IsSaveGame can be used.
- Static handlers cannot be created from within the game (only by other Static handlers or from GameInfo by the engine). This is implemented by making StaticEventHandler.Create protected, so that if we later want to open a menu from the game, we can make a method that'll create it.

Function arguments in structures as opposed to virtual function arguments:
- it's WorldThingSpawned() instead of WorldThingSpawned(Actor ...) for forward compatibility.
This way we can add other members later and this won't break classes that don't use the new features.

### CODE REVIEW

**Comment by coelckers** [comment]
I can't see anything obviously wrong here. Just a small piece of advice. The VM already has a check to shortcut empty functions and not set up a complete stack frame for them, so there is no need to create native virtual base methods. You can easily keep them entirely on the script side and it will even be faster.

Of course it should be noted that the event for rendering is not netgame-safe, this needs to be noted in the docs later.

**Comment by jewalky** [comment]
Ok, edited.
Also not only the event for rendering is not netgame-safe, but also global handlers, because these can affect the playsim.

**Comment by ZzZombo** [comment]
Please, make `Printf` NOT to add a newline automatically. In case you want to write stuff consequentially, splitting large calls into several in an order.

**Comment by jewalky** [comment]
In case you want to write stuff consequentially, use a string and String.AppendFormat.
Either way that use-case is WAY less common than using a newline. In my logging system elsewhere I have log_format() that adds a newline and log_format2() that doesn't, and the latter is called like 3 times total.

**Comment by jewalky** [comment]
Just realized that my am dumb and that my approach made it completely impossible to handle both world events and other events. So to preserve forward compatibility and enable handling different things in single handler I'm now passing event data as an object.

Note that this object is actually static and passing it around won't result in anything good.
That's done so that I don't have to CreateNew/Destroy thousands of objects every frame once the event system is more rich in functionality than just 1-4 methods.

**Comment by jewalky** [comment]
Ok, so the world part is fully complete for now, pull pls if this is ok.

**Comment by jewalky** [comment]
Updated it so that you can attach handlers that will be preserved in savegames via GameInfo, for library-like stuff. These basically work the same way as regular map-section handlers, except that they will be implicitly added to every map that's loaded.

**Comment by jewalky** [comment]
So I added PlayerEntered, PlayerRespawned, PlayerDied, PlayerDisconnected.
Had some esoteric shit going on, for example our ENTER scripts were called for savegame loads (and no one noticed, because ACS is replaced from savegames...), and our RETURN scripts were called on an incomplete state, plus that REOPEN thing above.

**Comment by jewalky** [comment]
Also using "resurrect" should call Respawn ACS and ZScript hooks, because currently, when you use a script that sets player's TID to 0 on DEATH and restores on RESPAWN (so that only one thing has player's TID), it won't be restored in case of resurrect cheat. This caused esoteric issues for my MP-compatible map in the past.

**Comment by jewalky** [comment]
So currently there are two ways to receive input:
- InputProcess(InputEvent e): an interface to generic (non-GUI) events.
Any handler can receive these.
- UiProcess(UiEvent e): an interface to EV_GUI_Event.
Only handlers that have IsUiProcessor=true can receive these, and any present handler with this setting will set the global input mode to UI (much like open menus or console).

Also, got it about P_FreeLevelData and P_Shutdown, will doublecheck. Although I was pretty sure that my local handlers already get garbage collected on level change somehow.

**Comment by coelckers** [comment]
The issue is not regular level change but a game restart via the 'restart' CCMD. For that everything needs to be deleted separately from the level setup. You did delete your old handlers, but that code was in the same function that created the new ones. On a restart these would not get deleted and not get collected, remaining as zombie objects without a valid type, and these can cause crashes later.

**Comment by coelckers** [comment]
Sorry, I pressed the wrong button.

**Comment by jewalky** [comment]
Actually right now if I use restart in a map, I get this:
http://i.imgur.com/zTN2uRV.png

Even if no event handlers are registered that is.

**Comment by jewalky** [comment]
So the main frame is pretty much done, now all that's left is review, bugfixes and more customizable ways to draw textures to the screen, as currently the only possible way is like this: http://pastebin.com/UFcpJiN9

**Comment by alexey-lysiuk** [comment]
I can test changes using Cocoa back-end if you tell me exactly what I should check.

**Comment by jewalky** [comment]
It's not just testing, someone who's familiar with Cocoa (and can test it) should add querying of Shift/Alt/Ctrl keys being currently pressed and storing it in .data3 member of the event_t for EV_GUI_* events.
Example here: https://github.com/coelckers/gzdoom/blob/master/src/win32/i_input.cpp#L230

**Comment by alexey-lysiuk** [comment]
Modifier keys' state is assigned to `data3` in [Cocoa](https://github.com/coelckers/gzdoom/blob/master/src/posix/cocoa/i_input.mm#L389) and in [SDL](https://github.com/coelckers/gzdoom/blob/master/src/posix/sdl/i_input.cpp#L383-L385) back-ends.
Is it something wrong with them?

**Comment by jewalky** [comment]
Actually it's ok then, I must've been blind when I looked at it.

**Comment by jewalky** [comment]
Damn. Rechecked. Correction: it isn't set for MOUSE events in SDL and Cocoa, while Win32 does that.

**Comment by alexey-lysiuk** [comment]
Could you please give me line numbers from Win32 back-end?

**Comment by jewalky** [comment]
https://github.com/coelckers/gzdoom/blob/master/src/win32/i_input.cpp#L338

**Comment by alexey-lysiuk** [comment]
OK, I will add handling of modifiers keys to Cocoa back-end.
Honestly I have no idea what the point to check those keys for mouse clicks and even mouse moves in menu but I'll do it just for the sake of consistency.

**Comment by jewalky** [comment]
>Honestly I have no idea what the point to check those keys for mouse clicks and even mouse moves in menu but I'll do it just for the sake of consistency.

Ctrl+mwheel for scaling something.

**Comment by alexey-lysiuk** [comment]
Modifiers for wheel events are handled by all back-ends, moves and clicks are by Windows only.

**Comment by jewalky** [comment]
Are you sure? Because I'm looking at SDL_MOUSEWHEEL and all it does is setting subtype to WheelUp/WheelDown.

**Comment by alexey-lysiuk** [comment]
My bad, SDL one handles modifiers for keyboard events only.

**Comment by jewalky** [comment]
Apparently on Linux Console.Printf outputs complete garbage http://i.imgur.com/mGKnHoR.png
Not sure why, that screenshot is by another person and I'm still building new GCC on my CentOS VM, because existing 4.x is not capable of compiling our bleeding edge C++14 stuff.

**Comment by jewalky** [comment]
Ok, so I tested it with SDL, seems to work properly now.

**Comment by alexey-lysiuk** [comment]
Support of modifier keys for mouse events in Cocoa backend added in c6e42d6.
Probably the same thing for SDL should be submitted separately from this big PR.

**Comment by jewalky** [comment]
Probably, but only if requested by Graf. I already have some unrelated things here and don't want to juggle branches and have merge hell because same changes in GZDoom and thereisnospoon.
It isn't really needed outside of this PR anyway, because GZDoom itself doesn't rely on knowing modifier keys for mouse events, it's only needed for consistency between platforms for mods.

**Comment by jewalky** [comment]
https://forum.zdoom.org/viewtopic.php?p=976011#p976011
Is it ok to allow editing ViewPos/angles in RenderFrame handler?

Also, yesterday I realized that there should be a way to execute manual events from the console to be able to bind completely custom actions. Do I just copy puke implementation?

**Comment by coelckers** [comment]
No. The ViewPos stuff is strictly off limits and needs to be considered read-only. Allowing changes here would pretty much cut the renderer off from internal refactoring. The RenderFrame handler should not alter any data that may be used by the renderer. R_SetupFrame is doing some complex stuff and selectively changing some of it may break in unforeseen ways later.

**Comment by coelckers** [comment]
About console events, it depends on what these events are supposed to do. Local UI events should not be run through the network protocol ever, but any event that's supposed to work on game state must do that.

**Comment by jewalky** [comment]
Split into two consolecommands.
- event <name> [arg1 [arg2 [arg3]]] for UI stuff, this doesn't try to guess the player or anything, and works outside of level.
- netevent <name> [arg1 [arg2 [arg3]]] for playsim stuff, this goes through the same pipeline as a regular puke command.

**Comment by jewalky** [comment]
I was looking at puke implementation, do we really allow running puke when playing back a demo and in title level? Why?

**Comment by MajorCooke** [comment]
Testing things like special effects and what not.

**Comment by coelckers** [comment]
"I was looking at puke implementation, and do we really allow running puke when playing back a demo and in title level? Why? "

The Puke command is sent over the network, so that a recorded demo can also record the events from running the script in a synchronized fashion and to allow running it on all systems in a multiplayer game. Were it executed asynchonously it'd only be on the local computer and the event of starting the script would not be recorded in the demo.

**Comment by jewalky** [comment]
I meant that in CCMD(puke), it will try to write net command disregarding the current game state of the source client.

**Comment by coelckers** [comment]
No idea. I never checked that part.

**Comment by coelckers** [comment]
This is currently completely missing any garbage collection handling and will inevitably crash on you some time throughout the game. Is this otherwise finished?

**Comment by jewalky** [comment]
Otherwise — yes, but you will need to explain to me how exactly do I handle garbage collection if you want me to finish that part :)

**Comment by coelckers** [comment]
There's actually two parts:

First, all object pointer variables in your objects need to be declared as pointers, including 'prev' and 'next' for linked lists and
second, any time you write to such a variable, or a persistent global one, you need to call GC::WriteBarrier. 

And if there's global variables that can't be reached by the GC on its own, you have to manually GC::Mark on them when the GC starts.

**Comment by jewalky** [comment]
>First, all object pointer variables in your objects need to be declared as pointers, including 'prev' and 'next' for linked lists

Are you sure? I unlink the object and set references to zero myself, in OnDestroy.
Unexpected nulling of these pointers won't end up well.

**Comment by coelckers** [comment]
Yes, those, too. If you don't the garbage collector can never reach them and will consider everything they point to unused and may delete it, if it isn't linked to anything else.

About how it all works, I also only know half of it. Black magic? That seems to be a favorite ingredient with Randi's code... :D

**Comment by coelckers** [comment]
I just had a closer look, but here's the thing I do not like about the whole setup:

It looks to me that the various event types are merely being used as short lived containers for the parameters being passed. Why are you doing it in such a fashion instead of just passing all the necessary info as direct function parameters? The scripts cannot even store these events because they don't get serialized. 

As it stands, I am going to refactor all those callbacks to use direct parameters instead, unless you can give a good reason for all these objects.

**Comment by jewalky** [comment]
Forward compatibility. We can add more information later this way.
Also, give me a good reason to store an event structure.

**Comment by MajorCooke** [comment]
9 arguments... Reminds me of A_QuakeEx.

**Comment by coelckers** [comment]
In that case it may make more sense using structs, they have far less overhead and you don't run into the problem that the script may try to store the entire object, which is something that needs to be considered when doing so - but then it needs to be serialized and properly garbage collected.

But what 9 parameters? It seems like most event only use a small fraction of what the event type they receive can contain. If I haven't miscounted the current maximum is 5.

**Comment by jewalky** [comment]
Structs would be best, it's just that I had completely no idea how to declare structs, I tried looking at sector_t for example, but it seems you are just adding the fields without struct type declaration anywhere.

For the argument count: WorldThingDamaged uses Thing, Inflictor, Damage, DamageSource, DamageType, DamageFlags, and DamageAngle. This is 7.
Also, UiEvent has 8 members, and if you want to reduce the used per method, you'd have to split UiProcess into UiKeyDown, UiKeyUp, etc... I'd say too much text to write instead of simple switch() to handle based on the event type.

**Comment by coelckers** [comment]
What about sector_t? It got a native struct definition in r_defs.h, the exported members in p_sector.cpp and a struct Sector definition in mapdata.txt

**Comment by jewalky** [comment]
How does it link sector_t to Sector? Does it just expect it to be that without any type checking and will utterly fail if you try to pass something that's not a Sector to something that expects a Sector? (on native side that is)

Also, what happens to object pointers in structs? Example, if we copy a struct around and it points to an actor.

**Comment by jewalky** [comment]
As for the example of adding new data, I'm currently thinking of adding an event member for WorldLoaded that'd specify whether we started a new game or travelled from previous map.
For things like this: https://forum.zdoom.org/viewtopic.php?p=976589#p976589
If I didn't have event classes and this system was already in, I'd have to create two virtual methods, one with support of this feature and one without. And they would have to be called differently because there is no method overloading.

**Comment by jewalky** [comment]
Actually you can already detect new map by checking level.totaltime against level.time (or 0), so that's not needed. I'd really appreciate some information on structs though.

**Comment by nashmuhandes** [comment]
@jewalky can your Event system do "ActorUsed" event? Pressing +use in front of the thing to run a custom function?

Graf Zahl answered [https://forum.zdoom.org/viewtopic.php?f=3&t=55073&p=975573&hilit=usespecial#p975573] that currently the only way is +USESPECIAL but I don't want to assign specials on Things and in fact I'm trying to avoid ACS altogether (no more intermediary steps!)

**Comment by jewalky** [comment]
It's a non-global playsim event. It should be a virtual method on Actor.

**Comment by nashmuhandes** [comment]
@jewalky Hmmm I don't see anything in P_TalkFacing that handles SwitchableDecorations; seems like pressing +use (in P_PlayerThink) only handles using using lines and Actors with Conversation nodes. Ok thanks, I will put it on the Mantis

**Comment by jewalky** [comment]
@nashmuhandes I have no idea what you see or don't, but SwitchableDecoration is supposed to switch states when you press use on it.

**Comment by coelckers** [comment]
No, it isn't. It's supposed to switch when it gets activated. You need to give it a tid and a special to do that.

**Comment by MajorCooke** [comment]
Unless you override the (de)activate functions, perhaps?

**Pull request merged**
