### PR TITLE
Add per-tier sidedef light levels

### PR DESCRIPTION
**Pull request by mykola-ambar**
This PR adds support for independent per-tier light levels on sidedefs, allowing for different top, middle, and bottom light levels on a single sidedef. This can be done by setting `light_{top/mid/bottom}` and `lightabsolute_{top/mid/bottom}` UDMF fields. 
If both global (`light`/`lightabsolute` ) and per-tier fields are present on a sidedef, the global light level is applied first, and per-tier light levels are applied afterwards.

Here's a small demonstration map, look for linedefs that contain comments:
[per-tier-lightlevels.zip](https://github.com/coelckers/gzdoom/files/6048073/per-tier-lightlevels.zip)

### CODE REVIEW

**Review by coelckers — COMMENTED** [review]
I am not sure that GetLightLevel is correct, it uses TierLights even when the flag is off.
Also, please use parentheses to declare evaluation priority, this code emits warnings on certain compilers.

**Comment by coelckers** [comment]
This addresses only half of what I pointed out. What's with the TierLights being used even without the flag?

**Comment by mykola-ambar** [comment]
The flag makes the tier light absolute. Without it, the tier light level is calculated relative to the sidedef light level (for example, a sidedef with light level of 128 and mid-tier light level of 64 should have a mid-tier light level of 192 without the flag). Since `TierLights` contains 0s by default, adding it does nothing, as should be the case if tier lights are unspecified.

**Comment by mykola-ambar** [comment]
Found a 3d floor rendering issue in my code on hardware renderer, should be fixed now (some 3d floor lines would become pitch black).

**Pull request merged**
