### PR TITLE
Add option to invert mouse x

### PR DESCRIPTION
**Pull request by arookas**
Adds an option to invert yaw/turn alongside the existing invert-pitch setting.

This requires edits to LANGUAGE:
- Add `$MOUSEMNU_INVERTMOUSEX` as "Invert Mouse X"
- Change `$MOUSEMNU_INVERTMOUSE` to "Invert Mouse Y"

### CODE REVIEW

**Comment by coelckers** [comment]
While technically trivial, what's the reason? Do you play with inverted x-axis for some reason?

**Comment by arookas** [comment]
Inverted x and y, yes. Right now, the only way to get both axes inverted is to manually set the mouse sensitivity to a negative value via the console, as the menu slider clamps.

I see this being useful also for third-person gameplay mods, where invert x is more common (e.g. Risk of Rain 2, Uncharted).

**Comment by madame-rachelle** [comment]
This technically can be merged, imo, safely. The only thing stopping me from doing so is not knowing if this would be considered a bad idea. (In my opinion, I don't think it is)

**Comment by Doom2fan** [comment]
This looks fine to me. I'll be merging it later if there are no objections.

**Comment by arookas** [comment]
@Doom2fan @coelckers Cool, I tried out the latest and the option is in there and is working great; it's just missing the LANGUAGE update.

**Pull request merged**
