### PR TITLE
Moved FConfigFile over to FileReader/FileWriter

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
So it can take from other sources

### CODE REVIEW

**Comment by ZippeyKeys12** [comment]
Should I make the FileWriter a value object as well?

**Comment by coelckers** [comment]
No. That class is different. It may need some refactoring later, though.

**Comment by ZippeyKeys12** [comment]
Is there anything else, you'd like me to change?

**Comment by ZippeyKeys12** [comment]
Done

**Pull request merged**
