### PR TITLE
AActor::Tick separation to dedicated functions

### PR DESCRIPTION
**Pull request by MekBoss**
Set of commits that move logic, like movement, state progression, etc., from AActor::Tick into dedicated function. It also exposes new functions to zscript, to allow easy overriding of a tick on zscript side.

On additional note, it also slightly improve performance of a Gzdoom, comparing to a current (250fac5) master version. Tested CPU consumption on release version, on okuplok map. Okuplok are here
http://www.mediafire.com/file/dy98536fxa79az7/oku2v31.wad/file

Update: look like my Visual Studio trying to Volkswagen me, because now, after I tried to make performance report screenshots, my version works worse than master.

### CODE REVIEW

**Comment by coelckers** [comment]
This really makes little sense without allowing virtual overrides. But it's something I deliberately did not do in the past due to performance concerns.

**Comment by OrdinaryMagician** [comment]
I'm looking at this and I do appreciate putting carrying sector handling into a separate function that doesn't modify velocity directly. That is especially useful for mods that alter player movement physics, and would be very welcome.

**Comment by MekBoss** [comment]
I cant find a way to trigger "if (effects & FX_VISIBILITYPULSE)" condition
https://github.com/coelckers/gzdoom/blob/e02690af58ec91af8bc54bec4a8d5085c6296af4/src/playsim/p_mobj.cpp#L3718
Is this is a dead code and I can delete it?

**Comment by Doom2fan** [comment]
> 
> 
> I cant find a way to trigger "if (effects & FX_VISIBILITYPULSE)" condition
> 
> https://github.com/coelckers/gzdoom/blob/e02690af58ec91af8bc54bec4a8d5085c6296af4/src/playsim/p_mobj.cpp#L3718
> 
> Is this is a dead code and I can delete it?

No. [This is an actor flag](https://zdoom.org/wiki/Actor_flags#VISIBILITYPULSE).
This indicates to me you don't really know what you're getting into here and shouldn't be attempting something like this. There's a lot of stuff that can go wrong here, from harming performance to breaking features, and this needs to be done _extremely_ carefully, by someone who has in-depth knowledge of the engine and its features.

**Pull request closed without merging**
