### PR TITLE
Modern CMake overhaul for GZDoom + ZMusic submodule

### PR DESCRIPTION
**Pull request by Blzut3**
I've been picking away at this for awhile so I wouldn't be too surprised if I forgot something.  As with ZMusic, sorry about the completely unreadable diff, but such is the nature of this effort.

This was a lot harder modernize than ZMusic since there was a ton of legacy stuff and not really feasible to just throw it out and start fresh, but I think I got something I'm mostly happy with.  Of course the big changes are CMakeLists.txt and src/CMakeLists.txt.

For the root CMakeLists.txt, the goal was to hoist as much as possible into modules and move target setup elsewhere.  To that end we now have a CMakeLists.txt specifically for vendored libraries, a few new files in cmake/, and the rest got filtered down into src/.

In src/ I tried to minimize the amount of branching, or perhaps more accurately branching and then doing the same branch hundreds of lines later in the same file.  Modern CMake lets us also avoid having to add to variables since we can just append stuff to targets.  I've created sections marked with BEGIN and END (my text editor can fold on these, although not sure if there's a more compatible syntax to get folding) and that folding has been useful to me so I would say the sorting has been a success.

I'm not too happy about the source list variables still hanging around they way they are, but I really couldn't think of a better way to handle the situation.  But what I was able to do is mostly move the logic bits below the entire source listing.  (Only thing I kept in line was the platform selection since I couldn't figure out a nice clean way to defer that to later.)  There were previously some conditionally compiled sources that weren't always added to the Visual Studio project, and that's fixed now.

Of course ZMusic is now a submodule.  One is free to use a system copy of ZMusic (or otherwise import a separately compiled ZMusic), and it's not required to have the submodule cloned to do that.  I'm not sure if we still want to keep the prebuilt lib files here now that using the submodule is an option, but those are still supported as well.  The condition upon which they are used may need some tweaking though depending on what we want to do.

I put some initial CPack support in which can generate deb packages and on Windows produce a zip archive.  The deb package is mostly where it needs to be, but there's more to be done here.  Just no need to hold off the rest of this for that to be done.

### CODE REVIEW

**Comment by coelckers** [comment]
Please remove the submodule. 
The one for widepix has been nothing but trouble, I won't deal with them anymore.
widepix will also be properly integrated once Nash's work is done.

**Comment by Blzut3** [comment]
Does it make no difference that this submodule is optional?  My understanding is your concerns are about stuff like bisecting acting weird, but the way I implemented this nothing would stop you from bisecting a clone that doesn't have the submodule.

The reason I ask is one of the problems I was trying to solve is putting a pointer to the desired ZMusic version in this repo for building the dev builds.  This can probably be solved another way, but it seems like the submodule being optional should be a decent compromise?

**Comment by Blzut3** [comment]
Was trying to think about what other projects do to solve this problem and GCC's contrib/download_prerequisites comes to mind.  Basically I could write a shell script (compatible with git-bash on Windows) which users can choose to use to automatically pull down ZMusic for in-tree compilation if they so choose.  This would have the advantage of when you download the archive of the source code without git the pull down script would still be available.  However, there is the reality that such script is just duplicating the functionality of git submodules without any of the git integration.  Something you'd probably see as a positive given your position on the feature.

Ultimately up to you what route to go down, or we can discuss this further.  There are two problems I'm trying to solve with a semi-automated solution.  First is that users find building GZDoom frustrating due to the ZMusic dependency not being vendored (numerous forum posts and an issue ticket here back this claim up).  Second is what I mentioned int he last post in that I would like for this repo to suggest what ZMusic version to build for any given version of GZDoom.  ZMusic is ABI stable, but there are still reasons such as the auto builds where this information can be useful.

There is a third problem that allowing ZMusic to optionally be built in tree solves and that is it allows CPack to easily build the deb packages.  But in-tree building can be supported with manually dropping the ZMusic source tree in the right location.

Again to reiterate, no matter what route is taken, the script is written to allow the libraries/zmusic directory to be empty and function just fine with an imported build as done today.

**Comment by alexey-lysiuk** [comment]
I was against usage of submodules initially, and didn’t change my mind since then.

Regarding ZMusic dependency, it’s not our problem that someone cannot build GZDoom/Raze because of it.
If they have no idea what they are doing, just download a binary package.
Willingness to build from source code is nice, but it requires some knowledge. It’s not a blind shell commands copy-paste job.

On the other hand, if ZMusic wasn’t found, it’s OK to grab its sources to build in-tree.
However, this should be done in pure CMake, I think.

**Comment by Blzut3** [comment]
If it's not our job to make compiling easy, then why do we vendor any of the libraries?

Doing the fetch in CMake is certainly a possibility.  I'm not a huge fan of doing non-build stuff in CMake since the language is very not designed for that, but it can be done.

**Comment by alexey-lysiuk** [comment]
> If it's not our job to make compiling easy, then why do we vendor any of the libraries?

Our job is to make things work. If we can make it easy without too much hassle, I'm fine with it. Otherwise, we may end up with a custom app that offers a single 'Do everything, and make me happy' button.

> Doing the fetch in CMake is certainly a possibility. I'm not a huge fan of doing non-build stuff in CMake since the language is very not designed for that, but it can be done.

I meant something like [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html) module.

**Comment by coelckers** [comment]
GZDoom can be built on Windows without any intervention or additional setup. It's only when running the compiled EXE that the .dll's have to be grabbed from a binary package. That's the case with or without ZMusic.

What I found far more ironic is how the process broke down for some Linux users when they had to think a little bit out of the box with ZMusic. The number and the kind of complaints this received was a little bit ridiculous.
I agree with @alexey-lysiuk  that it's not the developer's task to spoon-feed the perfect solution. The goal should be to allow configuring the project with reasonable effort. If that is too much to ask, don't self build, plain and simple.

But submodules are not the solution. The problems they cause are often a lot bigger than some minor inconvenience in the build process.

**Comment by coelckers** [comment]
Submodules are not a solution. I had to find out the hard way that they are far too broken to be used in any project that needs active maintenance. Apparently Rachael came to the same conclusion, judging by her post in the forum. So if you can provide something that works without submodules, fine. But if your solution requires submodules to work, count me out.

**Comment by Blzut3** [comment]
All right, I think I should have time on Sunday to put something together.

**Comment by alexey-lysiuk** [comment]
I encountered a pretty specific issue with this change. As it requires fairly long explanation, and it's tightly coupled with ZMusic, I put it in a separate report coelckers/ZMusic#28.

**Comment by Blzut3** [comment]
Updated to use FetchContent.  Although I'm not sure I'm 100% satisfied with the way the automatic fetching (disabled by default on MSVC) is setup.  Specifically in the case of alexey-lysiuk's ticket there the new way completely masks the error since CMake doesn't differentiate between find_package not finding the config and the config failing to find dependencies.  There's likely some better logic I can do here, but I think I need to sleep on it.

Of course would love to hear any other feedback in the mean time.

**Comment by alexey-lysiuk** [comment]
With non-MSVC configuration, the new version always fetches source code to build ZMusic even if headers and library are found at prefix path. Is it supposed to work this way? The initial version didn't have this "feature".

**Comment by madame-rachelle** [comment]
I am actually quite eager for this, as I would like to build .deb packages for non-x86 platforms (including the Pi) and have found hand-building those things to be quite a pain in the butt, especially after the ZMusic split, which is why I haven't provided Pi packages or Linux packages period since that one person complained that my binary wouldn't work for them with Raze.

This would even allow for the possibility of doing dev build nightlies for, at the very least, Linux, and our Linux user base is growing so I think it would be nice to have something for them when they want to try out new features between releases.

**Comment by coelckers** [comment]
I can't sift though this wall of changes. It may make sense to resubmit in smaller portions that are easier to check. In its current state I won't merge it for fear of breaking stuff.

**Pull request closed without merging**
