### PR TITLE
Colourmap Attempt 2

### PR DESCRIPTION
**Pull request by PixelEater2018**
Thanks Rachael and Alexey for helping me to get through this!

This commit adds a BestColorNorm() function which takes fullbright colours and matches them to fullbright palette entries.

UpdateTextures() has been extended so it can use the new function to generate a lut with a neutral colourmap for the palette shader.

BestColor() has a slight modification to optionally ignore grey as a replacement for saturated colours.

Tonemap.fp has been altered to fix a glitch where the palette tonemap would teeter between two colour values due to rounding. It could be clearly seen in rsky2 of Doom2.

Other changes are just for cvars and menu entries.

### CODE REVIEW

**Comment by PixelEater2018** [comment]
Ah I got the wrong place for that then. Is amending the commit description safe when no files have been changed? I get this message:
screen shot 2019-01-25 at 7 21 30 am

**Comment by alexey-lysiuk** [comment]
Changing history it’s not safe no matter what you about to change, files or just a message.
In this case, however, this is the right thing to do. You need to commit and do a force push, otherwise remote will reject the changes.
SourceTree has the advanced option to enable force push checkbox in the corresponding window.

**Comment by raa-eruanna** [comment]
@PixelEater2018 I redirected this onto the old master branch since Graf created a new one. If you open a new pull request, please follow the instructions on this thread: (You will have to use the terminal)

https://forum.zdoom.org/viewtopic.php?f=49&t=63417

Alexey knows more than me about Sourcetree, he might be able to figure out how to do that with the GUI.

**Comment by madame-rachelle** [comment]
Superseded by https://github.com/coelckers/gzdoom/pull/817

**Pull request closed without merging**
