### PR TITLE
CMake: Fix building on 32-bit Linux (Core 2 Duo).

### PR DESCRIPTION
**Pull request by svdijk**
This fixes building on 32-bit Linux on my old Core 2 Duo laptop. It'd be nice if this could be merged before 3.0.0.

### CODE REVIEW

**Comment by alexey-lysiuk** [comment]
What was the compilation error? Post whole output of `make` please.

**Comment by coelckers** [comment]
My guess would be that it complained about not having SSE2 support for the intrinsics in the renderer. Weird that this still needs to be enabled explicitly on some systems.

**Comment by alexey-lysiuk** [comment]
I tried by myself on 32-bit Mint and it supports only x87 math without explicit compilation flags indeed.

**Comment by svdijk** [comment]
It was indeed complaining (albeit indirectly) about not having support for the intrinsics. Since this has already been merged I'm not sure if it's still needed/wanted, but here's the [make_output](https://github.com/coelckers/gzdoom/files/966126/make_output.txt).

By the way, I just noticed that I didn't update the comment above my change, "this file" should be changed to "these files".

**Pull request merged**
