### PR TITLE
Add support for editor config powered editors

### PR DESCRIPTION
**Pull request by Eonfge**
Before I'll add anything substantial to the codebase, I figured it would be nice to help you with standardizing some base layout elements within the codebase.

More info:
https://editorconfig.org/

This will prevent people in the future from mixing tabs and spaces for example.

### CODE REVIEW

**Comment by Eonfge** [comment]
@alexey-lysiuk They'll only trigger changes when people change and save the file. Also, you can chose to not commit them if it would otherwise be to disruptive. See it more as a guideline from point forward.

**Comment by alexey-lysiuk** [comment]
In the perfect world, it works like you said indeed. In the real world, those spaces will be committed with completely unrelated changes. It's so cool to check `diff` or `blame` polluted with such things.
I'll wait for other opinions on this.

**Comment by Talon1024** [comment]
IMO, before this gets added to GZDoom, someone should do a commit to trim trailing whitespace and remove whitespace on otherwise blank lines.

**Comment by Eonfge** [comment]
@Talon1024 That would be a big change...

**Comment by alexey-lysiuk** [comment]
Still, it's better than to have a bunch of unrelated changes that make diffs hard to read.
Even if we will decide to go this route, it won't happen while the refactoring is in progress.

**Comment by dpjudas** [comment]
Seeing what such an editorconfig file did in Raze, I don't think this is a very good idea unless it also includes one commit that puts the entire codebase into the form dictated by it.

Otherwise one innocent change in a non-conforming file will cause chaos when the editor gets confused and reformats the entire file. It happened multiple times for me in Raze and I'd rather not have the same happening to me when coding on GZDoom.

**Comment by Gaerzi** [comment]
Git tools need a setting to only commit whitespace changes to lines that have also been otherwise modified...

**Comment by coelckers** [comment]
Automatic formatters are a menace. I've just seen it again - this time in DukeGDX where one particularly large commit had the sources formatting changed, meaning it's impossible to find any relevant change in there. No way I'm adding such a thing to GZDoom.

**Pull request closed without merging**
