### PR TITLE
Replace "\033" with the more descriptive "\e"

### PR DESCRIPTION
**Pull request by Cacodemon345**

### CODE REVIEW

**Comment by Doom2fan** [comment]
Have you tested this in anything other than GCC? [A quick search](https://stackoverflow.com/a/10220539) says this is a non-standard extension from GCC.

**Comment by Cacodemon345** [comment]
> Have you tested this in anything other than GCC? [A quick search](https://stackoverflow.com/a/10220539) says this is a non-standard extension from GCC.

GCC and clang support it.

**Comment by alexey-lysiuk** [comment]
For me, it’s not descriptive at all.

**Comment by coelckers** [comment]
> 
> 
> > Have you tested this in anything other than GCC? [A quick search](https://stackoverflow.com/a/10220539) says this is a non-standard extension from GCC.
> 
> GCC and clang support it. The change made is also restricted to a source file that only gets pulled when compiling on POSIX systems.

This doesn't matter. We do not use compiler specific extensions unless necessary in a system interface. This isn't the case here.

**Pull request closed without merging**
