### PR TITLE
Merge dpJudas's renderslices branch

### PR DESCRIPTION
**Pull request by XaserAcheron**
[dpJudas wrote](https://forum.zdoom.org/viewtopic.php?f=4&t=71478&start=15#p1181923):
> This should generally be ready for merging now.

[Graf Zahl wrote](https://forum.zdoom.org/viewtopic.php?f=4&t=71478&start=15#p1184948):
> There is no PR so there's nothing to merge as far as I am concerned.

Here's a PR, then. Figured I may as well open one instead of waiting for y'all to finish waiting on each other. :P

### CODE REVIEW

**Comment by coelckers** [comment]
@madame-rachelle  Was it really necessary to squash such a large change into a single commit? This forfeits any chance to analyze potential problems that may come with it.

**Comment by drfrag666** [comment]
It's pretty much the same i think, most changes are in the first commit and the others are bugfixes. Another issue is that XaserAcheron appears as the author too when he just created the PR.

**Comment by madame-rachelle** [comment]
I can revert the massive commit if need be and then drop in the changeset individually but I'd really prefer to do it without altering histories.

**Comment by XaserAcheron** [comment]
Frankly, I was a bit surprised that GitHub let me make the PR anyway (and then signed my name on the dang merge :P ). Guess I accidentally hit my mischief quota for the day. :P

**Comment by drfrag666** [comment]
The PR itself was fine, i think it's a side effect of the merge when you choose one of the three options.

**Comment by madame-rachelle** [comment]
Yeah that is why Graf didn't like the way I did it. I normally use squash merges most of the time because a bunch of PR's come in like "- did this" "- reverted previous commit" "- oops" and we try and get rid of those. It's a pretty common request that the PR's get squashed. I prefer having a commit history to be quite honest, but at the same time, it's too easy to have a lot of useless fluff commits - and those are bad enough from the internal developers, having them come from externally too is far from ideal.

**Comment by drfrag666** [comment]
I normally use the third option, rebase and merge.

**Pull request merged**
