### PR TITLE
Various texture related fixes

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
Fixed debug assertion failure in texture precaching
Fixed allow to use all hqNx texture upscale modes
Added missing hqNx modes to options menu
Enabled nqNx 16-bit (MMX/SSE implementation) on all platforms

### CODE REVIEW

**Comment by Mateos81** [comment]
Would some of these fixes benefit ZDoom, and thus GZDoom when getting merged afterward?

**Comment by alexey-lysiuk** [comment]
No, all these changes are for GZDoom only. There is no high quality texture scaling in ZDoom. The assert fix is for code added in GZDoom too.

**Comment by alexey-lysiuk** [comment]
Actually, I could merge it myself, but I would like to have a sort of review first.

**Comment by Mateos81** [comment]
Oh OK ^^'

**Comment by coelckers** [comment]
I have the following issues here:

1. The hqNx 16 bit code does not work on all platforms to my knowledge. This was the reason it once got removed in the first place. Furthermore, 16 bit implies lower quality. But this code was reinstated because the edge smoothing of the plain C version was significantly worse.

2. Why enable SSE2 for floating point? This provides no performance advantage. In fact, for me the x87 version has been consistently faster, albeit marginal.

**Comment by alexey-lysiuk** [comment]
hqNx implementation via intrinsics is working on all Intel based platforms. MSVC/GCC/Clang supports it without a problem on Windows and POSIX OSes. I'm not aware of any non-Intel platform that runs GZDoom 2.x and honestly 1.8 too (there were a few PowerPC Macs that supported OpenGL 2.1). So I think it's rather pointless to complicate code and CMake files for no reason.

`-msse2` switch is required in order build it on Linux. `-mfpmath=sse` can be removed indeed. I copy/paste it from SSE detection in the same CMakefile.txt file. If you prefer, I'll add `-msse2` option for hqNX file only.

I agree that naming for hqNx modes isn't perfect. Could you please propose better names? 'hqNx' vs 'hqNx ASM' maybe, although the latter doesn't use assembly but MMX/SSE intrinsics.

**Comment by coelckers** [comment]
Does the MMX stuff work on 64 bit, too?
Aside from that I'd still like to have it conditionally. Who knows when the first ARM based computers appear that can compile GZDoom? Then it must be possible to disable it.

For naming, how about hqNX/hqNX MMX?

For the SSE math stuff, why is this required? I got no reports about this in the past. Has something changed?

**Comment by alexey-lysiuk** [comment]
SSE implementation is needed for Win64 only. Other platforms supports MMX intrinsics for x64.

MMX hqNx was available on Windows only. So no additional switches were needed for GCC/Clang. I think `-msse2` switch can be replaced with `-mmmx` if it matters.

I'm still looking for good solution for detection of MMX presence.

**Comment by cmbruns** [comment]
Could we use a CMake try_compile() stanza to detect mmx presence? 
https://cmake.org/pipermail/cmake/2010-March/036115.html

**Comment by alexey-lysiuk** [comment]
What I don't like in `try_compile()` is inability to compile a file. It tries to build executable and so it requires complete program with `main()`.
But it looks like this is the right way to check MMX presence.

**Comment by Blzut3** [comment]
The first ARM computers running GZDoom already happened.  Beloko's Android port uses GZDoom.

**Comment by coelckers** [comment]
Right. Forgot about this. So unconditional inclusion of MMX/SSE stuff is a no-go.

**Comment by alexey-lysiuk** [comment]
At the moment I have an issues with passing compiler flags to `try_compile()`.
So I decided to split enabling of hqNx MMX on supported platforms from other fixes.
Please take a look at #34.

**Pull request closed without merging**
