### PR TITLE
Make TArray safe for non-trivially-copyable classes

### PR DESCRIPTION
**Pull request by kcat**
Most notably, GCC complains about `FHardwareTextureContainer::TranslatedTexture` not being trivially copyable but used with `memmove` in `TArray` on most source files, flooding the compiler's output. Looking into it, [only trivially copyable types can be used with `memmove` and friends](https://en.cppreference.com/w/cpp/types/is_trivially_copyable), and [the presence of a non-trivial destructor makes it not trivially copyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable), which makes the aforementioned struct non-trivial since it has a destructor that deletes a pointer.

I've gone through all the warnings to ensure the types used with `TArray` are all either trivially copyable or have correct copy/move semantics, and replaced the bit-fiddling with proper copies/moves. Things still seem to work, but some more testing wouldn't hurt.

Also worth mentioning, there are other cases of `memcpy` and `memset` used with non-trivial types that GCC complains about. Among those, there are `sector_t` and `vertex_t`, however it seems there's a particular use of those that requires bit-perfect copies. That's out of my depth for fixing (either making trivially copyable, or working without bit-perfect copies). But either way, the warnings coming from `TArray` have been cleaned up so the others are more visible.

### CODE REVIEW

**Comment by coelckers** [comment]
I am putting this on hold for the time being. I'd rather analyze the cases where things are not trivially copyable when they should than hiding the problem behind some added template glue,

Also, what about efficiency? I do not really trust C++ template functions to work well here.

**Comment by kcat** [comment]
Most uses of `TArray` are with trivially copyable types, or at least never generated a warning. `TArray<sector_t>` objects, for instance, never called `Delete` or `Insert` so it never generated a `memmove` call and thus no warning (or if they did it was a single time, hidden among all the other `TArray` warnings). The vast majority of `TArray` warnings were with `TranslatedTexture`, along with a handful involving `FString` or classes that contained an `FString`. I haven't touched the non-`TArray`-related cases of `memcpy`/`memset`, so all those warnings remain and the relevant classes can be found.

Regarding efficiency, with trivially copyable types `move`/`move_backward` (and `copy`/`copy_backward`) are optimized to `memmove`. I've seen it do that with my own code. Non-trivially-copyable types may or may not optimize like this, depending on the assignment operator behavior. If they don't, it's a good bet they probably shouldn't be. As it was, the `memmove` calls were in the `Insert` and `Delete` methods, which aren't going to be very efficient with non-trivial types anyway since there's construction/destruction to do. Anecdotally, even on my crappy system I haven't noticed a single performance problem from the change; if anything it feels a bit better, but I also updated recently which might be affecting that.

**Comment by coelckers** [comment]
Like I said, this is something I want to review first, mainly because many of the examples you cite should be trivially copyable, and if they are not they need to be fixed. Especially sector_t won't work if it isn't.

And I certainly won't add something invasive like this right before a new release.

**Comment by kcat** [comment]
Certainly understandable to not merge it right before release. As I said, it could do with more testing.

About the mentioned examples, it seems `sector_t` isn't trivially copyable because it contains `FName`, which has a non-trivial copy constructor (fixable by defaulting it).  `vertex_t` isn't trivially copyable because it contains a destructor that deletes `sector_t**`s and `float*`s (doesn't seem easy to fix). `FString` should be obvious (manages string memory), and `TranslatedTexture` has a destructor that deletes a held `IHardwareTexture*`.

I'll take another look through, trying to filter out just the `TranslatedTexture` warning spam and get a complete list of what `TArray` complains about, and figure out why for each of them.

**Comment by kcat** [comment]
Okay, here's what I  found. Ones marked with * are themselves fine, they're only an issue because they contain a non-trivial type (which will also be listed).

Warned from `TArray` only (possibly; might've missed some non-`TArray` warnings):

`FHardwareTextureContainer::TranslatedTexture` -> Non-trivial destructor
`FName` -> Non-trivial copy constructor
`TabData` -> Non-trivial copy constructor, contains `FName`
`TArray` -> Non-trivial copy/move ops, destructor
`FNotifyText`* -> Contains `FString`
`FFoundWadInfo`* -> Contains `FString`
`FStateDefine`* -> Contains `FName`, `TArray`
`FEpisode`* -> Contains `FString`
`FMugShotState`* -> Contains `FName`, `TArray`
`PrecacheDataPaletted`* -> Contains `TArray`
`PrecacheDataRgba`* -> Contains `FBitmap`
`TexInit`* -> Contains `FString`, `FScriptPosition`
`BuildInfo`* -> Contains `FString`, `TArray`
`FPlayerSkin`* -> Contains `FString`
`ZCC_ConstantWork`* -> Contains `TArray`, `PSymbolTable`
 
Implicated:
`FBitmap` -> Non-trivial move ops, destructor
`FScriptPosition` -> Non-trivial copy ops
`PSymbolTable` -> Non-trivial destructor, contains `TMap`
`TMap` -> Non-trivial copy ops, destructor

Warned from non-`TArray` uses (memcpy requires trivial copy, memset requires trivial construction(+copy?)):

`vertex_t` -> Non-trivial destructor
`GenericValue` -> Non-trivial copy/move ops, destructor
`FString` -> Non-trivial copy/move ops, constructor, destructor
`sector_t`* -> Contains `FName`
`FSoundChan`* -> Contains `FSoundID`
`GenericMember`* -> Contains `GenericValue`
`FTerrainDef`* -> Contains `FName`, `FSoundID`
`FDynamicLight`* -> Contains `FCycler`
`EDSector`* -> Contains `FName`
`FMapThing`* -> Contains `FName`
`FPlayerColorSet`* -> Contains `FName`

Implicated:
`FSoundID` -> Non-trivial constructor
`FCycler` -> Non-trivial constructor

**Comment by coelckers** [comment]
Here's the problem: FString is trivially moveable inside an array, as is TArray itself. By changing to your code this will imply severe inefficiencies to many internal arrays that are currently fast but will no longer be afterward. 
It's really too bad that we cannot declare a class as safely moveable inside a container and in order to silence all these warnings have to use crutches that make the code a lot less performant.

**Comment by kcat** [comment]
> Here's the problem: FString is trivially moveable inside an array, as is TArray itself, and TMap.

Only by happenstance, the language, compiler, and system make no such promise. `TArray`'s code is unambiguously and unquestionably wrong for non-trivial types. The language says these types aren't trivially copyable and it's undefined behavior to use `memcpy`/`memmove` with them, and the compiler is telling you to not do it. All it'll take is the compiler deciding to do something unorthodox for non-trivial types with the struct data or layout and cause the copied memory to not correctly represent the object (debug/instrumentation data that depends on a consistent address, or hidden data not being overwritten when copied into, for example). Or for someone to use it with a type that truly can't be bit-copied (a struct that contains a pointer to something in itself, for example).

> By changing to your code this will imply severe inefficiencies to many internal arrays that are currently fast but will no longer be afterward.

If you're expecting insertion and deletion in the beginning or middle of a dynamic array to be fast (especially with `FString`, `TArray`, and `TMap` which have potential allocations/deallocations to do on the inserted/deleted element), then there's other problems to worry about than slightly slower moves. In any case, if there's some place that shows a severe drop in efficiency, or some place you're worried might, let me know where and I can take a look.

> I am simply not willing to take that performance hit to appease a compiler's warning output.

Then I'm not sure what you want to happen. The code isn't right and there's no telling when it may break, how that break will manifest, or how easy it will be to fix later. The number of warnings generated from just `TArray` alone makes it next to impossible to notice any other warning, and turning off that type of warning will blind you to cases where it can be an active problem. It would also hinder discovery of types becoming non-trivial that need to be trivial; we would've never realized the listed structs had problems were it not for this.

**Comment by kcat** [comment]
> TBH, it wouldn't surprise me if C++ eventually addresses this with some sort of relocation operator, that allows moving an object to another memory location while simply discarding the old location - if such a thing existed it'd make the standard containers a lot more efficient and this is something that occurs quite frequently in production code.

That's basically what moves are to help facilitate. When implemented properly, the compiler would be able to see you're just moving consecutive blocks of memory and coalesce that into a `memmove` or similar. The "trick" is to make sure that after an object is moved from, being moved into would just require a copy of all members. Consider an example with a non-trivial type:
```
class Foo {
    char *ptr;
    size_t len;

public:
    Foo& operator=(Foo&& rhs) noexcept
    {
        delete[] ptr;
        ptr = rhs.ptr; rhs.ptr = nullptr;
        len = rhs.len; rhs.len = 0;
        return *this;
    }
    ...
};
```
If you're moving an array of these sequentially over by one, for example, a clear pattern emerges when inlined:
```
delete[] foo[0].ptr;
foo[0].ptr = foo[1].ptr; foo[1].ptr = nullptr;
foo[0].len = foo[1].len; foo[1].len = 0;
delete[] foo[1].ptr;
foo[1].ptr = foo[2].ptr; foo[2].ptr = nullptr;
foo[1].len = foo[2].len; foo[2].len = 0;
...
```
Starting at the second iteration, you're always deleting a null pointer, which is a defined no-op, so they can be optimized out. You can also see foo[n] is being cleared to null/0, then immediately overwritten with values from foo[n+1], also a clear optimization opportunity. A more optimized look at the inlined sequence:
```
delete[] foo[0].ptr;
foo[0].ptr = foo[1].ptr;
foo[0].len = foo[1].len;
foo[1].ptr = foo[2].ptr;
foo[1].len = foo[2].len;
...
```
If a compiler can't optimize that to a `delete`+`memmove` or equivalent, there's no hope for it. FWIW, the language says that the only requirement for a post-moved object is:
"Unless otherwise specified, all standard library objects that have been moved from are placed in a valid but unspecified state. That is, only the functions without preconditions, such as the assignment operator, can be safely used on the object after it was moved from"

So for something like FString, as far as the standard is concerned it does not need to represent anything after being moved from, and can be done in a way that chains like that (whether or not the engine code can rely on FString doing that is a different story, and something to look at if performance with it is a problem). The only things you need to be able to do with it is assign it a new value (where it takes on a specified state again) or destruct it (which should be a no-op since it has nothing to dereference). Move operators for `TMap` and `TArray` can be made to do this just fine.

> Actually, if the compiler started doing that, a lot of stuff would break in other software as well. Let's be clear here: We are developing a game where performance matters, and these kinds of security concerns are often counterproductive. FString was specifically designed to be safe to put in TArray - the entire object consists of a single pointer to some external data structure with no backwards references.

But if you're updating compilers, it's expected you're updating code to maintain compliance. The language does remove stuff and break code -- C++17 broke code that used trigraphs, `auto_ptr`, the `register` storage class, increments on bools, and `throw()` exception specifications (things that all worked prior), C++14 broke code that relied on `constexpr` member functions being const, C++11 broke code that relied on the `export` keyword and the `auto` storage class -- though in just about all these cases the compiler would issue warnings ahead of time, giving you a chance to fix your code before the update that finally broke it.

Yes, performance matters. I would go as far as to say you should always be performance-minded even outside of games. But it's not like it used to be where you needed to fight against the language and compiler just to hope for good performance out of C++. Understand and work with the language, and the compiler can do a lot for you these days (both in terms of performance, and bug analysis). And even where they may have problems, they're constantly getting better.

To reiterate, though, I'm fully on board with keeping this PR open so it can be further tested, and any issues or performance problems can be identified and fixed prior to merging. The code base is quite old, and mixing new guidelines and practices with old ones can create added friction. Even if there wasn't an imminent release, some extra time to check would be good. I just don't think the idea of fixing the code to be more correct should be dismissed out of a concern it might slow down too much, especially if leaving it alone can cause a major breakdown if or when the compiler does something that the language says it can.

> No, that cannot happen unless we were talking about insane compiler developers that do not respect the programmer anymore. One of the core principles of C++ is that you get what you define - nothing more, nothing less, and certainly not something that is fundamentally incompatible with the contents.

You get more than you define all the time. Hidden padding between struct members for more efficient access, virtual functions creating hidden vtable pointers, silently creating temporary objects, or static local variables requiring extra boolean flags and mutexes. You also get less than you define quite often too; short lived local variables, lambdas, and `std::bind` objects are routinely optimized out, for example, removing redundant copies and avoiding unnecessary stack usage. I've replaced plain old `for(int i=0;i<count;++i)` loops with a lambda or bind passed to `std::for_each`, `std::transform`, and other algorithms, and the resulting binary code came out exactly the same.

One of the core principles of C++ is you don't pay for what you don't use. When you use something, the compiler does what it needs to while also trying to minimize its cost. How exactly it does that and what the cost ends up being is up to the compiler, given what the language says and how good the optimizer is.

What you call insane compiler developers that don't respect the programmer, I call the programmer finally getting a slap on the wrist for doing what they were constantly told not to. As a programmer myself, I want the compiler to leverage anything the language allows it to for optimal code generation, and not be pessimizing the code when it could be optimizing it. The compiler is working in service to your code, not against it, so if it's warning about something, there's a reason for it. Consequently, if the compiler does unorthodox things that the language allows it to, it's because there's a legitimate benefit to enough people.

**Comment by coelckers** [comment]
FnameNoInit is long gone, I had to make FName trivially copyable for other
reasons where it was really important, like copying around sectors.
The problem with the static asserts is that this probably cannot catch
structs with FStrings.

**Comment by Blzut3** [comment]
Must have did a find in files on the wrong directory.  Anyway you're right about not handling structs with FString.  Given that as far as I'm aware the TArray limitations have tripped us up exactly zero times the most sane thing is probably just to silence the warning and be done with it.  It would be possible to do some template metaprogramming to check for a member type alias or perhaps an enum value, but that's a fair amount of ugly code for a minor sanity check.  Probably would be more productive to just be more proactive about static_asserting at declaration point on structures you believe should be trivial, because hacking around the performance issues of unexpectedly non-trivial structures is a thing that has happened.

**Comment by coltongit** [comment]
Can this be closed since the issue has already been dealt with? Or will this be reassigned in the future?

**Pull request closed without merging**
