### PR TITLE
Show subtitles just before the Entity boss fight in Strife.

### PR DESCRIPTION
**Pull request by nashmuhandes**
This required editing and recompiling the Strife helper ACS library.

### CODE REVIEW

**Comment by nashmuhandes** [comment]
Any problems with this implementation?

**Comment by coelckers** [comment]
Only missing an explanation what this is for.

**Comment by nashmuhandes** [comment]
@coelckers -

Ah, apologies for the lack of explanation.

In the final map of Strife, MAP29, just before approaching the Entity, there are some scripted voice clips that the player can listen to.

Subtitles for these lines exist in [language.csv](https://raw.githubusercontent.com/coelckers/gzdoom/master/wadsrc_extra/static/language.csv) (search for `TXT_SUB_LOG128` and `TXT_SUB_LOG130`) but they never get shown on the screen; only audio is heard.

So what I did here is make the ACS scripts give a newly-made item to the player, which - when picked up - sends the necessary SetSubtitleNumber calls to print the subtitles to the screen.

Here's a short video showing the problem I was trying to fix.

[alt text](https://youtu.be/fRYhhx-DW1Q)

**Comment by coelckers** [comment]
Ah. But don't you think it would have been better to add a new ACS function for this instead of an inventory hack?

**Comment by nashmuhandes** [comment]
> Ah. But don't you think it would have been better to add a new ACS function for this instead of an inventory hack?

Well, at first I thought of the saying, "do as the Romans do"... ;)

Agreed, that's a way better idea. I'll make a new PR.

**Pull request closed without merging**
