### PR TITLE
Export Matrix4

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
For projections and transformations

### CODE REVIEW

**Comment by ZippeyKeys12** [comment]
I broke RelWithDebInfo??

**Comment by ZippeyKeys12** [comment]
As opposed to a struct? or what?

**Comment by ZippeyKeys12** [comment]
Vectors are already treated weirdly, I'd rather not touch that. If anything, I'll cut out the matrices and make another commit for just `ProjectToScreen`

**Comment by coelckers** [comment]
Why did you build this upon the softpoly renderer's matrix and not the already existing VSMatrix which is outside the renderer code?

And yes, this should be a struct, not a class.
Concerning vectors, they are not treated "weirdly", they are mostly done with VM intrinsics for performance. For matrices this isn't needed, though.

**Pull request closed without merging**
