### PR TITLE
Update level_compatibility.zs

### PR DESCRIPTION
**Pull request by edthebat**
Map fixes for some older mods

### CODE REVIEW

**Comment by coelckers** [comment]
Can you please add links to the mods? They are mainly obscure so I cannot check what was done here.

**Comment by edthebat** [comment]
Yes, sir!
One against hell: https://www.doomworld.com/idgames/levels/doom2/Ports/m-o/one1
Toon Doom II: https://www.doomworld.com/idgames/levels/doom2/megawads/toon2b
Valletta's Doom Nightmare: https://www.doomworld.com/idgames/themes/terrywads/vltnight
Swan Fox Doom v2.4: https://www.wad-archive.com/wad/7bd37271e818ef60456e3370501c31dd

If there any objections to including any of these mods in level_compatibility, I am perfectly willing to host my fixes personally in user-made patches, which are thankfully now possible with the advent of the level_postprocessor.

**Comment by edthebat** [comment]
> Also, do you have a spacebar broken on the keyboard?
I hardly feel that level of attitude was warranted... but fine, I can add spaces after commas and comments if it will make you happy.

**Comment by alexey-lysiuk** [comment]
No offense, but let’s not forget that the code is mostly read, not written. The thing is how it was written does matter. If it’s hard to read, then it was written poorly.

**Comment by edthebat** [comment]
I genuinely find spaces after commas make code harder to read. In addition to wasting filespace; sometimes every byte can matter.

However I do agree with you that consistency is important, and since the existing body of the file follows those conventions, I can adapt my commit to match. After all, I even followed along with adding braces around the body of each Case, even though that doesn't follow any conventions I'm aware of for Switch statements.

**Comment by madame-rachelle** [comment]
I'm going to go ahead and take this one since it seems pretty harmless. If I am wrong the changes can always be undone.

**Pull request merged**
