### PR TITLE
Git version

### PR DESCRIPTION
**Pull request by winterheart**
Now version-specific information placed in CMakeLists.txt file.
gitinfo.h and version.h will be generated each time when commit or version changes occurred.

### CODE REVIEW

**Comment by coelckers** [comment]
I see absolutely no advantage here, especially since it involves changing version.h too frequently.

**Comment by winterheart** [comment]
version.h updates only when CMakeList.txt changes. And advantage is that git version now available not only for Windows platform.

But, if you think that code simplification is not advantage, OK then.

**Comment by coelckers** [comment]
I wouldn't call it 'simplification' to move the contents of a small and contained file with all those versioning defines into a larger file that contains a lot more stuff that is entirely unrelated to versioning.

**Comment by alexey-lysiuk** [comment]
Git version is available on all platforms. The single requirement is `git` executable in search path.

**Pull request closed without merging**
