### PR TITLE
Attempt to make TiMidity++ work on GNU/Linux again

### PR DESCRIPTION
**Pull request by Talon1024**
The recent OpenBSD support commit broke TiMidity++ on Linux. This is my attempt to fix that.

### CODE REVIEW

**Comment by Talon1024** [comment]
I don't know why execvp fails, though. But, I think it's a start.

**Comment by raa-eruanna** [comment]
From my tests, on the current commit, GZDoom does not even start when Timidity is selected.

**Comment by Talon1024** [comment]
Try it now. Hopefully, GZDoom will at least start up now.

And, for the record, I am also using Ubuntu 16.04 x86_64.

**Comment by raa-eruanna** [comment]
Now I am getting the error "execvp failed: Bad address" - it does at least start, but no timidity is working. (I went and set timidity_exe to "/usr/bin/timidity" after installing it, and I configured it to use "/home/raa125/timidity.cfg" which points to a soundfont in the same folder)

**Comment by Talon1024** [comment]
I'm glad to hear GZDoom starts up, but as I said before, I have no idea what is causing execvp to fail.

Running `explain -e 'Bad address' -- execvp /usr/bin/timidity  -EFchorus=1 -EFreverb=1 -s44100 -o - -OrsS1 -id  /tmp/zmidqyrNvr` gives me this:

`execvp(pathname = "/usr/bin/timidity", argv = ["/usr/bin/timidity",
"-EFchorus=1", "-EFreverb=1", "-s44100", "-o", "-", "-OrsS1", "-id",
"/tmp/zmidqyrNvr"]) failed, Bad address (14, EFAULT) because pathname or
argv or envp refers to memory that is outside the process's accessible
address space; this is more likely to be a software error (a bug) than it
is to be a user error`

**Comment by Talon1024** [comment]
Holy shit, I think I got it working. Looks like I needed to add a null pointer at the end of TimidityArgs.

**Comment by raa-eruanna** [comment]
Merged w/ rebase, after testing it. It seems to work on both Windows and Linux, properly, now.

**Pull request closed without merging**
