### PR TITLE
WorldThingPrePickedup & WorldThingPickedup (incomplete)

### PR DESCRIPTION
**Pull request by XxMiltenXx**
This implements WorldThingPrePickedUp and WorldThingPickedUp as events for the Event handlers, however, as pretty much all of the inventory handling is virtualized I was unsure where to place the corresponding functions, so I will leave that up to you.

WorldThingPrePickedUp is right before the item would be going into the inventory. If "shouldpickup" return false in the event, it will be prevented.

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
1. You have marked shouldpickup as readonly, which makes this unusable.
2. I would recommend reusing the already existing Actor Thing component of the WorldEvent struct, rather than adding a new one just for these events.

**Comment by XxMiltenXx** [comment]
Sorry, just saw your reply as the response notification e-mail was in my spam folder.

About 1.: I removed the "readonly" flag
About 2.: That is what I am doing - at least it was my intention. The existing actor "Thing" represents the item that is picked up. The added actor "Toucher" represents the actor that picked up the item. So I had to add another actor.

Where would be the best place to put this function in general? Most of the inventory functions are virtualized, and calling it in a virtualized function where it can be overriden defeats the purpose of having this.

**Comment by OrdinaryMagician** [comment]
Hmmm, I see I see...

**Comment by coelckers** [comment]
This is still marked incomplete after such a long time, so I think this best gets closed.

**Pull request closed without merging**
