### PR TITLE
Add Doom 64-style additive lighting

### PR DESCRIPTION
**Pull request by Talon1024**
I'm working on adding [Doom 64-style additive lighting](https://forum.zdoom.org/viewtopic.php?f=59&t=62956).

### CODE REVIEW

**Comment by coelckers** [comment]
Can you give a little more information about your problem. Is this only shader side or does the actual property get overwritten?`

**Comment by Talon1024** [comment]
I made the SpecialColors array in sector_t larger in order to store the additive colour. The issue I had was that the default value for the additive colour was white rather than black.

But now that I think about it, it makes sense that all the other default "special colours" are white, because they are multiplied with the texture colours in order to create the Doom 64 lighting effects, and obviously the Doom 64 lighting effects should not be applied by default.

I fixed it by adding a line below the line that sets the default values for each special colour, but I'm thinking of adding another colour array to sector_t that is initialized to 0 by default, and possibly doing the same to sidedef_t in order to make the additive colour stuff more flexible.

**Comment by coelckers** [comment]
By "adding another color array", do you mean setting independent additive colors for every element?

**Comment by Talon1024** [comment]
Yes.

**Comment by coelckers** [comment]
Just one quick question: Is it like this in Doom64 where the additive part gets applied before the modulating part of the color?

From a pure editing point of view the reverse order seems to make more sense. Aside from that this looks good to me.

**Comment by Talon1024** [comment]
Based on what I've seen from my Doom 64 EX screenshots, the additive color is applied before multiplying it with the gradient colors. You can see it in [this video](http://www.ciinet.org/kevin/myimages2/doom/misc/Doom64ComparisonAnim.webm).

**Pull request merged**
