### PR TITLE
Re-add Solaris support

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR re-adds support for Solaris systems.

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
Your changes for simple chars make the savegame code non-portable. You got to force signed chars via compiler option if they are not the default - it is very likely that some things may break if the signedness of chars is left undefined.

In addition, what's the issue with removing int8_t and uint8_t in the serializer functions?

**Review by alexey-lysiuk — COMMENTED** [review]
In my opinion, various unrelated issues are attempted to be fixed by a single commit.
May I ask you to post all error messages that were reported?

**Comment by Cacodemon345** [comment]
1. `int8_t` is erroneously defined as simply `char` in Solaris (possibly preprocessor defined), causing compilation failure.
Would it be better to ifdef the problem code and unconditionally force `char` as signed?
2. `PATH_MAX` isn't defined outside of `limits.h` in Solaris causing failures.
3. `alloca` is not defined unless including `alloca.h`.
4. `-pie` is unsupported on Solaris.

**Comment by coelckers** [comment]
'char' needs to be signed. Long term, once C++20 becomes viable all string literals should be converted to char8_t, all remaining uses if 'signed char' and 'unsigned char' to int8_t and uint8_t and all use of regular 'char' be reduced as much as possible.

I don't get it why these type shenanigans in C cannot be cleaned up for good - it's nothing but problems. On macOS, int64_t is a simple long, for example, which causes the same sort of issues if not all uses are transitioned to the sized types from stdint.h.

**Comment by Cacodemon345** [comment]
I found out that `int8_t` is defined as `signed char` only if the default `char` type is unsigned on Solaris.

I will revert the changes to the savegame code and instead ifdef the `int8_t` portion of the savegame code behind a Solaris platform check.

**Comment by coelckers** [comment]
What kinds of idiots have written that header?
But you cannot just #ifdef that code for Solaris. The same code gets used in Raze which needs to use unsigned chars, thanks to ancient Build stupidity.

**Comment by Cacodemon345** [comment]
Only the `int8_t` part of the code needs to be #ifdef'd with an additional check if the preprocessor symbol `_CHAR_IS_SIGNED`. The rest can be left off as-is.

**Comment by Cacodemon345** [comment]
I would tackle Raze at a later time when actually needed; I don't believe later Build source ports ever supported Solaris.

**Comment by Cacodemon345** [comment]
Are you okay with the explicit preprocessor check for `_CHAR_IS_SIGNED` in the serializer when building for Solaris? That should take care of the Raze issue.

**Comment by Cacodemon345** [comment]
Seems like this PR will have to be rebased.

**Comment by coelckers** [comment]
I decided to close this. Some of the issues will probably be resolved once we migrate to C++20 and can get completely rid of direct use of short integer types. We should also see to get rid of alloca in our code, instead of adding more includes for it. (In short: no code outside the platform code should include platform headers.)

**Pull request closed without merging**
