### PR TITLE
Serialize ZScript-created translations

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
This is step one of what I need for redoing SetBloodColor, as it will be making use of this translation table.

This new table gets serialized just like TRANSLATION_LevelScripted. To verify that it works, I've made an example map [here](https://github.com/coelckers/gzdoom/files/2710262/trns_m.zip).

To see that it works:

1. Start a new game.
2. Save the game manually.
3. Restart GZDoom.
4. Load the save from the main menu.

The columns should have their custom blends preserved and restored correctly.

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
Actually, hold on, I think it would be better if I make these get serialized in globals.

**Comment by coelckers** [comment]
This doesn't really solve the main problem of a system that's simply not up to the task it needs to perform. This needs a rewrite from the ground up in a way that just works better.

**Comment by OrdinaryMagician** [comment]
Explain, please.

**Comment by coelckers** [comment]
The entire translation system is broken. Trying to patch over the
deficienicies is not really going to work out.
This needs a completely different approach to how translations are stored.

**Pull request closed without merging**
