### PR TITLE
Multiple fixes for Congestion 1024 (1024.wad)

### PR DESCRIPTION
**Pull request by Player701**
Proposing to fix some issues in this PWAD mentioned in the Doom Wiki. All of the following issues have been confirmed by me personally, and their fixes have been verified. The WAD itself can be found [here](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/1024).

### Not fixed:

> It is possible to grab the megaarmor in secret #1 through the door before you open it by running into the door. No straferunning is required to pull this off, although it is best to start from the opposite wall.

It's possible to move the armor father inside the closet, but then its sprite will appear partially stuck inside the wall when viewed from certain directions. I guess I could make the closet bigger, but I'm not sure whether it's feasible to alter parts of the map like that just to fix a small non-gamebreaking bug. Would like to hear a developer's opinion on how to proceed, not fixing this for now.

### Fixed:

> In front of the door blocking the exit is a small space that you cannot step in, even though you should be able to, until you open the door. This is a nodebuilding error caused by the then-current version of ZDBSP.

Fixed by rebuilding nodes. Having played through this map with rebuilt nodes, I did not find any issues.

### Not fixed:

> It is possible to fall behind the third and fourth pillars from the south in the northeast corner of the level (sectors 36 and 37) while attempting to navigate them. If this occurs, you will be unable to escape unless you use the noclip cheat.

This is indeed possible, but it's extremely tricky to fall down there, because you have to stand at just the right spot. Furthermore, I have no idea of a "clean" way to fix this. Perhaps I could alter the position of some vertices there to make the gap narrower. Would like to hear a developer's opinion on how to proceed.

### Invalid:

> When playing in a non-ZDoom-based source port, the wide lights in the gray STAR hallway (linedef 671) suffers from egregiously poor texture alignment, and the exit door (linedef 1995) has a garbled texture. These are nodebuilding errors caused by the then-current version of ZDBSP, which occasionally did not write a level's SEGS data correctly. 

It says explicitly that ZDoom-based ports are not affected. Having played through the map, I didn't encounter any glitches that could be a result of badly generated nodes. I probably shouldn't add maps to the node rebuild list "just in case"... or should I?

### Invalid:

> The doors back to the starting room don't open from the outside. 

I could not reproduce this, and since the exit switch is located in this room, it would make the map unwinnable. But I was able to complete it just fine, so... WTF?

### Fixed:

> This level does not contain a Player 3 start position, preventing cooperative multiplayer games from being played with three players or more. On the other hand, there are two Player 2 start positions, potentially causing a voodoo doll to be generated to the left of player 1.

GZDoom does not error out with 3 players but generates a voodoo doll at the extra player start, so I've fixed it by changing the type of the corresponding mapthing.

### Not fixed:

> The backpack in secret #1 can be obtained without lowering the panel by straferunning at it from the opposite wall. 

Same issue as in MAP01, and a fix for this one would be even more difficult due to the surrounding architecture. Not sure if this is worth fixing.

### Invalid:

> The switch found at the top of the building stairs (linedef 889) has a garbled texture. This is a nodebuilding error caused by the then-current version of ZDBSP, which occasionally did not write a level's SEGS data correctly. 

Like with MAP03, I could not reproduce this issue, and I also did not encounter any other glitches.

### Fixed:

> Six shotgun guys and two chaingunners inside a teleport closet outside of the map are not able to enter the map. This is because the blocks that prevent them from teleporting into the map (sectors 92 and 158 which have tags 22 and 16, respectively) have no corresponding linedef tags that lower them. Furthermore, the left side of sector 92 has a linedef with tag 23, however there is no corresponding sector in the map with tag 23 that would presumably allow the shotgun guys to teleport in. 

Since the triggers are missing, it is impossible to guess the original intent of the mapper, so I've decided to fix this by removing the offending monsters entirely.

### Not fixed:

> You can jump out of the 1024×1024 zone from the room with the switch that lowers the yellow skull keycard pillar.

This is indeed possible, but I'm not sure if I should fix this or not. It is very hard to escape unintentionally, and the outside area has damaging floors everywhere, so the player can't get stuck there unless they are in godmode. There are a lot of HOMs outside though. Please tell me if a fix for this is necessary, and if it is, I will include it in my next PR.

### Invalid:

> The red skull keycard is absent in difficulty 1-2. The red door does not open but you can enter the zone with the catwalk on the right (this prevents the baron of Hell's pit after the barrels to go up). Use the cheat tntkeyrs for the next switch.

This is not true, I checked the map with an editor. No fix necessary.

### Fixed:

> Three or four monsters (depending on your skill level) will not teleport. This is because the teleporter line points to tag 34, but there is no corresponding sector with tag 34.

Fixed by removing these monsters from the level (same as with MAP10).

> A zombieman (Thing 18) in the southwest has no flags set for any of the three difficulty classes, so it does not actually appear in the level. It was probably supposed to be set at Hey, not too rough and below, for at the same position is a shotgun guy at Hurt me plenty and higher.

Fixed by setting the appropriate skill flags.

### Also fixed:

One of the lines in the exit door sector has a missing texture (doortrack).

### Invalid:

> The door after the bridges room can't be opened from this room. Noclip once, open it and go back.

> The yellow door can't be opened the right way, open it from the bridges room then run back.

I could not reproduce any of these issues. Every door in the map opened normally for me.

### Fixed (not listed):

This map contains three duplicate keys that are supposed to disappear upon grabbing the actual keys placed within the playable area. However, the duplicate red key is bugged and won't disappear. This is because the trigger lines use the wrong special (```Floor_LowerToHighest``` instead of ```Floor_LowerToLowest```). Changing it, however, will break things elsewhere in the map, so I've gone with another approach instead - the sector with the duplicate red key has been re-tagged, and the correct special has been assigned directly to the actual red key itself, so the duplicate key will now correctly disappear as soon as the actual key is picked up.

### Not fixed:

> You can kill a few monsters before they can teleport.

~~The areas with teleporting monsters are blocked by some bars and also covered with lines that have middle textures, which obviously don't block shots. It is thus possible to shoot through the bars and potentially harm or kill some of the monsters before they can teleport out, so I've fixed it by making the corresponding lines block everything.~~

Changes removed by request of @coelckers 

### Invalid:

> The player must go out of the 1024×1024 zone to end the level.

This doesn't look like something that can be fixed, since it only violates the mapping convention.

### Invalid:

> There are infinitely tall hanging corpses that can bother you if you are playing old school.

This is actually not correct, since the corpses in question are of non-solid variety.

### Invalid:

> The infinitely tall hanging corpses in the last part of the map will force you to noclip. 

I couldn't find any hanging corpses in this level.

### Fixed:

> Due to two of the secret sectors being inaccessible, 0% secrets is the maximum score for secrets on this map. Also only 50% items is possible (0% on Ultra-Violence or higher) due to one of the secrets having an item that counts towards the items tally.

I have no idea what the mapper was smoking when adding that berserk secret, so I've removed the berserk as well as the secret special, and also made it impossible to open the secret anymore, since that closet doesn't appear to serve any other purpose.

The BFG secret is trickier. That small sector is slightly recessed into the floor, so it's not possible to trigger it by any means. Tagging the surrounding sector as a secret is also out of the question, because it is a very big sector that also covers other playable areas of the map. To allow players to register this secret, I've added a secret trigger thing and a sector action to activate it as soon as the sector containing the BFG is entered.

> An imp (Thing 100) is located inside a wall at the southwest end of the map and is not accessible by any means aside from the no-clipping cheat.

Fixed by removing said imp from the map.

### Invalid:

> The trap line in the south-east room can't be crossed, the level can't be completed as is. 

I have no idea what it means. There are no triggers to cross in the south-east room, and I can complete the map just fine.

> The player 2 start (Thing 167) has no flags set for any of the three difficulty classes and is marked as multiplayer only, but because of special handling in the engine, it functions normally in the level. 

Not a bug per se, since the player start works normally after all.

### Invalid:

> When exiting the starting room, the southern-most rocket is placed too close to a narrow pillar, and cannot be picked up. 

I am able to pick it up just by walking up to it. It's probably somewhat misplaced though. However, I don't think it should be moved since there is no actual bug.

### Invalid:

> The hanging bodies in the corridor before the red key prevent entering it.

There are actually no hanging bodies in the level.

### Fixed:

> The switch marked with the blue skull symbol (linedef 632) doesn't actually need the blue key to activate. As a result, the blue key is unnecessary.

Fixed by changing the line special accordingly.

### CODE REVIEW

**Comment by Player701** [comment]
Fixed typo in code (double space)

**Comment by Player701** [comment]
Fixed typo in commit message

**Comment by Player701** [comment]
Added another fix (not listed on the wiki) for MAP15. See the original post for details.

**Comment by coelckers** [comment]
I think many of these changes go too far. Please restrict this to changes needed to either prevent locking up the map, render/play glitches and item/kill/secret count. This is not supposed to address poor gameplay choices in the maps.

**Comment by Player701** [comment]
@coelckers Could you please be a little more specific? According to what you're suggesting, the only change that should be removed is the line blocking flags for MAP16. Maybe also the disappearing key on MAP15. Everything else falls under one of the categories you've mentioned:

* MAP02: play glitch (invisible obstacle)
* MAP05: play glitch (duplicate player 2 start, voodoo doll)
* MAP10: kill count
* MAP13: kill count, render glitch (missing texture)
* MAP15: well, you could say it's a kind of a glitch... (since the other two duplicate keys disappear correctly but not the red one)
* MAP23: kill count, secret count
* MAP27: play glitch (switch should obviously require blue key since it's marked with blue skulls just like the three other switches are marked with red and yellow skulls respectively)

I'm currently replaying this PWAD for a second time, maybe I'll find some more glitches that are not mentioned on the wiki. Should be done no later than by tomorrow. Currently on MAP21.

**Comment by coelckers** [comment]
Yes, MAP16 was my primary concern.
The MAP23 change looks a bit large, too, what's up there?

**Comment by Player701** [comment]
@coelckers MAP23 fixes:

1. There is a secret in the beginning that can be opened, but there is no way to access it because the entrance is positioned too high above the floor level of the main room. An arch-vile jump could be the only option, but there are no arch-viles nearby, so this secret cannot be obtained by any means. Therefore, the secret special and the item contained within have been removed so as not to mess up the item/secret counters. Since the secret closet itself doesn't serve any other purpose, it has also been blocked off.
2. There is another secret in the map that is reachable, but the secret sector cannot be triggered because it's too small and is slightly recessed into the floor. To make sure the secret can be obtained, it is now activated via a SecretTrigger, which itself is activated via a sector action (player enters sector).
3. There is an imp in the map that cannot be accessed by any means. It has been removed so as not to mess up the kill counter.

As for MAP16, I will remove the changes since they don't fall under any of your suggested categories. I'm almost finished playing through the WAD for a second time, now on MAP30 (that's one hell of a map BTW). I will update the PR as soon as I've finished playing.

**Comment by Player701** [comment]
Updated the PR, removed MAP16 changes. Just finished my second playthrough, couldn't find any more glitches.

**Comment by coelckers** [comment]
Let's establish some rule for compatibility patching: Only do this if something breaks the map's progression. We should refrain from patching stuff like inaccessible secrets or locked-off monsters if this affects all ports. The purpose of the patcher is not to clean up after sloppy mappers, but to ensure that the map can be played properly.

The *only* relevant fix in here under these conditions is for MAP05 which addresses a genuine playability issue.

**Comment by Player701** [comment]
All right. Should I submit a separate PR for MAP05, or are you going to commit the relevant changes yourself?

**Comment by Player701** [comment]
OK, I can see the MAP05 fix in master, thanks.

**Pull request closed without merging**
