### PR TITLE
Add a cvar to control weapon bobbing while firing

### PR DESCRIPTION
**Pull request by Calinou**
This simulates a feature found in Crispy Doom, which keeps the weapon bobbing while firing. This leads to a "smoother" appearance which may look a bit prettier to some people.

The default value of 0 preserves the old behavior. If you want to enable this feature, values between `0.5` and `1.0` look best from my testing.

[Preview with `wbobfire 0.6`](https://gfycat.com/healthyindeliblehamster)

PS: I haven't added the new menu string yet, should I edit `language.csv` or do something else?

### CODE REVIEW

**Comment by coelckers** [comment]
For the string, language.csv should not be edited. Texts are maintained separately, so just post it here for inclusion in the string table.

Also, have you verified this with Hexen which uses weapon offsets in its attach frames?

**Comment by Calinou** [comment]
@coelckers I just tested it, the feature seems to work well in Hexen.

The display string should probably be `Weapon bob amount while firing`.

**Comment by Calinou** [comment]
Bump :slightly_smiling_face: Is there anything else I need to do to get this in a mergeable state?

**Comment by drfrag666** [comment]
I've merged this for testing. Seems it works well.

**Comment by drfrag666** [comment]
Seems this is okay to merge, i merged it into my master and i've experienced no problems so far. I tried high values and still worked. BTW i see no differences in the code between the initial version and the recent force push.

**Pull request merged**
