### PR TITLE
Increase Vulkan texture slot limit. Fixes https://forum.zdoom.org/vie…

### PR DESCRIPTION
**Pull request by nashmuhandes**
…wtopic.php?f=290&t=70955

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
This will still overflow `bindings` if more textures will be added to a material definition.

**Comment by nashmuhandes** [comment]
> This will still overflow `bindings` if more textures will be added to a material definition.

It was already possible to overflow the texture bindings, regardless of the bug report, even in OpenGL or Vulkan. None of the targets support 16 texture binds so I'm not sure it matters, at least in the context of this specific PR.

IMO that should be tackled in a separate PR. What I provide here is simply to make it so that existing mods that have already been released, to work in both renderers.

(without this fix, said mods would work only in OpenGL but not Vulkan)

**Comment by alexey-lysiuk** [comment]
With 8 more custom textures added to your sample, OpenGL runs fine while Vulkan still crashes.
I'm not against the fix for this issue. I'm against the fix that doesn't fix it completely.

**Comment by nashmuhandes** [comment]
> With 8 more custom textures added to your sample, OpenGL runs fine while Vulkan still crashes.
> I'm not against the fix for this issue. I'm against the fix that doesn't fix it completely.

Are you sure? I am only able to define a maximum of 5 user textures in OpenGL:

```
Material Texture "textures/test.png"
{
	Shader "shaders/test.fp"
	Normal "materials/test_n.png"
	Specular "materials/test_s.png"
	Glossiness 100.0
	SpecularLevel 1.0

	// custom textures
	Texture customTexA "shaders/test1.png"
	Texture customTexB "shaders/test2.png"
	Texture customTexC "shaders/test3.png"
	Texture customTexD "shaders/test4.png"
	Texture customTexE "shaders/test1.png"
	
	// the following causes shader compile errors in both OpenGL and Vulkan
	
	//Texture customTexF "shaders/test2.png"
	//Texture customTexG "shaders/test3.png"
	//Texture customTexH "shaders/test4.png"
}
```

Regardless, I think the texture limit should be enforced at the GLDEF parsing stage (depending on which kind of material render is used; as no materials, spec/norm and PBR all use different amounts of texture slots), this prevents user from using too many texture slots. If you agree with my solution, I will make a separate PR.

**Comment by alexey-lysiuk** [comment]
It was about material definition only, not shader.
```
Material Texture "textures/test.png"
{
	Shader "shaders/test.fp"
	Normal "materials/test_n.png"
	Specular "materials/test_s.png"
	Glossiness 100.0
	SpecularLevel 1.0

	// custom textures
	Texture customTexA "shaders/test1.png"
	Texture customTexB "shaders/test2.png"
	Texture customTexC "shaders/test3.png"
	Texture customTexD "shaders/test4.png"
	
	Texture customTexE "shaders/test1.png"
	Texture customTexF "shaders/test2.png"
	Texture customTexG "shaders/test3.png"
	Texture customTexH "shaders/test4.png"

	Texture customTex1 "shaders/test1.png"
	Texture customTex2 "shaders/test2.png"
	Texture customTex3 "shaders/test3.png"
	Texture customTex4 "shaders/test4.png"
}
```

**Comment by nashmuhandes** [comment]
> It was about material definition only, not shader.
> 
> ```
> Material Texture "textures/test.png"
> {
> 	Shader "shaders/test.fp"
> 	Normal "materials/test_n.png"
> 	Specular "materials/test_s.png"
> 	Glossiness 100.0
> 	SpecularLevel 1.0
> 
> 	// custom textures
> 	Texture customTexA "shaders/test1.png"
> 	Texture customTexB "shaders/test2.png"
> 	Texture customTexC "shaders/test3.png"
> 	Texture customTexD "shaders/test4.png"
> 	
> 	Texture customTexE "shaders/test1.png"
> 	Texture customTexF "shaders/test2.png"
> 	Texture customTexG "shaders/test3.png"
> 	Texture customTexH "shaders/test4.png"
> 
> 	Texture customTex1 "shaders/test1.png"
> 	Texture customTex2 "shaders/test2.png"
> 	Texture customTex3 "shaders/test3.png"
> 	Texture customTex4 "shaders/test4.png"
> }
> ```

Hmm, then, as I suggested, I think it's best to limit the amount of material definitions the user is allowed to do, because shader compilation will fail, anyway.

**Comment by dpjudas** [comment]
If the theoretical overflow limit of 16 is blocking this from getting merged, simply replace all FixedSizeVector with std::vector. I don't think the introduced memory allocations by doing this will affect the performance in any measurable way.

**Comment by alexey-lysiuk** [comment]
I was thinking about the same change, just forgot about this issue. Done in 499df03.

**Comment by nashmuhandes** [comment]
Thank you kindly both @dpjudas and @alexey-lysiuk - it is obvious that this was way beyond my amateur programming skills. :)

**Pull request closed without merging**
