### PR TITLE
Some lens flare effect code from my fork.

### PR DESCRIPTION
**Pull request by usernameak**
This can be in my fork only if you can't remove the first 4 commits. Otherwise, use my lens flare effect code.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Why did you rename it from GZDoom to aengine?

**Comment by MajorCooke** [comment]
You should look into rebasing, that way there's not so many "merge branch" commits polluting the pull request.

**Comment by coelckers** [comment]
If youi clean this up we may talk again but I'm not going to risk merging something where in the first file I can already see something that causes some damage.

**Comment by alexey-lysiuk** [comment]
I gave it a try.

The lens flare looks pretty odd as a permanent post-processing effect IMO.
Is it supposed to be used with a particular HUD mod?

**Comment by usernameak** [comment]
@alexey-lysiuk no, for anything. This is disabled by default in the OpenGL prefs.

**Pull request closed without merging**
