### PR TITLE
Fixed wrong alpha value being applied on sprite shadows in the hardwa…

### PR DESCRIPTION
**Pull request by nashmuhandes**
…re renderer.

### CODE REVIEW

**Comment by nashmuhandes** [comment]
Taking down PR because of Clang build failure

**Comment by alexey-lysiuk** [comment]
I cannot reproduce this compilation failure locally. Will fix build status soon one way or another.

**Comment by alexey-lysiuk** [comment]
It seems like the recent update of continuous integration VM screwed compilation with Clang 6. I disabled it for now.

**Comment by nashmuhandes** [comment]
@alexey-lysiuk oh, thank you. Reopening PR.

**Pull request merged**
