### PR TITLE
Exporting F3DFloor to ZScript [Part 1]

### PR DESCRIPTION
**Pull request by OrdinaryMagician**
Partial export of 3D Floor structures and functions to ZScript. A couple things, such as lightlist_t or extsector_t couldn't be done at the moment, but I'll see if I can get those out later.

Providing two usage examples.

[Example 1](https://github.com/coelckers/gzdoom/files/2342330/ffloor_m.zip): Actor that searches for 3d floors above and below it, listing their heights and model sector indices.

[Example 2](https://github.com/coelckers/gzdoom/files/2342331/ffloor2_m.zip): Actor that attaches itself to the ceiling and follows its movements, including those of 3d floors.

Some notes: LineTracer was edited to provide the commented out ffloor variable now. PlaneRef struct definition in C++ had to be moved out of F3DFloor in order to be accessible to scripting, and two of its members need getters on the ZScript side due to being pointers to TextureID/Color.

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
Sorry about that, I don't know all that much about C++ so I had no idea.

**Comment by alexey-lysiuk** [comment]
In this context it's the same as the following `typedef` in C:
```c
typedef F3DFloor::planeref planeref;
```
Because of the way VM types are defined via preprocessor macros, native counterpart cannot have scope operator `::`. This can be solved easily with C++ type alias or C `typedef`.

**Comment by OrdinaryMagician** [comment]
Closing and rewriting this.

**Comment by OrdinaryMagician** [comment]
oops, renamed the wrong PR

**Pull request closed without merging**
