### PR TITLE
Added direct-native versions of the Shape2D API.

### PR DESCRIPTION
**Pull request by Doom2fan**

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
This is kinda wasteful since these methods will eventually be deprecated they day vector arrays are ever implemented, but I guess it's fine to have it until then.

**Comment by raa-eruanna** [comment]
I redirected this PR to the old master so that at least, if it gets merged, it can be cherry-picked back to the master.

**Comment by MajorCooke** [comment]
This submission must be redone in order for it to be merged into QZDoom unfortunately. The file is in a different location and it [cannot be properly placed](https://puu.sh/EugkR/1b0011b82e.png).

**Comment by Doom2fan** [comment]
Done. I would also do the transform stuff, but I don't have any code that uses those functions.

**Comment by Doom2fan** [comment]
Alright, added direct-native versions of the linear transform API. Had to make my own test for it, bleh.

**Comment by MajorCooke** [comment]
Merged with QZDoom.

**Pull request merged**
