### PR TITLE
add service interface

### PR DESCRIPTION
**Pull request by mmaulwurff**
This add interface for cross-mod communication. This is a means to make optional mod dependencies.

Service class provides a single virtual method, String get(String request), which can be overridden in Service implementation. Then, clients will be able to find that service via ServiceIterator.

As this addition doesn't require any native code, here is the added functionality as a separate file(zscript.service.txt). Also, example service implementations and client are provided for testing. How to test:
`gzdoom -file zscript.service.txt zscript.client.txt zscript.service-impl.txt +map map01 +summon Client`
prints the following:
```
Who are you, Imp?
Hi, Imp!
Go to heck, Imp.
```

If the service implementation is not loaded:
`gzdoom -file zscript.service.txt zscript.client.txt +map map01 +summon Client`
It will print
`Service not found. Okay then.`

Here, client has an optional dependency on Greeting server. It can compile and work both with and without server.

### CODE REVIEW

**Comment by MajorCooke** [comment]
Where's the `#include`, or is that not needed?

**Comment by mmaulwurff** [comment]
You mean in the supplied files? It's not needed, as technically all three of them are mods by themselves, loaded separately with `-file` command line parameter.

**Comment by MajorCooke** [comment]
This setup sounds pretty confusing and convoluted...

**Comment by mmaulwurff** [comment]
Just to clarify, the files that are attached to this PR are purely for demonstration purposes, to check things out before this is merged (if at all):

- zscript.service.txt basically contains PR contents. That would go into gzdoom.pk3.
- zscript.service-impl.txt is an example of service definition.
- zscript.client.txt is an example of connecting to a service.

**Comment by MajorCooke** [comment]
Oh I know that. What I'm confused about is how `service.zs` doesn't have any sort of `#include` for it unless ZScript internally already includes them?

**Comment by MajorCooke** [comment]
Thank you. Now I can merge this into QZDoom for testing.

**Comment by edward-san** [comment]
Interesting. How does this approach cope with multiplayer mode, where clients may have different loaded mods for various purposes, like graphics and etc.?

**Comment by mmaulwurff** [comment]
This is an alternative to cross-mod communication via EventHandler.SendNetworkEvent. If the data that is passed between mods affects the game, mod authors have to use EventHandler.SendNetworkEvent.

**Comment by coelckers** [comment]
So in other words: This completely bypasses the network barrier?
You wouldn't expect modders to cluelessly use this and make their mods incompatible with multiplayer and demo recording?

Sorry, but we set it up this way so that modders won't accidentally create such mods - of course nobody will ever stop them from deliberately screwing things up - but I don't think it's a good idea to provide ready-made solutions to do such things.

**Comment by mmaulwurff** [comment]
So, if understand right, this thing is only acceptable if it's in UI scope completely?

**Comment by coelckers** [comment]
If it can cross the network barrier it will completely circumvent all the protections we added to the engine to ensure that modders won't accidentally create mods that break demos and multiplayer, so yes, it should be restricted to one side of it.

**Comment by Doom2fan** [comment]
In my opinion, adding a naïve restriction like that would severely limit the usefulness of the feature. Why not add proper scoping to it instead? Of course, that would be more work, but then the scoping system would be respected, and the feature would keep all of its usefulness.

**Comment by MajorCooke** [comment]
Can't it be kept to a play scope?

**Comment by mmaulwurff** [comment]
@Doom2fan, what do you mean by proper scoping? Play instead of default data?

**Comment by MajorCooke** [comment]
To me that makes the most sense. I would heavily use this for play activity, such as a spawner seeking other spawners and using dictionaries to pass around the information for setting up important data.

**Comment by madame-rachelle** [comment]
There could be one version for play scope and one version for UI scope. That being said, if you have to choose one, play scope makes the most sense for an addition like this - addons ultimately for the most part have the goal of modifying gameplay, rarely just the UI.

**Comment by MajorCooke** [comment]
Agreed with Rachael, because there have been some things I'd like to check on the UI side such as modifying a status bar depending on mods loaded.

**Comment by mmaulwurff** [comment]
Honestly, I don't see how this introduces a _new_ problem.

S1. Players involved in a netgame can load different sets of mods. Suppose that Player1 has a mod that Player2 doesn't have. Then if this mod changes the game, players will desync. I just checked this, it works like this. There is no protection from this situation besides "out of sync with..." message.

S2. If players have the same service-client combination, then service and client will behave the same, both service-client pairs working on their own side of network barrier. They don't "bypass the network barrier".

S3. If players have different service-client combinations:
- servers cannot cause different changes in the game because they are data-scoped.
- clients may behave differently depending on the supplied data from server (or lack of such information). This is an issue, of course, but it's the same issue that is described in S1, which already happens without Services.

If I'm wrong, please correct me. I feel that I don't understand something here. If you have time, please explain. I also will be glad if I'm pointed to a source where I can read on the subject.

**Comment by mmaulwurff** [comment]
To prevent scope violation, marked Get() function as _play_. Also added UiGet() (ui-scoped) to allow using servers in ui scope.

**Comment by mmaulwurff** [comment]
If this needs a use case for being merged, here is one.

There is an addon, [Nomina](https://forum.zdoom.org/viewtopic.php?f=46&t=68528#p1150645), that provides custom names to mods that don't define actor tags. There are two mods that display weapon names: [War Trophies](https://forum.zdoom.org/viewtopic.php?f=43&t=67054#p1132997) and [Weapon Menu](https://forum.zdoom.org/viewtopic.php?t=59498#p1040474). They both cannot just take actor tag, because they read the read-only default actors (in case of Weapon menu, in future version). So, they could utilize some kind of information service to query custom weapon names. If Service Interface is added to the engine, then Nomina can provide such a service, and two client mods could poll it. And all three mods will remain loadable by their own.

**Comment by MajorCooke** [comment]
Can I also use this to provide a signal that health values have changed? if there's one thing I'd like, one of the mods I have has health multipliers the moment the actor spawns based on cvars. I change both the SpawnHealth and actor Health variables, but GetSpawnHealth() always returns the default variant, even if SpawnHealth is perfectly accessible.

So I'd like to supply a means of telling TargetSpy and co that they have different health values so it doesn't show up as overhealed.

**Comment by mmaulwurff** [comment]
Yes, your mod could add a Service that would return proper spawn health for a class. Target Spy then could add code that checks for Service existence and asks it for health value.

**Comment by MajorCooke** [comment]
I'd like to see if this could be added as well. While I've only done a small test of it so far, it's actually quite useful.

**Comment by MajorCooke** [comment]
Can you fix the merge conflict please?

**Comment by mmaulwurff** [comment]
Done.

**Comment by MajorCooke** [comment]
This submission is ready. I wish I could post a review but I don't see any way to currently...

**Pull request merged**
