### PR TITLE
Add Polyobj_StopSound special

### PR DESCRIPTION
**Pull request by mykola-ambar**
This PR adds Polyobj_StopSound special that stops the sound being played by the polyobject.

Related ACC pull request: https://github.com/rheit/acc/pull/86

### CODE REVIEW

**Comment by coelckers** [comment]
Out of curiosity, what's the use case here?

**Comment by mykola-ambar** [comment]
The use case is pretty convoluted, but bear with me.

I'm working on a mod that uses ZScript to give polyobject doors a more Wolf-3D like behavior ([I posted the code here if want to take a look](https://forum.zdoom.org/viewtopic.php?f=105&t=69999)). In short, it substitutes Polyobj_DoorSlide activations with two separate Polyobj_MoveTo activations, one for when the door opens and one for when it closes. 

The problem is, it has to play the correct sound when closing the door.

Prior to 4.5, Polyobj_MoveTo did not play any sound at all. The workaround was to play the door sounds in the surrounding sector using StartSoundSequenceID, which works well, and can play the correct sound for closing the door. However, now that Polyobj_MoveTo actually plays a sound, it always plays the door opening sound, even when the door is actually closing.

Adding Polyobj_StopSound would make it possible to stop the undesired door sound from being played by Polyobj_MoveTo by calling it right after.


My particular use case is very niche, but I can see it being useful for quietly moving noisy polyobjects without alerting the player, maybe for a trap or something.

**Comment by madame-rachelle** [comment]
@coelckers This pull request effectively stops other ACC pull requests from being queued, useful or not, due to the merge conflicts that it would cause. Are there any other issues preventing this from being merged?

**Comment by madame-rachelle** [comment]
Well this has now gone stale, at least until the ACC PR is updated again.

**Comment by mykola-ambar** [comment]
I will resolve the ACC pull request conflicts tomorrow.

**Comment by mykola-ambar** [comment]
Resolved.

**Comment by Doom2fan** [comment]
The code looks good to me, and I see no reason not to merge it - any opposition?

**Comment by madame-rachelle** [comment]
> 
> 
> The code looks good to me, and I see no reason not to merge it - any opposition?

None here.

**Comment by Doom2fan** [comment]
I've merged this. The corresponding ACC PR needs to be merged by someone else, as I don't have commit access to it.

**Pull request merged**
