### PR TITLE
String Is* helper functions

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
Now with less stupidity (hopefully).
I don't know C++, so had no idea about cctype

### CODE REVIEW

**Comment by coelckers** [comment]
Sorry, still not usable. The entire family of 'is...' functions has one huge problem: It works on unsigned values but the input is an int, so that any international character will lead to undefined behavior because when expanded from a signed char, will be negative.

The least you need to do is cast the input to these functions.

**Comment by ZippeyKeys12** [comment]
There's international character support in GZDoom!?

**Comment by ZippeyKeys12** [comment]
I think I fixed it?
I cast it into a unsigned char now.

**Comment by coelckers** [comment]
The main problem here is that string analysis by character is inherently not unicode aware - so adding this would become a major feature blocker.
In fact, even reading texts character by character should be avoided if you want to play it safe.

**Pull request closed without merging**
