### PR TITLE
NoiseMarkSector optimization

### PR DESCRIPTION
**Pull request by MekBoss**

### CODE REVIEW

**Comment by Doom2fan** [comment]
Slow down. You're making way too many pull requests in way too little time.
Additionally, you're making a massive number of commits with the exact same name. This and the massive amount of commits would make the repo a massive pain in the ass to bisect, or even navigate.

**Comment by coelckers** [comment]
At least add the name of the function that got changed to the commit message!
The PR's name does not end in the repo - it's the commit message and since all these commits do not say what precisely they do, we cannot use them.

Also please think a bit about how critical a function is. Some are only called very infrequently and I'm going to reject all changes to those on sight because there is no point changing such code for the sake of changing it.

And last, but not least, shoving that pattern of 'x * fabs(x)' everywhere clearly shows that no deeper analysis goes in here, it's not needed in all those places. 

And have you made any performance tests? After all, this is what you are after, so without giving some evidence of improvement I'd rather err on the side of caution, because if it ain't broke, don't fix it!

**Comment by MekBoss** [comment]
> And last, but not least, shoving that pattern of 'x * fabs(x)' everywhere clearly shows that no deeper analysis goes in here, it's not needed in all those places.

Is it? Fabs applies to function arguments, which can be negative. Because of the typo for example. 
And since function need to compare squared distance (which cannot be negative by definition of the square function, it always return positive numbers) to squared argument, which should match original sign of a number for correct result of a function.
And negative number multiplied by negative number return positive number.
And expecting behavior, in case of negative function argument, is return false/whatever is under "actual distance to 'something' is greater than current argument" conditional statement.

Reason, inequality saves after addition/subtraction/multiplying by number not equal to zero/rising to any power not equal to zero both sides of inequality. Proof, pick some "x" and "y" which is a two non equal numbers , say that
x < y
than
x^2 < y^2
Why is it so is....too hard question to answer, really.
Also
x - x < y - x == 0 < y-x
which after squaring gives
0^2 = 0
(y-x)^2 = y^2-2xy+x^2 > 0
if "y" really bigger than "x"

**Comment by drfrag666** [comment]
Why don't you put all the commits in a single PR? You could create another branch and cherry-pick the commits one by one changing their messages.

**Comment by drfrag666** [comment]
BTW i've tested your old PR in nuts.wad and i don't notice any performance difference, QZDoom devbuild from may 17.

**Comment by MekBoss** [comment]
> Why don't you put all the commits in a single PR? You could create another branch and cherry-pick the commits one by one changing their messages.

I misread/misunderstood Graf when he said "create separate commits for each changes". I will do it in the next few days.


> BTW i've tested your old PR in nuts.wad and i don't notice any performance difference, QZDoom devbuild from may 17. With stat think it's around 40 ms with peaks of around 50, same as in GZDoom.

With "default" Doom gameplay, where you pick chainsaw and starts making basic jigsaw puzzles from demons, performance increasing is minimal. It only slightly noticeable on maps with enormous amount of cacodemons/flying monsters, like okuplok. But only "slightly".
It mostly fix/clear a little bit more advanced problems with performance. Originally I started it after I seen how someone complain that A_AlertMonsters(500), called for 50 times per tick, (laser beam alerters or something like that) cause more slowdown than simple A_AlertMonsters(). And when I check code for it I saw that it uses Distance2D to figure out is actor inside "alert" radius or no. Then I checked maybe there are more places where its possible to change Distance2/3D to Distance2/3DSquared and thats how it ended up here.

**Comment by drfrag666** [comment]
I was wrong, seems what Graf wants is to have the changes in multiple PRs. But those changes are all related, it's the same thing. He wants to apply them separately. You can do soft resets and commit again in the same branches then.
But of those what are the important changes? I see no performance difference. Monsters are alerted only once.

**Pull request closed without merging**
