### PR TITLE
Add keybindings presets

### PR DESCRIPTION
**Pull request by drfrag666**
Strings:
OPTVAL_CLASSICZ					= "Classic ZDoom";
OPTVAL_MODERN					= "Modern (WASD)";
OPTVAL_MODERNLEFT				= "Modern (Keypad)";

### CODE REVIEW

**Comment by drfrag666** [comment]
This was affected by the recent master reset and the mini-refactor coming afterwards so i rebased it a few days ago.

**Comment by MajorCooke** [comment]
Just to check, did you have anything else for this or is it good for merging into QZDoom for testing?

**Comment by drfrag666** [comment]
To see if people don't like the presets? It's been in LZDoom for a long time (with the old code in releases and the new code in modern devbuilds) and no one has complained. Actually i was about to close this due to lack of interest. Now i think it would be better to keep only two presets (classic amd modern WASD). Graf said the wanted three and i have four in LZDoom. People didn't agree on presets and i don't really care if this is merged or not.

**Comment by coelckers** [comment]
You missed one of the needed texts in the list

**Comment by drfrag666** [comment]
True, i've just added it to the fist post.

**Pull request merged**
