### PR TITLE
Added exact floating point comparison opcodes

### PR DESCRIPTION
**Pull request by Gutawer**
The CMP_APPROX flag still needs to be accounted for in these.

### CODE REVIEW

**Comment by coelckers** [comment]
That should also be done at compile time. Don't forget: You want to create assembly code for one specific instruction. There's absolutely no need to create the exact same code for all variations of a single opcode. Whatever can be used at compile time to choose different code generation, should.

It should look like this:

if (a & CMP_CHECK)
{
     if (a & CMP_APPROX)
    {
         // generate code
    }
    else
    {
         // generate code
    }
}
else
{
     if (a & CMP_APPROX)
    {
         // generate code
    }
    else
    {
         // generate code
    }
}

Actually, the code that will be generated for a branch instruction evaluating all static information at run time is approximately the same quality as the code interpreting it, resulting in no performance gain. The entire point of a JIT is to eliminate this evaluation of constant information, this is where most performance is gained.

**Comment by Gutawer** [comment]
I'll keep that in mind. I'll also change the other commit to do compile time code selection, I just never thought of that for some reason.

**Comment by Gutawer** [comment]
@coelckers - How do you recommend I should test the CMP_APPROX opcodes that aren't emitted from ~==? As far as I know, there are no operators apart from ~== that even emit that flag.

**Comment by coelckers** [comment]
CMP_APPROX only gets used for floating point comparisons. In all other cases the flag has no meaning and can be ignored,

The only other place where the ==~ operator has an effect is string comparisons, but for the CMPS opcode it may make sense to just call a generic function for it - this clearly is not a place where performance is critical.

**Comment by coelckers** [comment]
Correct, those are currently not emitted and never will because they make no logical sense. Two numbers can be approximately equal, but there's no sane definition of a number being approximately less than the other. Either it is less or it isn't, but never 'maybe'.

**Pull request merged**
