### PR TITLE
Overlay extension

### PR DESCRIPTION
**Pull request by MajorCooke**
This is basically the software only side of https://github.com/rheit/zdoom/pull/969

I've tried to get it working on the openGL side of things but alas, I've failed. All I can offer is the mainframe code which takes care of everything else.

### CODE REVIEW

**Comment by jewalky** [comment]
I tried to merge this into the latest GZDoom master, and realized that there's a type conflict between GZDoom and QZDoom, in visstyle_t RenderStyle is supposed to be an int (for ZScript compatibility), while QZDoom has it as FRenderStyle (and this PR expects it to be that as well).

@Graf: what to do here?

**Comment by coelckers** [comment]
Make the change for QZDoom so that it will get into ZDoom once that can be merged.

**Comment by MajorCooke** [comment]
It's already in QZDoom.

**Comment by coelckers** [comment]
I meant the GL implementation.

**Pull request closed without merging**
