### PR TITLE
Manage Shape2D vertex buffers lifetime with RefCountedPtr

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
What's included:
- #1446 squashed to a single commit
- `RefCountedPtr` follows rule of five
- `RefCountedBase` without virtual destructor
- `RefCountedPtr` manages 2D shape buffer infos

### CODE REVIEW

**Review by coelckers — COMMENTED** [review]
Looking good, overall.
The one thing I haven't checked yet is when the 2D data goes out of scope. With a hardware buffer in the game it needs to stick around until the scene is fully rendered, otherwise it may cause problems on Vulkan. On OpenGL the driver will keep the buffer until it is done.

**Comment by alexey-lysiuk** [comment]
Here is the callstack when destruction of vertex buffer happens
```
RefCountedPtr<DShape2DBufferInfo>::~RefCountedPtr<DShape2DBufferInfo>()
F2DDrawer::RenderCommand::~RenderCommand()
F2DDrawer::RenderCommand::`scalar deleting destructor'(unsigned int)
TArray<F2DDrawer::RenderCommand,F2DDrawer::RenderCommand>::DoDelete(unsigned int first, unsigned int last)
TArray<F2DDrawer::RenderCommand,F2DDrawer::RenderCommand>::Clear()
F2DDrawer::Clear()
VulkanFrameBuffer::Update()
End2DAndUpdate()
D_Display()
```
If we need to free it after `VulkanFrameBuffer::WaitForCommands(true)` completion then the initial solution is wrong.
https://github.com/coelckers/gzdoom/blob/f89e6950c39ff469570ac608bfc91c05efee1874/src/common/rendering/vulkan/system/vk_framebuffer.cpp#L198-L207

**Comment by coelckers** [comment]
That's too early. We need something else to hold the buffers until a scene has definitely been presented. Only then it is safe to delete the buffers on Vulkan.

**Comment by alexey-lysiuk** [comment]
[Something like this?](https://github.com/coelckers/gzdoom/pull/1447/commits/facb2294143b97c6caff666a5107f34906df066a)

**Pull request merged**
