### PR TITLE
fix Dictionary and DictionaryIterator memory leaks

### PR DESCRIPTION
**Pull request by mmaulwurff**
The gist of the commit is that Dictionary and DictionaryIterator now inherit from DObject. Serialization is moved from struct code to class.

Notes:

1. Savegame version is bumped, because Dictionary serialization is switched from struct to class.
2. I'm not sure about GC::WriteBarrier. I believe it's needed in DictionaryIterator::init because Dictionary can be potentially be marked for removal. Maybe it's needed in other places, maybe it's not needed at all.
3. Added some documentation to ZScript Dictionary and DictionaryIterator classes.
4. Serialization of DictionaryIterator is explicitly disabled.

Test file:
[zscript.txt](https://github.com/coelckers/gzdoom/files/4303521/zscript.txt)

Run it like this:
```
gzdoom -file zscript.txt +map map01 +"stat gc" +summon DictionaryTest
```

Without the fix, the allocated memory continues to grow even after GC hits the threshold, and the threshold is increased every time it's reached.
With the fix, GC collects allocated memory and stays capped (54 544 KB in my case).

### CODE REVIEW

**Comment by coelckers** [comment]
Two things: 

1. Please avoid multiple inheritance from container classes, these have already caused some non-obvious problems in the past.
2. If you need to make a savegame version bump, please try to keep loading of savegames operational. It#s annoying if a feature like this causes old savegames to become incompatible.

**Comment by mmaulwurff** [comment]
> 2. try to keep loading of savegames operational

Is it acceptable to just bring back MINSAVEVER? It will cause VM abort (NULL access attempt) for those users who have serialized Dictionary in their saves. But I don't know any mods that have Dictionaries as non-transient class members at the moment. I think maybe it isn't worthwhile adding compatibility code for those potential users.

**Comment by coelckers** [comment]
Yes, that would be acceptable. Just allow old savegames to be loaded as long as they don't contain dictionaries.

**Comment by mmaulwurff** [comment]
Done.

**Comment by mmaulwurff** [comment]
Added test file, see https://github.com/coelckers/gzdoom/pull/1031#issue-371493213

**Pull request merged**
