### PR TITLE
Fix bounce state not entering when hit from top

### PR DESCRIPTION
**Pull request by Cacodemon345**
Fixes this:https://forum.zdoom.org/viewtopic.php?f=2&t=61786&p=1070695#p1070103

### CODE REVIEW

**Comment by Cacodemon345** [comment]
I turned the previous PR's commit history into a mess. This should work properly now.

**Comment by OrdinaryMagician** [comment]
Confirmed working with the test wad I submitted in the bug report.

**Comment by Cacodemon345** [comment]
Does it work properly with Heretic? I don't really own it, but I would want to check if it breaks Heretic projectiles.

**Comment by OrdinaryMagician** [comment]
They're unaffected, since they don't bounce on actors.

**Comment by Cacodemon345** [comment]
I am considering putting the if block statement before the ontop check.

**Comment by Cacodemon345** [comment]
Ok then.

**Pull request merged**
