### PR TITLE
Service Expansion - More virtuals

### PR DESCRIPTION
**Pull request by MajorCooke**
Added (UI)GetInt/Double/Object virtuals to Service and expanded their parameters.

Several reasons for this:
- If Service is being used often, these virtuals can be used to reduce the number of translations from strings to numbers.
- Secures against potential typing errors if returning just numbers (anyone remember 0.L?) to prevent bad number translations
- When used to construct functions (see example below), the extra parameters are provided to reduce function calls.

-----
EXAMPLE

Currently I'm working on a global damage system where the damage is set up and calculated before a player is damaged without needing to override the player actor's DamageMobj function. For that, the Service class is set up to construct a damage function, and return the result.

```
// Begin call and set up the service provider, in order. 
serv.Get("DamageMobj", DamageType); // Sets it up and gives the damage type.
serv.GetObject("Pointers", target, src, inf); // Passes in the 3 essential pointers.
serv.GetDouble("Angle", dmgAngle); // Passes in the angle
return serv.GetInt("Result", damage, flags); // Passes in the damage & flags. Then gets the result.
```

### CODE REVIEW

**Comment by MajorCooke** [comment]
An expanded example to go with the one in the description:

```
struct DmgServInfo play
{
	Actor trg, src, inf;
	int damage, flags;
	Name type;
	double angle;
	
	void Reset(Name dmgtype = 'None')
	{
		src = inf = null;
		damage = flags = 0;
		type = dmgtype;
		angle = 0;
	}
}

Class DmgService : Service
{
	private DmgServInfo DSI;
	
	override String Get(String request, String str1, String str2, String str3)
	{
		Name req = request;
		Switch(req)
		{
			Case 'DamageMobj':	DSI.Reset(str1);	break;
		}
		return "";
	}
	
	override Int GetInt(String request, int num1, int num2, int num3)
	{
		Name req = request;
		if (req == 'result')
		{
			DSI.damage = num1;
			DSI.flags = num2;
			return CalculateDamage();
		}
		return -1;
	}

	override Object GetObject(String request, Object ob1, Object ob2, Object ob3)
	{
		Name req = request;
		if (req == 'Pointers')
		{
			DSI.trg = Actor(ob1);
			DSI.src = Actor(ob2);
			DSI.inf = Actor(ob3);
		}
		return null;
	}
	
	override double GetDouble(String request, double num1, double num2, double num3)
	{
		Name req = request;
		if (req == 'angle')
			DSI.angle = num1;
			
		return 0;
	}
	
	private int CalculateDamage()
	{
		// Do calculations here.
		return 0;
	}
}```

**Review by alexey-lysiuk — COMMENTED** [review]
Modification of existing virtual functions' signatures isn't the best idea. I would prefer to deprecate `Get()` / `UiGet()`, and add `GetString()` / `GetUIString()` methods. `UiGet()` was a poor name for a function anyway. But it's a minor thing.

The main issue is not future-proof extension of the interface. How does type of extra parameters relate to the type of return value?
For example, I want to pass an integer and a string, and to get an object as result. The new interface won't help me at all.

As long as ZScript has no internal variant type, the better option would be to have identical parameters list for all 8 functions: request `string`, `int`, `double`, `string`, and `object`.

**Comment by MajorCooke** [comment]
> Modification of existing virtual functions' signatures isn't the best idea. I would prefer to deprecate `Get()` / `UiGet()`, and add `GetString()` / `GetUIString()` methods. `UiGet()` was a poor name for a function anyway. But it's a minor thing.

Actually Graf told me to expand upon AbsorbDamage when I modified that for powerups/armor so that's what I'm doing here. I'm not going to deprecate that.

> The main issue is not future-proof extension of the interface. How does type of extra parameters relate to the type of return value?
> For example, I want to pass an integer and a string, and to get an object as result. The new interface won't help me at all.

Easy.
```
serv.GetInt("input", <someint>);
Object ob = serv.GetObject("output");```

Then just make sure the functions are set up appropriately for it.
 
> As long as ZScript has no internal variant type, the better option would be to have identical parameters list for all 8 functions: request `string`, `int`, `double`, `string`, and `object`.

Explain more please.

**Comment by alexey-lysiuk** [comment]
Sorry, but after reading your comments I lost interest in this thing. Literally, I'm too tired to argue. I hope someone else will review it.

**Comment by MajorCooke** [comment]
If Graf wants me to change the name of the function, I will. But I personally see absolutely no reason to, [especially as I learned they could be expanded without repercussion.](https://forum.zdoom.org/viewtopic.php?f=18&t=63551&p=1090389)

**Comment by MajorCooke** [comment]
Alright, I'll change the name and deprecate the old one. However, I don't know what you want about the rest of your request. I need more information.

**Comment by mmaulwurff** [comment]
I think mental wants to cover maximal number of use cases by making functions like these:

```
String getString(String stringArg = "", int intArg = 0, double doubleArg = 0, Object objectArg = null) { return ""; }
int getInt(String stringArg = "", int intArg = 0, double doubleArg = 0, Object objectArg = null) { return 0; }
double getDouble(String stringArg = "", int intArg = 0, double doubleArg = 0, Object objectArg = null) { return 0; }
Object getObject(String stringArg = "", int intArg = 0, double doubleArg = 0, Object objectArg = null) { return null; }
```
(and the same for UI functions. Maybe UI getObject should return readonly<Object>)

So you have many combinations, like, maybe you want to get object with int argument, or string with object argument, etc. This doesn't cover cases when you want to have more than one argument of a single type, but I believe such cases are expected to be rare. One can always encode them in a string.

I think mental's suggestion makes sense.

**Comment by MajorCooke** [comment]
Readonly for the UI version? Why? It can't be changed at any rate, far as I'm aware. The whole point is to receive a copy so that doesn't make much sense.

Everything else though does. I'll see if Mental will reply again. If not after a few days, I'll just give it a shot.

**Comment by mmaulwurff** [comment]
> It can't be changed at any rate, far as I'm aware.
Oh, good.

**Comment by alexey-lysiuk** [comment]
Yes, the idea was one argument of each type. The first argument, a request `string`, is missing from definitions by @mmaulwurff though.
```
string GetString(string request, string stringArg = "", int intArg = 0, double doubleArg = 0, Object objectArg = null) { return ""; }
```

I’m against putting a noun at the beginning of function names. We have a few such names for historical reasons, but I think we don’t need more of them. In other words, `GetUIString` (or `GetStringUI` maybe) is better than `UIGetString`. The latter is more like a class name.

**Comment by MajorCooke** [comment]
Ah I see. Okay. I'll open a new pull request so the commits are clean.

**Comment by MajorCooke** [comment]
https://github.com/coelckers/gzdoom/pull/1442

**Pull request closed without merging**
