### PR TITLE
Update GME up to 0.6.2 version

### PR DESCRIPTION
**Pull request by Wohlstand**
Contains a massive set of bug-fixes and the updated YM2612 emulator.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Just now woke up...
Gonna to analyze the stuff and will fix this...

**Comment by Wohlstand** [comment]
Okay, just now I have sent some update of CMake where I have researched and backported GZDoom-specific changes of CMake scripts, will wait when the stuff will be built, otherwise I'll fix if build will be broken...

**Comment by Wohlstand** [comment]
Oh, damn! MSVC build sucks: million of warnings and errors... I think it's need to polish the GME itself on some cases...

**Comment by Wohlstand** [comment]
On the case of one random Linux build I see it lacks the Zlib:
https://travis-ci.org/coelckers/gzdoom/jobs/444393094
GME needs the ZLib to be decompresss VGZ files...

**Comment by Wohlstand** [comment]
So, Linux & macOS are fixed now, but MSVC is still feel like a shit...

**Comment by Wohlstand** [comment]
Okay, to fix MSVC build I have found one weird macro that was commented out originally, which I have commented back.

I also have added the bunch of MSVC warnings disabler:
https://github.com/WohlSoft/AudioCodecs/blob/master/libgme/CMakeLists.txt#L26-L28
On side of my AudioCodecs pack I have wrote my own CMake build from scratch without of using any existing one.

**Comment by Wohlstand** [comment]
I think, it's ready now. If something needed also, tell me to fix/improve that.

**Comment by coelckers** [comment]
Merged manually

**Comment by Wohlstand** [comment]
Nice! :3
But the question: did you changed something or you have placed it as-is? (with only changes to resolve some conflicts)

**Comment by coelckers** [comment]
I merged manually so that I could run a few tests before committing. I left it unchanged.

**Comment by Wohlstand** [comment]
Ok, that fine :fox:
I only wanted to be sure I'll don't miss up some important changes for next time update.  :wink:

**Pull request closed without merging**
