### PR TITLE
Add WeaponScaleX and WeaponScaleY properties for adjusting weapon PSprite scale

### PR DESCRIPTION
**Pull request by XaserAcheron**
This PR adds a couple of new properties to the Weapon class for adjusting the scale of its PSprites. Finally. :P

Some notes:
- The default scale is (1.0, 1.2), i.e. Doom's native aspect ratio. Folks who want square pixels can now set this to (1.0, 1.0) and get instant results.
- The X scaling is relative to the center of the screen.
- The Y scaling is relative to the bottom of the screen, for user-friendliness.
- Scaling applies equally to all PSprites on the weapon (including flash state, custom psprites, etc.).
- Internally, this feature uses a new `baseScale` var on the PSprite class that's independent of the `scale` var that's manipulated by `A_OverlayScale` and company, so the two features ought to play nicely with each other.
- Works in both the Software and Hardware renderers (i.e. all `vid_rendermode`s).

Pre-emptive answers to "Hey, can't you already do this with [feature x]?":
- Doing this in TEXTURES is extremely cumbersome.
- `A_OverlayScale` works in a pinch, but it's Hardware-renderer-only and takes a bit of setup and fiddling to get the right results.
- Having a quick way to do this that Just Works(tm) is Really Really Damn User-Friendly.

cc @MajorCooke on this -- this all oughta play nicely with the existing `A_Overlay*` functions, but I don't have a ton of experience with those so it'd be good to have an extra pair of eyes here. I've done some quick tests with Painslayer just to make sure I didn't break anything, but that's about the extent of my testing there.

### CODE REVIEW

**Comment by MajorCooke** [comment]
I'll do you a favor and toss it into QZDoom. Sound good? Then everyone can test it out.

**Comment by XaserAcheron** [comment]
Thanks! Probably a good way to go about it -- mainly I'm wondering how the scaling affects how A_OverlayPivot works, i.e. do the coordinates still make logical sense or do they get fudged up? If it sucks, then we can probably factor in baseScale and fix it up.

**Comment by MajorCooke** [comment]
[Here's a test package](https://drive.google.com/file/d/181QeeogjZsFRiueeuwHprlRAsNoN9c12/view?usp=sharing) that you can use to fiddle around with, which uses all the overlay features. Simply load it up and it'll automatically start using scale, rotation, vertex manipulation, and so on.

**Comment by MajorCooke** [comment]
I've done a bit of experimenting, doesn't seem to be negatively impacting anything so far. I'll try a few more things to see if I can break it - if it survives, this gets my stamp of approval.

Sorry for taking so long. Holidays do that sometimes...

**Comment by MajorCooke** [comment]
@XaserAcheron Did some more testing to find out WeaponScale doesn't propagate to all PSprites belonging to the weapon. The reason for this happening is because it's not accessing the one who spawned it (albeit you did so for the reset function), but a quick reminder: PSprites can come from inventory and/or the player itself.

But if this was intended behavior, then its working fine.

**Comment by XaserAcheron** [comment]
Sorry, been busy over the holidays, but yeah, it's meant to apply to all psprites -- I'll patch it up vaguely-soonish.

**Comment by XaserAcheron** [comment]
Took me a bit to get back to it, but just pushed a commit that applies it to all weapon PSprites, both Flash and custom things created by A_Overlay. Should be 100% saner now. :P

**Pull request merged**
