### PR TITLE
- add support for SIGIL as an expansion for Ultimate Doom

### PR DESCRIPTION
**Pull request by madame-rachelle**
I created a forum thread for this, here:
https://forum.zdoom.org/viewtopic.php?f=59&t=64880

### CODE REVIEW

**Comment by coelckers** [comment]
I'm not sure about the autoload section. Should this be a sub-entry of ultimate or be parallel to it?

**Comment by madame-rachelle** [comment]
> 
> 
> I'm not sure about the autoload section. Should this be a sub-entry of ultimate or be parallel to it?

You might be right that it would be better to make it parallel. I will make that change.

**Comment by Nemrtvi** [comment]
Just to nitpick: “Sigil of Baphomet” is written with the word “of” in lowercase. Looks off otherwise. All in all, I’m for this change, if only to make translations easier/possible at all.

**Comment by madame-rachelle** [comment]
Yes - I agree there, but right now this submission's prospects are fairly unlikely. If Graf gives any more of an indication that he actually wants to merge this, I'll do another force-push to change it, but otherwise this feature is pretty much left for dead for me. I already have developed an alternative to this submission and am just waiting for its resolution one way or the other.

**Pull request closed without merging**
