### PR TITLE
CanCrossLine Virtual

### PR DESCRIPTION
**Pull request by MajorCooke**
Added CanCrossLine virtual.

- Allows actors to determine what lines can be crossed, after the original line checks are handled.

### CODE REVIEW

**Comment by Doom2fan** [comment]
I'm not sure this is a good idea. It adds a VM function retrieval, a virtual override check and a branch, and that's a fairly performance-critical section of the code.
This could cause very serious performance issues and needs some very careful profiling.

**Comment by MajorCooke** [comment]
Fair enough. Unfortunately I don't know how to do profiling.

**Comment by madame-rachelle** [comment]
I'm not merging this until @coelckers has a look at it.

**Comment by MajorCooke** [comment]
That's fair.

**Comment by coelckers** [comment]
I agree with @Doom2fan  on all accounts here. If you really want this, please take a few pointers from CanCollideWith how the really expensive actions can be avoided - this one always takes the most costly path imaginable.

I am also not convinced that this by itself will work - there's other places in the engine as well that deal with blocking lines.

**Comment by MajorCooke** [comment]
Alright, I'm moving discussion to [here.](https://forum.zdoom.org/viewtopic.php?f=59&t=69664&p=1166932#p1166932)

**Pull request closed without merging**
