### PR TITLE
Dynamic number of models per actor

### PR DESCRIPTION
**Pull request by Chernoskill**
Actors can now have a dynamic ("unlimited") number of models associated with them, instead of the old hard limit of four. 
Tested with:
Actors with more than four models, multiple surfaceskins per model, and animations.
Animated voxel actors
MODELDEF entries with FrameIndex lines which refer to model indices equal to or higher than the amount of models for that actor (ensured compatibility with mods that do this, since it didn't cause (but was supposed to) a critical error on startup.

If anyone wants to test it, here is a sample pk3 containing:
1. A md3 actor with 6 models total, all of which have multiple surfaceSkins, and are animated. The first cube on the left also has no textures assigned to the top and bottom faces to test if it makes the surfaces invisible, which it should and does. 
2. A voxel actor, with multiple frames.
https://www.dropbox.com/s/la9p65h5akb4r5w/multimodel.pk3

### CODE REVIEW

**Comment by coelckers** [comment]
For better looking code, could you please change those loops to use modern C++ iterator syntax?

**Review by alexey-lysiuk — COMMENTED** [review]
May I ask you to avoid arbitrary additions of empty lines and white spaces? Such changes introduce only useless noise to diff and blame features.

**Comment by Chernoskill** [comment]
> For better looking code, could you please change those loops to use modern C++ iterator syntax?

Thank you for the suggestion. I replaced them with range-based loops.

> May I ask you to avoid arbitrary additions of empty lines and white spaces? Such changes introduce only useless noise to diff and blame features.

Thanks for bringing this to my attention. I tried to remove any empty lines that were introduced by me previously.

**Comment by Chernoskill** [comment]
Sorry for all the commits. I wanted to make sure all empty line changes caused by mean were reverted. Should be good now :)

**Comment by vsonnier** [comment]
Hello @Chernoskill ! I tried this PR, unfortunately with either Brutal Doom v21.8 (https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases) or Brutal Doom Black Edition v3.2c ( https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition ) or probably every other Brutal Doom derivative, they cannot load.

For instance with  Brutal Doom v21.8 I get the following message:
```
Execution could not continue.

Script error, "brutalv21.8.0.pk3:modeldef.txt" line 280:
Too many models in WaterSplashWaves
```

**Comment by Chernoskill** [comment]
> Hello @Chernoskill ! I tried this PR, unfortunately with either Brutal Doom v21.8 (https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases) or Brutal Doom Black Edition v3.2c ( https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition ) or probably every other Brutal Doom derivative, it fails to load.
> 
> For instance with Brutal Doom v21.8 I get the following message:
> 
> ```
> Execution could not continue.
> 
> Script error, "brutalv21.8.0.pk3:modeldef.txt" line 280:
> Too many models in WaterSplashWaves
> ```

This is to be expected and in fact normal behavior. It is most likely caused by a MODELDEF entry's FrameIndex line to refer to a model index that is equal to or higher than the number of models used for that actor. There is even supposed to be a check when parsing a MODELDEF lump to make sure this does not happen, but it never caught any issues because the value it checked against was never correct, from what I understand. So, in short: In my opinion, this was always meant to cause a fatal error on startup, but never did. Now it does. 

That being said, I will replicate the old behavior for the sake of old mod compatbility.

**Comment by coltongit** [comment]
> > Hello @Chernoskill ! I tried this PR, unfortunately with either Brutal Doom v21.8 (https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases) or Brutal Doom Black Edition v3.2c ( https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition ) or probably every other Brutal Doom derivative, it fails to load.
> > For instance with Brutal Doom v21.8 I get the following message:
> > ```
> > Execution could not continue.
> > 
> > Script error, "brutalv21.8.0.pk3:modeldef.txt" line 280:
> > Too many models in WaterSplashWaves
> > ```
> 
> This is to be expected and in fact normal behavior. It is most likely caused by a MODELDEF entry's FrameIndex line to refer to a model index that is equal to or higher than the number of models used for that actor. There is even supposed to be a check when parsing a MODELDEF lump to make sure this does not happen, but it never caught any issues because the value it checked against was never correct, from what I understand. So, in short: In my opinion, this was always meant to cause a fatal error on startup, but never did. Now it does.
> 
> That being said, I will replicate the old behavior for the sake of old mod compatbility.

Would make sense in this case to have a per-mod override for this to ensure that these mods can run under the legacy behavior

**Comment by Chernoskill** [comment]
> > > Hello @Chernoskill ! I tried this PR, unfortunately with either Brutal Doom v21.8 (https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases) or Brutal Doom Black Edition v3.2c ( https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition ) or probably every other Brutal Doom derivative, it fails to load.
> > > For instance with Brutal Doom v21.8 I get the following message:
> > > ```
> > > Execution could not continue.
> > > 
> > > Script error, "brutalv21.8.0.pk3:modeldef.txt" line 280:
> > > Too many models in WaterSplashWaves
> > > ```
> > 
> > 
> > This is to be expected and in fact normal behavior. It is most likely caused by a MODELDEF entry's FrameIndex line to refer to a model index that is equal to or higher than the number of models used for that actor. There is even supposed to be a check when parsing a MODELDEF lump to make sure this does not happen, but it never caught any issues because the value it checked against was never correct, from what I understand. So, in short: In my opinion, this was always meant to cause a fatal error on startup, but never did. Now it does.
> > That being said, I will replicate the old behavior for the sake of old mod compatbility.
> 
> Would make sense in this case to have a per-mod override for this to ensure that these mods can run under the legacy behavior

Since this PR has pretty major consequences in teh way models are loaded, I have now ensured that all mods are compatible.

**Comment by vsonnier** [comment]
> Since this PR has pretty major consequences in teh way models are loaded, I have now ensured that all mods are compatible.

Yeah, works for me now ! It is indeed very important not to break existing mods, and especially the most popular ones however dirty they could have been written so thanks for adding a proper workaround.

**Comment by Cacodemon345** [comment]
So is the problem affecting the BD derivatives indeed fixed?

**Comment by vsonnier** [comment]
> So is the problem affecting the BD derivatives indeed fixed?

For the 2 examples above, it now loads and play OK, as far as I can tell. I also tried to run Project Brutality `master` ( https://github.com/pa1nki113r/Project_Brutality ) and it seems to work.

**Comment by Chernoskill** [comment]
The problem was not specific to BD derivatives. It was a problem for all mods (including one (unreleased) of mine) that "got lucky" over the past years since MODELDEF was introduced becasue the checks that was supposed to catch model indices equal to or beyond the number of models in a FramIndex line never did so, as far as I can tell.

**Comment by madame-rachelle** [comment]
Had some testing done on Discord - while only one person tested it so far he found no problems with two different mods.

**Comment by coelckers** [comment]
@Chernoskill  Please resolve the conflicts, apparently this clashes with a few validation checks I had to add for Raze.

**Pull request merged**
