### PR TITLE
CanCrossLine (Attempt #2)

### PR DESCRIPTION
**Pull request by MajorCooke**
Added CanCrossLine virtual for actors.

- Called last after all other line checks occur. Returning false means the actor cannot cross that line.

### CODE REVIEW

**Comment by coelckers** [comment]
Have there been any tests with this on highly populated maps with high detail?
This adds very costly code to the innermost parts of the most performance critical part of the entire engine.

**Comment by madame-rachelle** [comment]
Oops - no - I can revert this.

**Comment by madame-rachelle** [comment]
On Sunder MAP11 (The Furnace) stat think time was 8 ms without the patch, and 9.5 ms with the patch, on a Ryzen 7 3800X at 3.8 GHz

**Comment by madame-rachelle** [comment]
Even though that was a fairly rudimentry test that did seem to show a ~19% increase in think time, so I will revert the patch.

**Pull request merged**
