### PR TITLE
Mac M1 build fix, try to apply arm compiler flags to other oses only.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Cacodemon345** [comment]
Does this disable the intrinsics too?

**Comment by devnexen** [comment]
Yes the NO_SSE flag is set :-)

**Comment by Cacodemon345** [comment]
And NEON isn't available on the M1?

**Comment by devnexen** [comment]
it s arm 64 (uname -p/CMAKE_SYSTEM_PROCESSOR returns arm however) and neon is implictly enabled those flags are unsupported.

**Review by alexey-lysiuk — COMMENTED** [review]
Using Xcode 12.2+ on Intel Mac, cross-compilation for ARM64 succeeded without any changes at all.

**Comment by devnexen** [comment]
Here a sample of error
`clang: error: the clang compiler does not support '-mcpu=cortex-a7'`

Similarly (not used here) march=native does not work neither.

**Comment by devnexen** [comment]
> Using Xcode 12.2+ on Intel Mac, cross-compilation for ARM64 succeeded without any changes at all.

Did you compile with gcc ?

**Comment by alexey-lysiuk** [comment]
> Here a sample of error
> `clang: error: the clang compiler does not support '-mcpu=cortex-a7'`
> 
> Similarly (not used here) march=native does not work neither.

How do you run CMake? If you are using console, please post CMake command line. If not, did you set some options manually?

On modern Macs, `CMAKE_SYSTEM_PROCESSOR` should be either `x86_64` or `arm64`.
Without explicit override its value is initialized with the output of `uname -m` command.

> Did you compile with gcc ?

I'm using Apple's Clang shipped with Xcode.

**Comment by devnexen** [comment]
> > Here a sample of error
> > `clang: error: the clang compiler does not support '-mcpu=cortex-a7'`
> > Similarly (not used here) march=native does not work neither.
> 
> How do you run CMake? If you are using console, please post CMake command line. If not, did you set some options manually?

Just cmake


> 
> On modern Macs, `CMAKE_SYSTEM_PROCESSOR` should be either `x86_64` or `arm64`.
> Without explicit override its value is initialized with the output of `uname -m` command.

Not exactly https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSTEM_PROCESSOR.html

I m talking about a real Mac M1 not cross compiling on Intel mac btw.

> 
> > Did you compile with gcc ?
> 
> I'm using Apple's Clang shipped with Xcode.
Alright

**Comment by alexey-lysiuk** [comment]
Please update you CMake to a version that has proper support for ARM-based Macs, 3.18 or newer.

**Comment by devnexen** [comment]
Using cmake 3.19 from homebrew ;-)

https://cmake.org/cmake/help/v3.1/variable/CMAKE_SYSTEM_PROCESSOR.html
which leads to

https://cmake.org/cmake/help/v3.1/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html#variable:CMAKE_HOST_SYSTEM_PROCESSOR

same thing...

**Comment by Cacodemon345** [comment]
You are linking to CMake v3.1.3's help instead of CMake v3.19.

**Comment by alexey-lysiuk** [comment]
[3.1](https://cmake.org/cmake/help/v3.1/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html) is _a bit_ older than [3.19](https://cmake.org/cmake/help/v3.19/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html).

Regardless of CMake version, that condition is wrong in general. It assumes too much to just set compiler options for a very specific machine.

**Comment by devnexen** [comment]
Ah in fact in src/CMakeLists.txt
the condition is CMAKE_SYSTEM_PROCESSOR MATCHES "arm" rather than STREQUAL

**Comment by alexey-lysiuk** [comment]
Unless someone is willing to rewrite detection of Raspberry Pi target properly, I would remove the mentioned `if` block altogether.
There are so many ARM-based machines with a broad range of CPUs, and detection of a very few of them by generic processor name only is simply wrong.

**Comment by alexey-lysiuk** [comment]
@madame-rachelle May I ask you to fix [ARM support](https://github.com/coelckers/gzdoom/blob/26eac560dd51003717bcf0ed5cf695028af0d654/src/CMakeLists.txt#L321-L329)?

If it's not possible to detect a particular machine for which these compiler options are needed, please either remove the faulty detection, or make it an option disabled by default.
There is a huge number of ARM-based devices, applying very specific settings by generic CPU name is a bad idea.

**Comment by madame-rachelle** [comment]
https://github.com/coelckers/gzdoom/commit/b70c66e2ccaa626e13e08eea604468a45366c1d8

Unfortunately this seems to be the best we can do. It's been converted into an option, now, though, which can be turned off.

**Comment by madame-rachelle** [comment]
If you have any reliable ways to test for Raspberry Pi's using CMake, I am willing to rewrite the detection a little more robustly. For now, I hope this will do.

**Comment by alexey-lysiuk** [comment]
Thanks.

I never worked with Raspberry Pi, and have zero interest in such hardware in general.
It is nice that unwanted compiler options can be disabled at least, and the problem with Apple M1 target should be fixed.

**Pull request closed without merging**
