### PR TITLE
Optional override for SetSlot and ClearPlayerClasses

### PR DESCRIPTION
**Pull request by madame-rachelle**
With this, a decade-long struggle can now be ended.

This pull request revives #909

### CODE REVIEW

**Comment by MajorCooke** [comment]
Oh right, I completely forgot I had this merged into QZDoom too.

**Comment by MajorCooke** [comment]
There's a problem with the menu code. For some reason this option isn't showing up in the misc options menu.

**Comment by MajorCooke** [comment]
I reverted Ed's PR and used this one instead in QZDoom. I had actually forgotten this was already in and I updated the QZDoom thread too.

**Comment by MajorCooke** [comment]
I cannot merge this due to a conflict into QZDoom.

**Comment by drfrag666** [comment]
What's the value of the $MISCMNU_SETSLOTSTRICT string? It's missing in the original PR as well.

**Comment by madame-rachelle** [comment]
It's added to the translation list now.

**Pull request merged**
