### PR TITLE
GCC warning fixes

### PR DESCRIPTION
**Pull request by Blzut3**
This doesn't fix all of them, but definitely cleans up the output a lot.  GCC introduced a lot of static analysis class warnings which while they point out mostly harmless things they have produced some interesting results.  Like they now warn if you memcpy/set/move on types where the relevant operations would be non-trivial.

So with that there is some encouragement to go and explicitly default operations that previously needed to be defined in C++98/03.  Also made me analyze the operator= optimization in TVector which as it turns out appears to be inhibiting the compiler from doing the right thing which the default empowers.  Interestingly on 32-bit GCC the optimization allows the compiler to use SSE where as the opposite is true for 64-bit.  That said what Randi's comment says no longer applies in either case so profiling would need to be done to see if the microoptimization even does anything there and well at this point probably not worth worrying about.  Especially since it makes the type non-trivially copyable according to the standard.

One thing I haven't done yet but will need to explore later is reversing FName and FNameNoInit's hierarchy.  Since as it stands FNameNoInit is not trivially constructable which is making a number of otherwise POD types non-POD.

**I've only tested on Linux**, so please do check Windows before merging.  Also note that I made I_Error [[noreturn]] including in the win32 code.   This assists the static analyzer in making assumptions.  I_FatalError however can't be noreturn as it's written now since it does have a path where it technically returns.

### CODE REVIEW

**Comment by Blzut3** [comment]
You are correct that implicit-fallthrough=1 was the issue.  The cmake really needs to be converted to modern CMake which would have also made the issue more clear since the warning flags wouldn't apply to the thread_local check.

I could logically split it into 3 or 4 commits if you really want.  This commit was basically a top to bottom comb over the trivial to fix warnings.

**Comment by alexey-lysiuk** [comment]
In fact `CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "4.5"` condition is redundant because the oldest version of GCC that can build GZDoom is 4.9

Personally I don't like commits with long list of changes. Sometimes this is unavoidable but I would prefer to have self-contained commits as small as possible. Please note that this is my opinion only.

**Comment by coelckers** [comment]
Sorry, not like this.
This is way too much in one commit and removing the memcpy-based assignment operators for GLWall, GLFlat and GLSprite will have a performance hit. They were explicitly added to make the copy operation faster on Visual C++.

**Comment by alexey-lysiuk** [comment]
Also, I would make a macro defined as `[[fallthrough]]` for C++17 compiler and as something platform specific (or just nothing) for earlier language versions.

**Comment by coelckers** [comment]
Agreed. Is there even a good reason to stick to C++11 anymore?

**Comment by alexey-lysiuk** [comment]
At the moment Visual Studio 2015 and conservative Linux distros (with GCC 4.9) define the lowest language version, i.e. C++11 with some features of C++14 (for example, generic lambda support is mandatory).
Personally I’m fine to switch to MSVC 2017 / GCC 7+ / Clang 5+ where C++17 implementation is almost complete. It’s about up-to-date Visual Studio 2017 though, like 15.7.x and not initial release.

**Comment by Blzut3** [comment]
Wow, Visual C++ is really that bad at optimizing that it can't convert an assignment to a memcpy?  I guess I can ifdef them to VC++ only since both Clang and GCC handle it just fine, and having them non-trivial potentially blocks optimization opportunities elsewhere.

As for fallthrough, I considered that but figured if they'd all have to be replaced again once C++17 is a reasonable base line might as well go for the minimal solution.  @coelckers if that's the route you prefer let me know.  It is definitely too premature to require C++17 at this time.

The logical breakout I can think of is: 1. fallthrough, 2. make types more trivial, 3. initialization/static analysis fixes.  Is that enough separation or would you like more?

**Comment by Blzut3** [comment]
Playing around with godbolt compiler explorer.  I'm pretty sure the reason you needed the memcpys on VC++ is because of the non-trivial types.  I can explore more when I have the time, but if I create an aggregate type whereby one of the types has a "non-trivial" copy then VC++ gives up pretty much immediately, GCC seems to be able to trace a little longer before giving up, and Clang seems to always do a memcpy although for some reason it decides to actually inline it in the cases where the others give up.

See: https://godbolt.org/g/giLXyd  Change USE_OPT between 0, 1, and 2.  0 is what this patch would have produced, 1 is what I believe you tried to optimized, and 2 is what you did.  In any case 0 and 2 produce basically identical results across all compilers.  Not an exact replica of the structures, so there could admittedly be minor details.

**Pull request closed without merging**
