### PR TITLE
Add PSPF_PLAYERTRANSLATED flag

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR adds:
1. PSPF_PLAYERTRANSLATED flag: Makes the PSprite colorized according to the user's color settings of the player.
2. bPlayerTranslated variable: for checking whether it is colorized according to the user's color settings of the player.

### CODE REVIEW

**Comment by drfrag666** [comment]
It's not a clean branch, there are several ancient PRs and old merges. Is that really a problem?

**Comment by madame-rachelle** [comment]
Ah, yes, that will have to be fixed, although doing a squash will do that automatically.

**Comment by MajorCooke** [comment]
I've cherry picked the one commit that matters into QZDoom and ignored all the merging entirely.

**Comment by coelckers** [comment]
I just went ahead and rebased this. It's the only way I see to do a review on it, so please be aware that this may get removed again if the review does not succeed.

**Pull request merged**
