### PR TITLE
added option search menu

### PR DESCRIPTION
**Pull request by mmaulwurff**
A menu that allows searching for options and controls.

https://forum.zdoom.org/viewtopic.php?f=105&t=63945#p1095219

### CODE REVIEW

**Comment by coelckers** [comment]
This needs to wait until the new translation tables are ready. The old language files are going to be discontinued soon and I won't add anything that alters them right now.

**Comment by mmaulwurff** [comment]
Nemrtvi, 
Screenshot from 2019-03-16 22-15-06

coelckers, no problem, I'll wait. Will there be a clear signal when the new translation tables are considered ready? I'll update this PR and https://github.com/coelckers/gzdoom/pull/752.

**Comment by coelckers** [comment]
The main work is done - I wrote a blog post about what needs to be done differently in the future, it is mainly about how to convey new texts.

**Comment by mmaulwurff** [comment]
Done, the changes in language.enu are canceled.
Here are the text strings:
```
OS_TITLE      = "Option Search";
OS_ANY        = "Search for any terms";
OS_ALL        = "Search for all terms";
OS_MAIN       = "Main Options";
OS_NO_RESULTS = "No results found.";
OS_LABEL      = "Search:";
```

**Comment by coelckers** [comment]
Although I added it, while doing some testing I noticed one problem and have one question:

The problem: Changing between OS_ANY and OS_ALL does not trigger a search. This should provide immediate feedback just like pressing Enter on the input line.

The question: What is OS_MAIN for? From looking at the code I cannot deduce the context this may appear in so I cannot add a German translation.

**Comment by mmaulwurff** [comment]
The problem: noted, I will try to implement the immediate feedback.

The question: OS_MAIN: it's a stub title for options that are not in Options Menu, but in main menu, like this:
Screenshot from 2019-03-17 01-09-54

Only now I see that it's possible to get the original text in this case too. My bad. Will amend in the future commit.

**Comment by Nemrtvi** [comment]
I found a small issue with this search menu: when typing characters in Cyrillic, they turn into a Latin character when pressing backspace. When pressing backspace again, the letter disappears as it should.

I get the feeling it might be related to [this](https://github.com/coelckers/gzdoom/commit/50ebca20bb3882f535f32de78b0008a8be5df63c) commit—the replacing Latin letter is always a D or a Ñ—but I’m not sure.

**Comment by mmaulwurff** [comment]
@Nemrtvi , does thin happen with other input fields?

**Comment by Nemrtvi** [comment]
> 
> 
> @Nemrtvi , does thin happen with other input fields?

You mean like the in-game chat and the console? No. As far as I can tell, this is unique to the search menu.

**Comment by Nemrtvi** [comment]
Though, I haven’t been able to replicate this consistently. After restarting GZDoom twice, the Cyrillic letters behaved as expected.

**Comment by mmaulwurff** [comment]
@Nemrtvi , please try 
[text-test.zip](https://github.com/coelckers/gzdoom/files/2974900/text-test.zip)

It adds a standard text field to the bottom of Options menu.

**Comment by Nemrtvi** [comment]
@mmaulwurff 

I just tried it out. It didn’t have this issue. Strange—perhaps something random just happened when I launched GZDoom once, but the text erases itself normally now.

**Comment by Nemrtvi** [comment]
Tried it once more, and the issue appeared once again. Cyrillic letters turned into either a D or a Ñ when pressing backspace. It seems to happen when I minimize the window and go to write somewhere else and/or change keyboard layouts.

**Pull request merged**
