### PR TITLE
Add rt to lib list after others such as libasmjit to fix linking order

### PR DESCRIPTION
**Pull request by chewi**
I wasn't able to reproduce this personally so it may depend on other
factors but more than one other Gentoo user encountered it. See
https://bugs.gentoo.org/695192.

### CODE REVIEW

**Comment by coelckers** [comment]
Before merging this I'd like to hear a second opinion from someone using Linux.

**Comment by chewi** [comment]
Okay, this should deal with it properly. However, this actually hasn't been needed since you reverted the newer asmjit in 523fd0bf3a282edbcef36017ae8d16039cdeff59 because the older version doesn't use `shm_open`. If you bring it back then you will need this.

**Comment by alexey-lysiuk** [comment]
No reason to keep this PR open then. Also, macOS doesn’t have librt, so the change cannot be accepted in its current form anyway.

**Comment by chewi** [comment]
I did try to find out whether BSD has librt or not. I couldn't get a straight answer so maybe it varies. Anyway, I trust you'll deal with this if you bring the newer asmjit. Let me know if you need a hand.

**Pull request closed without merging**
