### PR TITLE
Add Linux distribution detection

### PR DESCRIPTION
**Pull request by Cacodemon345**

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
You are using free in one place and delete[] elsewhere to delete the buffer.  Can't you just use a static buffer here?

**Comment by Cacodemon345** [comment]
Static buffer can't be used because POSIX `getdelim` does not work well with static buffers since it expects a malloc'd buffer.

**Review by alexey-lysiuk — COMMENTED** [review]
What's the advantage of `getdelim()` function over `fgets()` here? With the latter, heap allocation isn't needed, so loop becomes simpler in general.

Variable's name and value parsing is rather naive. Shell-like syntax this file uses is much more complicated.
It doesn't test for presence of equal sign after variable name. It ignores a possibility of space characters' presence before variable name. It strips double quotes and new lines unconditionally. It doesn't handle escape characters.

`/etc/os-release` has a fallback location at `/usr/lib/os-release`.

Please use a single space after comma when passing arguments to functions.

**Comment by Cacodemon345** [comment]
All `/etc/os-release` examples I have seen so far does not include any spaces before or after the equal sign.

**Comment by alexey-lysiuk** [comment]
In general, I'm fine with simplified parsing except missing equal sign check.

**Comment by Cacodemon345** [comment]
Any more issues?

**Comment by alexey-lysiuk** [comment]
> Any more issues?

Yes, there are a few of them, but it's irrelevant for now.

On the second thought, implementation of fully functional shell-like parsing is a futile endeavor.
I let a shell do this for us, see 1767fdfe7a1cf522345799824e1e8e49e35c90fb.

**Pull request closed without merging**
