### PR TITLE
SDL joystick capable of controlling menus

### PR DESCRIPTION
**Pull request by protocultor**
These changes leave *nix platforms with the same functionality as in Windows: be able to use joystick/gamepad to navigate menus, making keyboard only needed for a first-time setup (deadzones and the like).

The DirectInput change is to leave the X axis as the first one and Y as the second, just like in XInput, PS2 and POSIX. Then, _menu.cpp_ was changed to reflect this. All of these fixes the issue where you could go up/down in the menus by pressing left/right (and viceversa) in *nix platforms.

JOY14 and 15 are the **O** and **X** buttons in a PS3 controller for a Raspberry Pi, and were added to be able to accept/cancel options in menus.

Finally, the _i_gui.cpp_ changes allow for a proper hiding of the system cursor in a Raspberry Pi.

All changes are based in my LZDoom changes for Raspberry Pi ([https://github.com/protocultor/gzdoom/tree/joypad_menu](https://github.com/protocultor/gzdoom/tree/joypad_menu)), and were tested in Ubuntu 18.04 and Windows 7.

### CODE REVIEW

**Comment by mjr4077au** [comment]
I wanted to ask, what's your experience with using the menus in GZDoom without this patch? For me, I can use the gamepad in a menu but if I use an analog axis to go up or down, it basically locks on and continually cycles up and down the menu like crazy.

I reported the issue [in the forums](https://forum.zdoom.org/viewtopic.php?f=2&t=67940), there's also some video there so you that you can see the behaviour. Hoping this is a fix for that :)

**Comment by protocultor** [comment]
> I wanted to ask, what's your experience with using the menus in GZDoom without this patch? For me, I can use the gamepad in a menu but if I use an analog axis to go up or down, it basically locks on and continually cycles up and down the menu like crazy.
> 
> I reported the issue [in the forums](https://forum.zdoom.org/viewtopic.php?f=2&t=67940), there's also some video there so you that you can see the behaviour. Hoping this is a fix for that :)

That happens when you leave deadzone too low for your controller; with 0.150 - 0.200 in all axes you should be OK. That even happens in Windows for some controllers. That's why the "block controller input in menu" option exists, for that first-time setup of your gamepad :)

**Comment by mjr4077au** [comment]
> That happens when you leave deadzone too low for your controller; with 0.150 - 0.200 in all axes you should be OK. It even happens in Windows for some controllers. That's why the "block controller input in menu" option exists, for the first-time setup of your gamepad :)

Yeah, okay... Aren't I the stupid one lol. Didn't happen in Windows so that threw me off. Appreciate the insight, will ask for the post to be closed.

**Comment by protocultor** [comment]
> > That happens when you leave deadzone too low for your controller; with 0.150 - 0.200 in all axes you should be OK. It even happens in Windows for some controllers. That's why the "block controller input in menu" option exists, for the first-time setup of your gamepad :)
> 
> Yeah, okay... Aren't I the stupid one lol. Didn't happen in Windows so that threw me off. Appreciate the insight, will ask for the post to be closed.

Nah, I also freaked out the first time it happened to me. Let's hope this gets solved for good.

**Comment by madame-rachelle** [comment]
This needs to be updated to the latest master to resolve merge conflicts.

**Comment by protocultor** [comment]
> This needs to be updated to the latest master to resolve merge conflicts.

I'd love to do that but your latest master crashes on my Ubuntu. Your previous master worked perfectly 4 months ago.

**Comment by protocultor** [comment]
Since there have been so many changes since I submitted this PR, I've updated this with
https://github.com/coelckers/gzdoom/pull/1163

**Pull request closed without merging**
