### PR TITLE
Added support for monospacing alignment modes to HUDFont / BaseStatusBar.DrawString

### PR DESCRIPTION
**Pull request by Player701**
This PR adds support for monospacing alignment modes to HUDFont (and therefore to BaseStatusBar.DrawString). See [here](https://forum.zdoom.org/viewtopic.php?f=15&t=64268) for details. Updated test WAD / screenshot can be found in the thread.

### CODE REVIEW

**Comment by Player701** [comment]
Sorry, I'm not particularly familiar with these C++ quirks, so I'm not quite sure what kind of declaration you're talking about... I think you are allowed to push changes to my PR branch, so I'd be happy if you could fix it for me.

**Comment by coelckers** [comment]
The problem is that the size of EMonospacing is not well defined. Such types shouldn't be used in a script export because they can cause undefined behavior.. So either make the member variable an int or make the enum an int by declaring it as enum EMonospacing : int

**Comment by Player701** [comment]
OK, I've added an underlying type declaration to `EMonospacing`, but I'm still not sure what I should replace `#include "v_video.h"` with.

**Comment by alexey-lysiuk** [comment]
With `enum EMonospacing : int;`

**Comment by Player701** [comment]
OK, done.

**Comment by alexey-lysiuk** [comment]
Now I would say "squash everything to one commit", but it's better to wait for Graf's final word on this topic.

**Comment by Player701** [comment]
Thanks. Now I can finally get rid of that lousy hack in my mod code...

**Pull request merged**
