### PR TITLE
- Make OpenGL library link fully dynamic on Unix.

### PR DESCRIPTION
**Pull request by edward-san**
Also, remove all the OpenGL CMake checks, because they're not needed anymore.

cc @alexey-lysiuk @Blzut3 for feedback.

### CODE REVIEW

**Comment by coelckers** [comment]
It should be noted that gl_load.c is a generated file so some care will have to be taken. I'm first waiting for feeback before merging.

**Comment by alexey-lysiuk** [comment]
Please remove `// TODO` line and add the following comments around changes in `gl_load.c`:
```
/* BEGINNING OF MANUAL CHANGES, DO NOT REMOVE! */
...
/* END OF MANUAL CHANGES, DO NOT REMOVE! */
```
There is one such block already at the bottom of the file.

I didn't try this PR on Windows but on macOS it works fine. In fact, it doesn't change anything because OpenGL framework is always available and it is required even for software renderer. SDL on Apple's platform also depends on it.

**Comment by coelckers** [comment]
On Windows it also changes nothing because the wgl library is a mandatory part of the OS that is always there. The changes are only in the Linux section, so I guess we still have to wait for a second opinion.

**Comment by edward-san** [comment]
> Please remove // TODO line and add the following comments around changes in gl_load.c:
>...
>There is one such block already at the bottom of the file.

Oh, I didn't notice it. I'll change it.

Anyway, what I really wonder is the behavior with systems which don't have the gl libraries and headers. Now that I think about it, I guess that headers are still required, right?

**Comment by coelckers** [comment]
No. gl_load.c is the only file that may include system headers needed to run OpenGL. The entire point of this is to have the GL headers locally. If this file doesn't include them, nothing will, they all get their definitions from gl_load.h

**Comment by coelckers** [comment]
The option needs 'if linux' checks.

**Comment by edward-san** [comment]
It's not easy to just check 'Linux' so I made the check valid for 'Unix without Apple'.

**Comment by alexey-lysiuk** [comment]
Works fine on macOS.

Unrelated to changes themselves but I would merge this PR as a single commit.

**Comment by edward-san** [comment]
I'd do that, but I need to know if @coelckers agrees.

**Comment by Blzut3** [comment]
What was the point of moving the declaration of DYN_GL to the root CMakeLists.txt?  All the others are specified in src/CMakeLists.txt which makes sense since the options only affect and thus are scoped to the gzdoom binary.

**Comment by edward-san** [comment]
That's because I could avoid [including the gl cmake module](https://github.com/coelckers/gzdoom/pull/213/files#diff-95e351a3805a1dafa85bf20b81d086e6R17) if DYN_GL is on.

**Comment by Blzut3** [comment]
Still makes no sense since FindOpenGL is only used in src/CMakeLists.txt, so you should still be able to declare it there.

**Comment by edward-san** [comment]
Ugh you're right, it works fine. Fixed, squashed and rebased on top of current upstream HEAD.

**Comment by coelckers** [comment]
Is this ready to merge now?

**Comment by Blzut3** [comment]
See ticket 30.

**Comment by edward-san** [comment]
Updated. Removed DYN_GL and cmake gl code.

**Comment by Blzut3** [comment]
Rebased and merged.

**Pull request closed without merging**
