### PR TITLE
AttachMessage parameter fix

### PR DESCRIPTION
**Pull request by MajorCooke**
- Fixed missing id and layer parameters for AttachMessage.

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
Zeroing both should do it.

**Comment by alexey-lysiuk** [comment]
For default values C++ wrapper needs to be updated as well, `PARAM_...` -> `PARAM_..._DEF`.

**Comment by OrdinaryMagician** [comment]
I'd do it myself but this isn't my PR :V

**Comment by MajorCooke** [comment]
UINT does not have a def version, so I'm not touching that.

**Comment by MajorCooke** [comment]
In fact, the more I think on it, the more I'm convinced that Graf had these non-def for a reason so I'm not going to touch it at all unless he confirms otherwise.

**Comment by OrdinaryMagician** [comment]
[I'm pretty sure they're meant to be defs](https://github.com/coelckers/gzdoom/blob/master/src/g_statusbar/sbar.h#L384)

**Comment by alexey-lysiuk** [comment]
Also, `HUDMSGLayer_...` values are not exported to ZScript. I think I'll do it myself.

**Comment by alexey-lysiuk** [comment]
Pushed my changes [here](https://github.com/coelckers/gzdoom/tree/hud_attach_message). It's up to Graf to decide are they worth it or not.

**Comment by coelckers** [comment]
That branch looks ok, so I'll close this PR.

**Pull request closed without merging**
