### PR TITLE
Add optional direction parameters for SprayDecal and its A_SprayDecal zscript counterpart

### PR DESCRIPTION
**Pull request by MekBoss**
As title say.
Test map
[spray_decal_test.zip](https://github.com/coelckers/gzdoom/files/4402374/spray_decal_test.zip)

### CODE REVIEW

**Comment by MekBoss** [comment]
New test example
[spray_decal_test(2).zip](https://github.com/coelckers/gzdoom/files/4403912/spray_decal_test.2.zip)
Sine wave in the corners of a room looks bigger because it is projected from the greater distance btw.

**Comment by MekBoss** [comment]
To which MSVC version I should switch? 2015?

**Comment by alexey-lysiuk** [comment]
2019.

**Comment by MekBoss** [comment]
Should be okay now. The code analyzer showed no errors.
Also add offset argument to SprayDecal, just because I can.
New test example
[spray_decal_test(3).zip](https://github.com/coelckers/gzdoom/files/4446816/spray_decal_test.3.zip)

**Pull request merged**
