### PR TITLE
Add FORCE_INTERNAL_GLSLANG option

### PR DESCRIPTION
**Pull request by DanySpin97**
Add the possibility to use the glslang installed on the system.

### CODE REVIEW

**Comment by coelckers** [comment]
AFAIK this was blocked because the code had to be slightly modified. I think dpJudas can say more about that.

**Comment by dpjudas** [comment]
There's generally two problems with a system install of glslang:

1) its C++ API is not stable as far as I know - so it may not compile if the version doesn't match.

2) glslang might miscompile (we had one update so far to fix such an issue). If the Windows and Linux versions of GZDoom are using the same version the SPIR-V is guaranteed to be the same. If the Linux version uses a random build of glslang debugging could become far more tricky.

**Comment by coelckers** [comment]
That second point is enough for me to close this. I don't want to take any chances of something this critical as the shaders, which the entire renderer depends on.
The memories of random shader miscompilations with AMD and Intel are enough.

**Comment by DanySpin97** [comment]
> glslang might miscompile 

Provided version does not compile for me and I opened this MR to actually not depend on the provided glslang. `FORCE_INTERNAL_GLSLANG` can be set to ON by default.

**Comment by madame-rachelle** [comment]
What compiling environment are you using?

OS, compiler, processor type, etc.

It's better to patch the miscompile than it is to depend on the OS libraries.

**Comment by madame-rachelle** [comment]
Also - relevant errors would be helpful too.

**Comment by dpjudas** [comment]
I think it is better to instead upgrade the internal glslang if it no longer compiles. That way both platforms gets an updated version and the shader compiler will behave identically and predictably on both platforms.

**Comment by DanySpin97** [comment]
I am using Exherbo Linux based on musl, compiling using `clang -stdlib=c++`.

This is the error compiling from master after running `cmake` with no arguments:
```
In file included from /home/danyspin97/Projects/coding/gzdoom/libraries/glslang/OGLCompilersDLL/InitializeDll.cpp:42:
/home/danyspin97/Projects/coding/gzdoom/libraries/glslang/OGLCompilersDLL/../glslang/Include/PoolAlloc.h:307:54: error: 
      'operator=' is a private member of 'glslang::TPoolAllocator'
    void setAllocator(TPoolAllocator* a) { allocator = *a; }
                                           ~~~~~~~~~ ^ ~~
/home/danyspin97/Projects/coding/gzdoom/libraries/glslang/OGLCompilersDLL/../glslang/Include/PoolAlloc.h:244:21: note: 
      declared private here
    TPoolAllocator& operator=(const TPoolAllocator&);  // don't allow as...
                    ^
```

> It's better to patch the miscompile than it is to depend on the OS libraries.

It depends on your point of view. From a packager point of view it is the opposite, packages should only depends on system libraries (and that's the case for almost every software provided by a unix distribution).

Using system libraries gives a lot of flexibility. Let's say that tomorrow I'll need a feature or bug fix from master branch of glslang. How do I use gzdoom? Do I have to come here and ask you to update provided glslang to an untagged release? Should I patch the gzdoom provided one? This doesn't work, because I would have to multiply this effort for all the programs/games that ship an internal version of glslang. Instead I just install the master version of the glslang package and it's fixed. It would be as simple as only patching the system glslang library. Also, system glslang provides shared libraries by default (as can be seen by [arch linux package](https://www.archlinux.org/packages/extra/x86_64/glslang/)).

**Comment by dpjudas** [comment]
Let's just say we disagree on whether the Linux library policy of making every library under the sun a 'system' library is sane. When you use that master branch version of glslang and the whole thing miscompiles you do not go to the distro maintainer or glslang and report a bug. You come to GZDoom and report the bug. That gives us a lot of extra noise for very little benefit.

As for arch linux having made shared libraries of glslang just shows they haven't done their homework. I point at https://github.com/coelckers/gzdoom/commit/06222a1fbf9befa3cb7dc52c52517259d8f289c5#diff-0917c685f6262e5d2f088cfe70bb9f41R92 in GZDoom as the evidence that this library does not have a stable API and therefore linking to the "system" version of the library could produce compile errors on some systems. That it doesn't do that on yours is pure luck, but once again, when it does produce a compile error guess where the users will report it to. Yes that's right - they will report it to US, not the arch maintainer that shouldn't have declared it a system library.

**Comment by coelckers** [comment]
I have to concur with dpJudas. If the maintainers of this library cannot guarantee a stable API it will only get linked statically.
If you get a compile error and want it fixed, please post a PR fixing the bug, not working around it.

**Comment by dpjudas** [comment]
I've upgraded our version of glslang to the latest release: https://github.com/coelckers/gzdoom/commit/a056307218586b4d12aae56a0b6fb34fae0f51b6

Hopefully that should fix the compile error.

**Comment by DanySpin97** [comment]
> When you use that master branch version of glslang and the whole thing miscompiles you do not go to the distro maintainer or glslang and report a bug. You come to GZDoom and report the bug. That gives us a lot of extra noise for very little benefit.

Are you talking about shader compilation? As for the code compilation, you could set version constraint using pkg-config, like "glslang>=8.13&<9.0" as the working version and the packagers have to follow this constraint. This is pretty common practice.

>  I point at 06222a1#diff-0917c685f6262e5d2f088cfe70bb9f41R92 in GZDoom as the evidence that this library does not have a stable API and therefore linking to the "system" version of the library could produce compile errors on some systems.

This literally _always_ happens. It is the responsibility of the packagers to take care of the packages installed on the system and their version. It is the responsibility of the software developers to state the required version of the libraries they're using. This is not an issue, it's just how it works.

> That it doesn't do that on yours is pure luck, but once again, when it does produce a compile error guess where the users will report it to.

Set the version required in this [line](https://github.com/coelckers/gzdoom/pull/1034/files#diff-af3b638bc2a3e6c650974192a53c7291R182) and you're fine, cmake will complain about the version and from there it's their problem. Note that FORCE_INTERNAL_GLSLANG will be ON by default so that GZDoom can compile on every system regardless if glslang is installed or is a wrong version.

> Yes that's right - they will report it to US, not the arch maintainer that shouldn't have declared it a system library.

If you're talking about code compilation, this will never happen. The only place where FORCE_INTERNAL_GLSLANG=OFF will be in the gzdoom system package, and maintainers won't complain for the different version, they will instead update the system glslang or find some way to fix it.

> If you get a compile error and want it fixed, please post a PR fixing the bug, not working around it.

Still, going around all projects and fixing bugs because they do not want to use the system version is a waste of time.

I've tested the build with latest commit and GZDoom compiles for me. Regardless, I will apply this patch for Exherbo gzdoom package and I'd be happy if this PR gets accepted.

**Comment by dpjudas** [comment]
> > Are you talking about shader compilation? As for the code compilation, you could set version constraint using pkg-config, like "glslang>=8.13&<9.0" as the working version and the packagers have to follow this constraint. This is pretty common practice.

I can't setup such a constraint as I don't know when glslang will modify its API next time in the future. I can't even set a lower constraint as I don't know when they fixed our last miscompile or when they changed the API. They didn't make an announcement about it - all I have is their commit log and the option of going through a painful bisect process. The major version number in itself doesn't guarantee anything (they made no public statement about what it means).

> > This literally _always_ happens. It is the responsibility of the packagers to take care of the packages installed on the system and their version. It is the responsibility of the software developers to state the required version of the libraries they're using. This is not an issue, it's just how it works.

Yes, it is exactly why the Linux model has been broken for decades. Neither package maintainers, library consumers or library producers are following the rules to the letter. It only takes one small mistake from either party to cause a problem. Any system relying on flawless behavior from so many people at the same time is a poor design. But hey this is just my opinion - feel free to disagree. I can already tell now we will not reach an agreement on this so let's just stick to the PR itself.

> > I've tested the build with latest commit and GZDoom compiles for me. Regardless, I will apply this patch for Exherbo gzdoom package and I'd be happy if this PR gets accepted.

That's your choice. Just remember, if anyone from that distro reports a shader not working as a side effect of this will be told to try again with a different distro if it only happens there.

**Comment by coelckers** [comment]
> I've tested the build with latest commit and GZDoom compiles for me. Regardless, I will apply this patch for Exherbo gzdoom package and I'd be happy if this PR gets accepted.

Feel free to do that - but then you must add a disclaimer that this is not the original version of GZDoom but a modified one, and the GZDoom maintainers will not take any responsibility for it. 
Sorry, I must insist on this.

**Pull request closed without merging**
