### PR TITLE
Compatibility fixes for Clavicula Nox

### PR DESCRIPTION
**Pull request by edthebat**
https://www.doomworld.com/idgames/levels/doom2/Ports/a-c/clavnoxr

This Vavoom mod was unplayable in G/ZDoom without cheating, due to how swimmable water was implemented. This finally fixes it to work.

### CODE REVIEW

**Comment by coelckers** [comment]
I'd rather want to know why this doesn't work, In Silent Steel all deep water sectors are ok,

**Comment by edthebat** [comment]
Based on how long it's been since our last discussion on that, I didn't expect the engine's implementation would be changing anytime soon. I'm willing to help investigate, but the very most I could offer would be to spot any possible differences in how the two mods implemented their water.

**Comment by edthebat** [comment]
After looking into it, I've found that the arguments for the instances of Special 161 are different between both mods.
Silent Steel uses Water type, alpha of non-zero values (55, for instance), and flags include "don't block movement"
Clavicula Nox usually uses Empty type, alpha is always zero, and the "don't block movement" flag is never active.

**Comment by coelckers** [comment]
Thanks for the info. This sounds like the mod depends on undefined behavior here. I'm not going to try to emulate this.

**Pull request merged**
