### PR TITLE
Display other kills in coop tally screen

### PR DESCRIPTION
**Pull request by MaartenCL**
image

Yay, I did it! The number of other kills counts up together with the personal kills. I added translations in Dutch (my native language), German, French, and Finnish, because I know these languages well enough to know those terms are correct.

The commit also includes some mistakes in Dutch, as "kills" was translated as the 3rd pers. s. of the verb "to kill", and "deaths" would have been reversely translated as "deceased" or "passed away".

### CODE REVIEW

**Comment by madame-rachelle** [comment]
Only thing is - these `language.csv` changes will be overwritten on the next language update. You should request edit access to https://docs.google.com/spreadsheets/d/125KS8lOk8a_Mkxg_NHyMd0XUrDkjUMaNizO0MxiDBF4/edit instead. But otherwise, I see no reason this can't be merged. In the future though, please keep unrelated changes (such as spacing fixes) out of the initial pull request, though.

**Comment by MaartenCL** [comment]
Roger that, thanks!

**Comment by Gaerzi** [comment]
IMO for the French translation it should be "Autres" (plural form).

**Comment by madame-rachelle** [comment]
Picture

Unfortunately, this does not seem to properly track infighting, if that was the goal. I let a bunch of enemies kill each other, and then noclipped to the exit, and this was the result.

**Comment by MaartenCL** [comment]
That it odd, because I tried exactly the same thing, with the plain old _doom.wad_.

Could you give me reproduction steps? Which wad, command parameters...

**Comment by MaartenCL** [comment]
I think I found the issue. If you skip the counting, it didn't update the other kills counter, but stayed at zero.

**Comment by madame-rachelle** [comment]
Looks good to me.

**Pull request merged**
