### PR TITLE
moved controls to submenus in "Customize Controls" menu

### PR DESCRIPTION
**Pull request by mmaulwurff**
What is done:
D1. Controls are separated by existing sections, each section is now a submenu;
D2. The original sections are preserved;
D3. The original controls order is preserved;
D4. "Controls" section is renamed to "Game", because "Controls" submenu of "Customize Controls" would be too confusing;
D5. Map (automap) controls are added as a section, map controls submenu is unchanged;
D6. Missing controls are added to "Other" section;
D7. Sections are given a title following the scheme "Customize [section] Controls", except N4 (see below).
D8. Inside the sections, spaces are added to group the related controls.

Things that I'm not sure about:
N1. "Game" controls section name is too generic - I'll gladly change it to something more suitable;
N2. "Other" controls section name is too generic - I'll gladly change it to something more suitable;
N3. Map controls submenu could use some spacing, and internal title ("Map Controls") is redundant;
N4. "Strife Popup Screens" section name is too long to fit in scheme described in D7, therefore the title is "Strife Popup Screens Controls";
N5. "Game" section could be divided further, but this will break the original menu structure.

### CODE REVIEW

**Comment by mmaulwurff** [comment]
While I agree with the fact that +userX bindings are in the wrong place, moving them to the other place will cause confusion, won't it? I tried to be as conservative as possible.

**Comment by alexey-lysiuk** [comment]
IMHO those bingings are aleady causing a confusion because newcomers would think "what the hell is this?" and advanced users would think "is this really used so frequently?"

**Comment by Nemrtvi** [comment]
Sweet. Gonna add this to the Russian translation of GZDoom. @mmaulwurff and @alexey-lysiuk, do you think this is correct?
`CNTRLMNU_GAME                    = "Игра";
CNTRLMNU_GAME_TITLE                = "Настройки игры ";
CNTRLMNU_CHAT_TITLE                = "Чат";
CNTRLMNU_WEAPONS_TITLE                = "Оружие";
CNTRLMNU_INVENTORY_TITLE            = "Инвентарь";
CNTRLMNU_OTHER_TITLE                = "Другие клавиши";
CNTRLMNU_POPUPS_TITLE                = "Всплывающее меню Strife";
CNTRLMNU_PAUSE                    = "Пауза";
CNTRLMNU_DISPLAY_INC                = "Увеличить размер экрана";
CNTRLMNU_DISPLAY_DEC                = "Уменьшить размер экрана";
CNTRLMNU_OPEN_HELP                = "Помощь";
CNTRLMNU_OPEN_SAVE                = "Сохранение игры";
CNTRLMNU_OPEN_LOAD                = "Загрузка игры";
CNTRLMNU_OPEN_OPTIONS                = "Главное меню настроек";
CNTRLMNU_OPEN_DISPLAY                = "Меню настроек видео";
CNTRLMNU_QUICKSAVE                = "Быстрое сохранение";
CNTRLMNU_QUICKLOAD                = "Быстрая загрузка";
CNTRLMNU_EXIT_TO_MAIN                = "Выход в главное меню";
CNTRLMNU_TOGGLE_MESSAGES            = "Переключение сообщений";
CNTRLMNU_MENU_QUIT                = "Выход";
CNTRLMNU_ADJUST_GAMMA                = "Настройка гаммы";`

**Comment by JNechaevsky** [comment]
Hi, colleagues. May I leave a small aesthetic suggestion here? Maybe it's worth to draw `or` with a little bit different color for preventing too monotone color in long strings with more than one bindings. Something like this:

or

**Comment by Gaerzi** [comment]
If "Game" corresponds to the basic (movement, attack, use, etc.) then "Action" would fit. Honestly, to me, "game controls" sounds more like the keys to pause, call the menu, change the screen size, etc. What controls the _game_.

**Comment by mmaulwurff** [comment]
Note that there is a typo in a commit message, but not in the code :)

@alexey-lysiuk , +userX controls are moved to the bottom of the menu.
Should I squash the commits?

@Nemrtvi , it is suprisingly hard for me to translate to Russian. My attempts seem awkward even to myself.

@JNechaevsky , I agree, but it seems unrelated to this PR. I'd suggest moving " or " string from C_NameKeys function in c_bind.cpp to language.enu first.

@Gaerzi , menu is renamed. Thanks!

**Comment by alexey-lysiuk** [comment]
> +userX controls are moved to the bottom of the menu.
> Should I squash the commits?

Yes please.

**Comment by mmaulwurff** [comment]
Done.

**Pull request merged**
