### PR TITLE
[Draft] Nash's A_PlaySound start time

### PR DESCRIPTION
**Pull request by madame-rachelle**
For now this is mostly so I can see what is going on in the branch, but I do plan to complete this and make this mergeable.

### CODE REVIEW

**Comment by nashmuhandes** [comment]
These are the 2 remaining issues, I think:

> More generally, I think it would be better to always clamp the start time instead of conditionally wrapping it when looping, because a sound may have non-default loop points that one would expect such wrapping to acknowledge.

> I also think this can be just as easily handled outside of the backend, prior to any StartSound[3D] calls so it doesn't depend on the backend to implement this behavior.

**Comment by nashmuhandes** [comment]
@madame-rachelle here's the example file
[a_playsound_start_time_test.zip](https://github.com/coelckers/gzdoom/files/3822959/a_playsound_start_time_test.zip)

**Comment by madame-rachelle** [comment]
@kcat can you clarify this please?

> I also think this can be just as easily handled outside of the backend, prior to any StartSound[3D] calls so it doesn't depend on the backend to implement this behavior.

**Comment by kcat** [comment]
What I mean is, `S_StartSound` has the sfx handle to play, which can be queried for its length. The function can then adjust the start time prior to calling `GSnd->StartSound` or `GSnd->StartSound3D`. The sound backend then doesn't have to worry about the time being out of range, and any future backend automatically inherits the same behavior. So for example, in `src/sound/s_sound.cpp`:
```
static FSoundChan *S_StartSound(...)
{
    ...
    startTime = (chanflags&SNDF_LOOP)
        ? fmod(startTime, (float)GSnd->GetMSLength(sfx) / 1000.f)
        : clamp<float>(startTime, 0.f, (float)GSnd->GetMSLength(sfx) / 1000.f);
    GSnd->StartSound3D(..., startTime);
    ...
}
```

**Comment by madame-rachelle** [comment]
This is currently not possible to port to the current master version, it has to be redone due to the extensive sound rework. This unfortunately shows the nastiness that can occur when a PR stays open for too long, and most of that is my fault for putting this off for too long and not foreseeing that the sound code would've been changed this extensively. The worst part is that `S_Sound` has several overloads and it's hard to match which one to which one. This would've been an easy PR to fix had I not waited, now it's nearly impossible, especially since I have virtually no experience with the sound code or the OpenAL backend.

**Pull request closed without merging**
