### PR TITLE
Remove support for SDL2 2.0.5 and earlier

### PR DESCRIPTION
**Pull request by Cacodemon345**
This PR removes support for SDL2 versions 2.0.5 and earlier.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
The change makes the code much cleaner. However, what versions of popular distros it excludes? Support of Ubuntu 16.04 ends today, have no idea about others.

**Comment by Cacodemon345** [comment]
Fedora: Anything earlier than 27.
Debian: Anything earlier than Buster. Also means only Deepin OS releases incorporating Debian Buster and later are supported after this PR.
openSUSE Leap: Anything earlier than 15.2.

**Comment by alexey-lysiuk** [comment]
This is kinda OK to me. If someone has an objection, let us know.

**Comment by alexey-lysiuk** [comment]
On second thought, you need to specify the oldest supported version of SDL2 [here](https://github.com/coelckers/gzdoom/blob/ff35ea9ac7e76972a56369427b7464c972a0287e/src/CMakeLists.txt#L180).

**Comment by Cacodemon345** [comment]
The `FindSDL2.cmake` file lacks the mechanism to detect the version of SDL2.

**Comment by Cacodemon345** [comment]
Let's wait for https://github.com/coelckers/gzdoom/pull/1058 until the SDL2 version can be checked.

**Comment by alexey-lysiuk** [comment]
I merged both commits, added a version string, and [it fails to build](https://github.com/alexey-lysiuk/gzdoom/actions/runs/799776108).
```
CMake Error at src/CMakeLists.txt:180 (find_package):
  Could not find a configuration file for package "SDL2" that is compatible
  with requested version "2.0.6".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake, version: unknown
    /lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake, version: unknown
```

Build machines have Ubuntu 20.04.2 installed.

**Comment by Cacodemon345** [comment]
I don't think version checking via CMake config was available before 2.0.12. Alternate method will need to be used.

**Comment by Cacodemon345** [comment]
This should do the trick.

**Pull request merged**
