### PR TITLE
Lens flare, now without that unneeded code

### PR DESCRIPTION
**Pull request by usernameak**

### CODE REVIEW

**Comment by nashmuhandes** [comment]
Wow, this came out of nowhere! Any images?

Also, I am particularly interested in learning more about what conditions would draw the lens flares. And can modders specifically assign different lens flare textures to different light sources?

Also, is it possible to create an infinitely-distanced lens flare for eg the sun? I made lens flares using ACS and HudMessage (uggglllyyyy hack) and I was hoping shaders would allow me to get rid of my ACS! (Demo video here : https://www.youtube.com/watch?v=E-1wW0pAp5Y )

**Comment by usernameak** [comment]
@nashmuhandes Demo video here : https://youtu.be/TrlogN1Y1uo . That shitty space suit effect can be fixed (yeah, i haven't fixed that yet!) by changing two lines of code. The lens flares are fully rendered by the shader which processes image from screen and flares light parts.

**Comment by coelckers** [comment]
I honestly don't know what to make of this. While it's certainly interesting from a technical point of view, the entire effect feels far too intrusive even on the lowest settings,

**Comment by alexey-lysiuk** [comment]
Exactly. Lens flare is cool as a temporary effect used in suitable places by level/mod author. Although as a permanent post-processing one it's pretty annoying IMHO.
And it could be customized by content creator for particular scenario but not by end users.
I'm curious is there anyone who wants to play with it enabled? If so, disregard my comment and merge it (as the single commit preferably).

**Comment by MajorCooke** [comment]
And if merged, it should be more professionally written too.

**Comment by coelckers** [comment]
In its current state I see no point to merge it. The effect, even with all sliders at the left is too strong - and to the right it's utterly overblown. I started a thread at the forum to get some more feedback but I strongly tend towards closing the PR.

**Comment by nashmuhandes** [comment]
@usernameak I've left some feedback on the forum too, hope you can check it out when you have time, thanks

**Comment by coelckers** [comment]
The overwhelming consensus was not to use this feature in its current state.

**Comment by StrikerMan780** [comment]
I think you'd be better off making proper flares using the unused "flare" property for dynamic lights in GLDEFS.

**Pull request closed without merging**
