### PR TITLE
Some fixes (fixes?) in abstract classes

### PR DESCRIPTION
**Pull request by jewalky**
- Made it possible to create an instance of the current class using "new()" without parameters
- Made it possible to create an instance of an abstract class (but it's private-like, you can only do it if you are doing it from the same class), so that modders can also make libraries that require you to call the "constructor" static method instead of creating things directly
- Now passing calling function to new(), right now only for abstract check, but this is also required for context-aware checks of playsim<->ui barrier
- Added check at compile time for constant new(...), to catch programming errors ASAP and not randomly during runtime
- Fixed possible Type() dereferencing before checking Type() for null during ZScript class initialization
- Made abstract inherited, so that you can't do class Bla : Actor and then construct Bla freely.

Test case http://pastebin.com/g9SpHjFQ

### CODE REVIEW

**Comment by coelckers** [comment]
There's one thing that's an absolute no-go. You cannot inherit a parent class's 'abstract' attribute, that would negate the entire purpose of it, namely to prevent the creation of the base class of a class family.
The use case you want to cover is not really reason enough to prevent that.

**Comment by jewalky** [comment]
The use case I want to cover is preventing creation of Actors, Thinkers, Iterators directly using new. I wanted to implement a separate keyword, but you said that abstract is used for that.

**Comment by coelckers** [comment]
If you want to block new, this should be a different keyword. You essentially took an established function and changed its meaning into something entirely different. We need both, then.

**Comment by jewalky** [comment]
https://github.com/coelckers/gzdoom/pull/248#issuecomment-279228650 found the exact comment :P
Anyway, going to fix.

**Comment by jewalky** [comment]
Changed and reverted regular abstract to unconditional failure if you try to construct it.

**Pull request merged**
