### PR TITLE
Allow Level Compatibility to remove COUNTKILL/COUNTITEM

### PR DESCRIPTION
**Pull request by 3saster**
https://forum.zdoom.org/viewtopic.php?f=15&t=68326

Added a spawn flag MTF_NOCOUNT that will remove the COUNTKILL/COUNTITEM flag from a particular thing on a map. Some use cases are detailed in the forum post and the second commit; thanks to Skepticist from Doomworld who did most of those. The first commit contains the actual content for the flag; the second commit contains a number of maps that would benefit from this flag.

### CODE REVIEW

**Comment by coelckers** [comment]
Now all that is needed is to expose the flag to ZScript as well. ;)
BTW, another map using monsters as decoration is Scientist MAP01.

**Comment by 3saster** [comment]
> Now all that is needed is to expose the flag to ZScript as well. ;)

I thought I did? I added the flag to base.zs, should it go somewhere else?

> BTW, another map using monsters as decoration is Scientist MAP01.
There's probably enough for the sake of this PR, more maps can be added later.

**Comment by coelckers** [comment]
> 
> 
> > Now all that is needed is to expose the flag to ZScript as well. ;)
> 
> I thought I did? I added the flag to constants.zs, should it go somewhere else?
> 

Oops, sorry, I meant UDMF, not ZScript. This would be useful for mapping, too.

> > BTW, another map using monsters as decoration is Scientist MAP01.
> 
> There's probably enough for the sake of this PR, more maps can be added later.

Ok, no need to overdo it. ;) I just wanted to note that this map also could use such a setting.

**Comment by 3saster** [comment]
In that case, [this should expose it to UDMF](https://github.com/coelckers/gzdoom/pull/1079/commits/7f21340f96637cabe5cc06915d8fe31007bf11da). Only thing I'm not sure is what the namespaces should be, perhaps you might know?

**Comment by coelckers** [comment]
Same as other new properties: Zd and Zdt.

**Comment by 3saster** [comment]
That ought to cover it then. That should cover everything from GZDoom's side, so it should be ready to push to master now, unless there is something else to add.

**Pull request merged**
