### PR TITLE
Add configuration for the key sequences

### PR DESCRIPTION
**Pull request by pizdjuk**
For example: wr - chose rocket launcher, we - choose shotgun, wq - choose plasma gun

primary objective: with a game controller (from PS4, for example) will be much more simple to map the weapons directly to the key sequences/

secondary objective: more natural way for changing weapon

### CODE REVIEW

**Comment by madame-rachelle** [comment]
This is sourced from the wrong tree, please reopen the pull request.

**Comment by pizdjuk** [comment]
In which one? I tried in master, but it didnt allow me to open a pull request

**Comment by Gaerzi** [comment]
Just look at [the changes](https://github.com/coelckers/gzdoom/pull/1065/files), it's obviously not right.

**Comment by madame-rachelle** [comment]
Check your own GZDoom fork and find the tree where you pushed the work.

If you didn't actually do the work and this is merely a request for a feature, then this is the wrong place to put requests. They must go here, no exceptions: https://forum.zdoom.org/viewforum.php?f=15

**Pull request closed without merging**
