### PR TITLE
ProfileThinker print reorder

### PR DESCRIPTION
**Pull request by MajorCooke**
Changed the order for ProfileThinker's printing to time, count, and classname.

### CODE REVIEW

**Comment by MajorCooke** [comment]
I did the latter.

**Comment by alexey-lysiuk** [comment]
Currently the list isn't sorted at all. I mean that heavy actors should be placed at the top of it.

**Comment by MajorCooke** [comment]
Oh. Okay. Yeah I don't know how to do that part.

**Comment by alexey-lysiuk** [comment]
Added in fc981bf. Let me know if it's enough.

**Comment by MajorCooke** [comment]
It would be preferred if you could flip it around so time is first and name is last, from left to right.

**Comment by alexey-lysiuk** [comment]
OK, I’ll take a look to make it more readable.

**Comment by nashmuhandes** [comment]
@alexey-lysiuk thank you for the various modes, these are very useful indeed. I find myself using number 5 the most useful for my purposes. And yeah, any improvements to make it more readable would also be much appreciated. Can you add some colours perhaps? Similar to "acsprofile" command. Perhaps you could colourize the time printout.

**Pull request closed without merging**
