### PR TITLE
A_ChangeModel

### PR DESCRIPTION
**Pull request by ShinyMetagross**
**A_ChangeModel**(string _modeldef_, int _modelindex_, string _modelpath_, string _model_, int _skinindex_, string _skinpath_, string _skin_, int _flags_, int _generatorIndex_)

This can change the modeldef, models, skins, or surface skins of an actor.

An actor MUST have a modeldef in order to use this function, either defined from modeldef, or given one through the modeldef parameter. You can pass "" to use the same modeldef. Likewise, passing "" for model or skin will just revert to the default model.

You can add models to an actor to render by using generatorIndex to tell your new model index to copy the behavior of another one. You may only copy the behavior of a model index already defined in your actor's current modeldef. To remove a model or skin, just pass "" in model/skin parameter to revert to the default.

**Available flags:**
CMDL_WEAPONTOPLAYER - If used on a weapon, this instead change's the model on the player instead.
CMDL_HIDEMODEL - Hides the specified model index from rendering. Can be used with CMDL_WEAPONTOPLAYER.
CMDL_USESURFACESKIN - skinindex instead corresponds to the number of a surface to replace it's skin.

### CODE REVIEW

**Comment by ShinyMetagross** [comment]
https://drive.google.com/file/d/1L2wCwXHiKilRVOdzBBDUwzSTOv4UZWIA/view?usp=sharing

Here is a test file. Let me explain the various things you can do with it:
**Summon SwapModelDef** - This shows off dynamically swapping modeldefs
**Summon SwapModels** - This shows off raw dynamic model swapping
**Summon SwapSkins** - This shows off raw dynamic skin swapping
**Summon SwapModelsAndSkins** - Dynamically swaps models and skins
**Summon SwapModelsEdgeCase** - No modeldef is defined, will not show any models even though a model and skin is given
**SwapModelsEdgeCase2** - It tries to switch to hammer, but has no modeldef. Therefore, it just shows up as a pistol sprite
**Give TriggerSwapModel** - This token changes the weapon view model and player third person gun model to show off the ideal usage of CMDL_WEAPONTOPLAYER
**Take TriggerSwapModel** - This token reverts the player model and weapon view model back to default. This is where the bug I mentioned occurs, but can be circumvented by just manually stating the model to revert back to.

**Review by coelckers — CHANGES_REQUESTED** [review]
I'm afraid but this still has problems.
First, do you really need two TArrays? This still eats 36 bytes per actor for a feature that won't ever be used extensively.
Second, due to how AActor gets initialized it may not contain any objects that need construction, unless they are protected. Put them before 'snext' where they are safe.
Finally, if you add new stuff, it needs to be serialized to savegames.

**Review by coelckers — CHANGES_REQUESTED** [review]
One more thing: Comparing names with nullptr is not correct and will cause undefined behavior.

**Comment by ShinyMetagross** [comment]
To point 3, doing so I believe means also checking for null pointers instead of checking for NAME_None on the property itself, which means more has to be processed (if albeit a very small difference). Do we care about that?

**Comment by ShinyMetagross** [comment]
I'm still stumped with the serialization. Looks like modelData isn't null when loaded but there's certainly some undefined behavior going on.

**Comment by ShinyMetagross** [comment]
And one more thing. I don't think it will be as easy as serializing a modelID/skinID alone. These are given out in the order they are pushed to the Models array. I've given a little bit of thought on how to do this, and I would like to know if it would be possible to serialize a models array which just stores models defined by this function (i.e, file paths, skin file, model file), then pushes those on load of the file into the models array. The indices given for modelIDs and skinIDs should be the same. If the file is the same, the order models that were pushed on load time will have the same order and so will the other pushes. Unless there's a better way to do this of course.

**Comment by ShinyMetagross** [comment]
Due to popular demand, I want to extend this function to support surface skins as well before it's integrated.

**Comment by coelckers** [comment]
Please ,notify me when this is ready.

**Comment by ShinyMetagross** [comment]
I am happy with this in it's current state unless you have any other items that need action in regards to it.

**Pull request merged**
