### PR TITLE
Force node rebuilding for Double Impact E1M3 (bad subsector)

### PR DESCRIPTION
**Pull request by Player701**
Another [bad subsector](https://imgur.com/eh7WglL) found in [Double Impact](https://www.doomworld.com/idgames/levels/doom/Ports/d-f/dbimpact) E1M3. This one causes players to bump into an invisible obstacle.

Reproduce with: ```gzdoom -iwad doom -file dbimpact.wad -nomonsters -warp 1 3 +"warp 580 1568"```

Player is stuck and cannot move. Rebuilding nodes fixes the issue.

### CODE REVIEW

**Comment by Player701** [comment]
Addendum: I've found another potential bug (not node-related) on this map. Once you enter the area where you can collect the blue key, you cannot reenter it by normal means (this is by design). A teleporter becomes accessible when you return to the main part of the level, but it doesn't work because the teleport destination is set to appear in multiplayer only. This doesn't look quite right to me especially since that area contains potentially missable items (with +COUNTITEM). Do you think this issue should be addressed as well?

**Comment by coelckers** [comment]
Sounds like screwed up game design to me. I do not know the map so it's hard to assess how likely it is to break progression with this. If it's serious, yes it should be fixed.

**Comment by Player701** [comment]
Well, it surely does not prevent completing the map normally, but it can lock players out of reaching the secret exit because the blue key is required to access it.

**Comment by Player701** [comment]
Having played through the entire mapset, I did find a couple more multiplayer-only teleporters but no permanently missable content. However, since it's not possible to get stuck (much unlike with [the lift in E1M7](https://github.com/coelckers/gzdoom/pull/1210)) nor get locked out of the secret exit, I don't think it's necessary to change anything else on this map.

**Pull request merged**
