### PR TITLE
- Implemented a simple graphics switch. This currently affects NVidia…

### PR DESCRIPTION
**Pull request by raa-eruanna**
… Optimus-enabled notebooks only. (Will implement the ATI Hybrid options if I figure out a way, but without the affected hardware it is impossible for me to do that at this time)

### CODE REVIEW

**Comment by MajorCooke** [comment]
I play on nothing but nvidia notebooks. 24/7. Please implement this!

**Comment by raa-eruanna** [comment]
I don't know if it makes you any happier but I went ahead and removed the menu option for this.

**Comment by MajorCooke** [comment]
Why? If someone has an issue with their graphics card and they want to switch it for performance/testing purposes or as a fallback, that option would be useful.

**Comment by raa-eruanna** [comment]
Graf thinks the menu is getting a little congested. See your Mantis report regarding slow loading times for more info about that. >_>

**Comment by MajorCooke** [comment]
_"The renderer options need to be better sorted, this was one of those issues which didn't sit well with ZDoom, but now it can be addressed. I wouldn't hide the options for the other renderer, but I would hide options for incompatible hardware"_

**Comment by raa-eruanna** [comment]
Yeah ... about that....

I am just as stuck as he is with figuring out whether or not Optimus is activated on a system or not. Supposidly you can just check for the presence of a certain DLL file but I can't find the post that said where/what it is.

And if Graf wants to actually implement it after we find out a method that does work - it's probably going to require even more hacks to the menu, itself, than we already have, which is an unpleasant prospect because one thing that keeps the code from growing is hack after hack after hack.

**Comment by MajorCooke** [comment]
Yeah. That is a bit troubling, and I can see now why you hid the option entirely.

**Comment by coelckers** [comment]
The menu can be taken care of after QZDoom has been merged back and some cleanup can be performed that was close to impossible with ZDoom still being around.

**Comment by ROCKNROLLKID** [comment]
Are you guys merging QZDoom and GZDoom into 1 port now?

**Comment by raa-eruanna** [comment]
This one got pulled in with the QZDoom merge, and is therefore present in 3.0. I am closing this pull request for now - I don't know what Graf wants to do about the menu thing.

**Pull request closed without merging**
