### PR TITLE
Fix crash when following symlinks to nonexistent IWAD files

### PR DESCRIPTION
**Pull request by Cacodemon345**
Fixes issue #1269.

### CODE REVIEW

**Review by alexey-lysiuk — COMMENTED** [review]
Does this fix the case with no permission to read a file? I remember it was a problem at some point.

**Comment by Cacodemon345** [comment]
This PR doesn't fix it yet.

**Comment by Cacodemon345** [comment]
That should fix it.

**Comment by coelckers** [comment]
The Windows case is not ok. GZDoom is strictly UTF-8 throughout but that simple _access function is not compatible with that and may return errors with any file name not entirely consisting of ASCII characters.
This needs to use _waccess and a call to WideString to convert the file name.

**Comment by Cacodemon345** [comment]
Done.

**Pull request merged**
