### PR TITLE
Expose ConsoleState to scripts

### PR DESCRIPTION
**Pull request by nashmuhandes**

### CODE REVIEW

**Review by coelckers — CHANGES_REQUESTED** [review]
Before exporting this you need to make sure that the variable's type is well defined.
Currently it's a typedef to an unsized enum which is not well defined.

**Comment by nashmuhandes** [comment]
> Before exporting this you need to make sure that the variable's type is well defined. Currently it's a typedef to an unsized enum which is not well defined.

Sorry for the noob question. Would simply doing `typedef enum cstate_t : int` suffice?

**Comment by coelckers** [comment]
Yes, but while you are at it, please get rid of the typedef, too. 😉

**Comment by nashmuhandes** [comment]
> Yes, but while you are at it, please get rid of the typedef, too. 😉

Done (I hope!)

**Comment by nashmuhandes** [comment]
Fixed compile errors on Mac and Linux, should be good to go now

**Pull request merged**
