### PR TITLE
SDL: Set icon of created window on startup

### PR DESCRIPTION
**Pull request by Cacodemon345**
Supersedes #1364.

### CODE REVIEW

**Comment by Cacodemon345** [comment]
Will reopen this after fixing compile bugs.

**Review by alexey-lysiuk — COMMENTED** [review]
This looks like a complex solution for a simple problem. I would like to know someone else opinion.

**Comment by coelckers** [comment]
I think the problem is called XPM. Why is it necessary to use such a shit format to provide the icon? Can't it be done by something easier to parse, like PNG where we already have code for?`

**Comment by Cacodemon345** [comment]
The XPM icon has been left there lying unused for 4 years with no sign of its usage in the code ever since it made into the repository.

**Comment by OrdinaryMagician** [comment]
The XPM icon is used by some distro packages for gzdoom.

**Comment by Cacodemon345** [comment]
That explains the existence of it.

**Comment by coelckers** [comment]
Since this is still some messed up code it will be closed now. Please do it right. Either use a sane graphics format or add an XPMTexture class so that the engine gets universal support for the format.

**Pull request closed without merging**
