### PR TITLE
Allow targeting of ARM64 platforms on Windows

### PR DESCRIPTION
**Pull request by madame-rachelle**
This brings about some basic changes that will allow using GZDoom on ARM64 Windows (which is currently available for Windows 10 and Windows Server 2019)

- static linking to opengl32.lib is removed entirely - definitions were replaced with custom dynamic DLL function calls - this affects all Windows builds, but it should be okay, I tested it and it works fine for me.
- crash reporter should be unaffected for intel x64 - however, I removed it completely for arm64. if there is really a need for it someone will have to make one. (arm64 windows is not widely used yet, anyhow... so this should be fine for a more experimental/beta testing phase)

### CODE REVIEW

**Comment by coelckers** [comment]
Are there ARM64 Windows installations supporting OpenGL? Last time I checked it was D3D only.

**Comment by Cacodemon345** [comment]
There's the SoftPoly renderer that could be used to run GZDoom on devices lacking OpenGL support, but there was a bug report by @drfrag666 in the forums that causes GZDoom to crash when using SoftPoly renderer on ARM.

**Comment by coelckers** [comment]
IMO it is pointless to do GZDoom or ARM64 without hardware acceleration. So, does this work?

**Comment by madame-rachelle** [comment]
I know Vulkan works, but the driver vendor has to provide their own drivers for that. I am not 100% sure about OpenGL but since the compatibility pack is available I am also not too worried about that - I think in the long-term, this will work, and it is set up to work once the proper drivers are in place. Other than missing the crash reporter for ARM, it is 100% identical to the Intel Windows version.

**Pull request merged**
