### PR TITLE
Don't autoload zvox.wad anymore

### PR DESCRIPTION
**Pull request by drfrag666**

### CODE REVIEW

**Comment by drfrag666** [comment]
It was just a DM announcer and six wanna be offensive player comments. https://zdoom.org/wiki/Zvox.wad
You can download the thing here: https://www.wad-archive.com/wad/c00e662405992561cbcc8d40712aaaff

**Comment by alexey-lysiuk** [comment]
> BTW why are 32 bit VS builds failing? Something about zmusic.

Nobody cares about 32-bit anymore. Kinda fixed in 3e7061036a695fe5cd977f2eeb1d7bb2c07a61cd.

**Comment by madame-rachelle** [comment]
But why "just" remove it?

**Comment by drfrag666** [comment]
Do you mean changing it for something more useful/exciting?

**Comment by madame-rachelle** [comment]
No, I mean why did you just now decide that this autoload needs to be removed?

**Comment by drfrag666** [comment]
Becouse i actually changed it for something else  and i thought it was no longer useful.

**Pull request closed without merging**
